#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://icon-theme.freedesktop.org/releases/hicolor-icon-theme-0.12.tar.gz"
MD5SUMLIST="55cafbcef8bcf7107f6d502149eb4d87"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

