#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://mirrors.kernel.org/gnu/libtasn1/libtasn1-2.10.tar.gz"
MD5SUMLIST="ef80c227d0dcdc2940fbc58faf8e0cf1"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/libtasn1-2.10
install -v -m644    doc/libtasn1.{html,pdf,ps} \
                    ${FAKEROOT}/usr/share/doc/libtasn1-2.10

make DESTDIR=${FAKEROOT} -C doc/reference install-data-local

#################
} # END OF FILE #
#################

