#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/app/xbitmaps-1.1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/bdftopcf-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/iceauth-1.0.5.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/luit-1.1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/mkfontdir-1.0.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/mkfontscale-1.0.9.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/sessreg-1.0.7.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/setxkbmap-1.2.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/smproxy-1.0.5.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/twm-1.0.7.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/x11perf-1.5.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xauth-1.0.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xbacklight-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xclock-1.0.5.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xcmsdb-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xcursorgen-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xdpyinfo-1.3.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xdriinfo-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xev-1.1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xgamma-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xhost-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xinit-1.3.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xinput-1.5.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xkbcomp-1.2.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xkbevd-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xkbutils-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xkill-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xlsatoms-1.1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xlsclients-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xmodmap-1.0.5.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xpr-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xprop-1.2.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xrandr-1.3.5.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xrdb-1.0.9.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xrefresh-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xset-1.2.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xsetroot-1.1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xvinfo-1.1.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xwd-1.0.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xwininfo-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/app/xwud-1.0.3.tar.bz2"
MD5SUMLIST="f9ddd4e70a5375508b3acaf17be0d0ab
            4a7a4a848c43c42f7d499b60666434a4
            08e3f6b523da8b0af179f22f339508b2
            cb9377b09e562e4084cc614a44df2641
            dc342dd8858416254bb5f71a9ddce589
            3d1dc487f3e859f4e5c46540cb49abd3
            e99172cbd72700eeeae99f64632b5dc2
            2f6df89201eb9a2cbfb905d6b82a191e
            edce41bd7562dcdfb813e05dbeede8ac
            c1c124ff16255d6525a53a0d5cec8bf9
            5c3c7431a38775caaea6051312a49bc9
            105f5b00bb9293b3db36f7e500d4f950
            c9891d6a3f3129d56cede72daa0ba26c
            eaf124bbc9d13e1a12a29faaa2ed3612
            a8f013229f7234d582e0ee2c89879e30
            731c39ea88217c12ddd37f8627d97f3f
            1ef08f4c8d0e669c2edd49e4a1bf650d
            3d3cad4d754e10e325438193433d59fd
            515cfd1fe857b66abe43ec3343634954
            34d22b130bffd8aa857eae6d9da4bbb1
            2be663a0afbcc0856c1591477d5bf32a
            ee234056d8a3dbf37b61b4bcb35b88e4
            1e2f0ad4f3fa833b65c568907f171d28
            35622a497894c1cff9182d42696c3e27
            d8d0bc5935b4b8f016ed92fd369dd385
            52ad6d8d87577a8ac736ab5488bec210
            e7f0d57b6ba49c384e9cf8c9ff3243c1
            c543ccb6489b629d427810d9a57d0724
            760099f0af112401735801e3b9aa8595
            b18850d373f3717dca569377c449d091
            1c2c540d240def3ea65ff2030f059f8a
            d5529dc8d811efabd136ca2d8e857deb
            9735173a84dca9b05e06fd4686196b07
            ed2e48cf33584455d74615ad4bbe4246
            2f63f88ad0dcecd33c8cf000f38e9250
            d44e0057d6722b25d5a314e82e0b7e7c
            b78a2da4cf128775031a5a3422fc0b78
            c88feb501083951a8f47a21aaeb1529d
            ecd9167fbfdfc3cfef7e0bb089edd25b
            9e8b58c8aa6172e87ab4f9cf3612fedd
            a37020053e8ee32c6fd1145242d53ee3"
REQUIRES="libpng mesalib x7lib xcb-util"
TAGS="multi"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

case $(basename "$PWD") in
   twm-[0-9]* )
      sed -i -e '/^rcdir =/s,^\(rcdir = \).*,\1/etc/X11/app-defaults,' \
                src/Makefile.in
      ./configure $XORG_CONFIG
      ;;

   xinit-[0-9]* )
      ./configure $XORG_CONFIG --with-xinitdir=/etc/X11/app-defaults
      ;;
     
   * )
      ./configure $XORG_CONFIG
      ;;
esac
make

make DESTDIR=${FAKEROOT} install

# (*) Use a custom xinitrc system
if [ ! -r ${FAKEROOT}/etc/X11/app-defaults/xinitrc ]; then
    return
fi

mkdir -v ${FAKEROOT}/etc/X11/app-defaults/xinitrc.d

mv -v ${FAKEROOT}/etc/X11/app-defaults/{,xinitrc.d/default.}xinitrc

cat > ${FAKEROOT}/etc/X11/app-defaults/xinitrc << "EOF"
#!/bin/sh

. /etc/X11/app-defaults/xinitrc.d/functions

startSession "${1:-${DEFAULT_SESSION}}"
EOF

cat > ${FAKEROOT}/etc/X11/app-defaults/xinitrc.d/functions << "EOF"
#!/bin/sh
# Functions that list or load xinitrc files.
# Written by Marcel van den Boer

# This variable can be overridden by setting it in /etc/xinitrc.conf
DEFAULT_SESSION="default"

if [ -r /etc/xinitrc.conf ]; then
    . /etc/xinitrc.conf
fi

# Lists all *.xinitrc files in xinitrc.d with underscores replaced by spaces,
# and the suffix '.xinitrc' removed. Entries are sepperated by comma's.
# The default session is also listed first.
# Designed for use by the bootscript for the Slim Display Manager.
listSessions() {
    pushd /etc/X11/app-defaults/xinitrc.d &> /dev/null || {
        echo ""
        return
    }

    for f in $(ls -1 *.xinitrc); do
        local SESSIONS="${SESSIONS},\"$(echo ${f//_/ } | cut -d'.' -f1)\""
    done

    popd > /dev/null

    local FIRST_SESSION="\"$(echo ${DEFAULT_SESSION//_/ } | cut -d'.' -f1)\""

    echo "${FIRST_SESSION}${SESSIONS}"
}

# Loads the specified xinitrc file (as listed by 'listSessions()') or starts
# TWM with a single XTerm if the session does not exist.
startSession() {
    local XINITRC="/etc/X11/app-defaults/xinitrc.d/${1// /_}.xinitrc"
    if [ "${1}" != "" ] && [ -r "${XINITRC}" ]; then
        . "${XINITRC}"
    else
        twm &
        exec xterm -geometry 80x30+0+0 -title \
                "Unable to load specified session. Type 'exit' to return."
    fi
}
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) Properly register all installed fonts for X11
mkdir -p /usr/share/fonts/X11
pushd /usr/share/fonts/X11
for dir in $(ls); do
    pushd ${dir}

    rm -f fonts.scale fonts.dir
    mkfontscale
    mkfontdir

    popd
done
popd

#################
} # END OF FILE #
#################

