#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://download.akonadi-project.org/akonadi-1.5.0.tar.bz2"
MD5SUMLIST="8b0d43b0e947b876a461d90f4b877f54"
REQUIRES="boost shared-mime-info soprano"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

CMAKE_PREFIX_PATH=$QT4DIR \
    cmake -DCMAKE_INSTALL_PREFIX=$KDE4_PREFIX ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

