#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://archive.apache.org/dist/httpd/httpd-2.2.21.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/httpd-2.2.21-config-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/httpd-2.2.21-pcre-8.30-1.patch"
MD5SUMLIST="1696ae62cd879ab1d4dd9ff021a470f2
            dontverify
            dontverify
            dontverify"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -p1 < ../httpd-2.2.21-pcre-8.30-1.patch
patch -Np1 -i ../httpd-2.2.21-config-1.patch

./configure --enable-layout=FHS      \
                               --enable-mods-shared=all \
                               --enable-so
make

make DESTDIR=${FAKEROOT} install
chown -v root:root ${FAKEROOT}/usr/lib/apache/httpd.exp                     \
    ${FAKEROOT}/usr/sbin/{apxs,apachectl,dbmmanage,envvars{,-std}}          \
    ${FAKEROOT}/usr/share/man/man1/{dbmmanage,ht{dbm,digest,passwd}}.1      \
    ${FAKEROOT}/usr/share/man/man8/{ab,apachectl,apxs,htcacheclean,httpd}.8 \
    ${FAKEROOT}/usr/share/man/man8/{logresolve,rotatelogs,suexec}.8
chown -v -R apache:apache ${FAKEROOT}/srv/www

includeBootscript httpd

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 25 apache
useradd -c "Apache Server" -d /dev/null -g apache \
        -s /bin/false -u 25 apache

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

sed -i -e "s/User daemon/User apache/" \
       -e "s/Group daemon/Group apache/" \
    /etc/apache/httpd.conf

#################
} # END OF FILE #
#################

