#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.kde.org/pub/kde/stable/attica/attica-0.2.0.tar.bz2"
MD5SUMLIST="df3dcea0229cfa31539bdd427976e15b"
REQUIRES="cmake qt4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=$KDE4_PREFIX ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

