#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/infosys/servers/isc/bind9/9.8.1-P1/bind-9.8.1-P1.tar.gz"
MD5SUMLIST="afa41f8203d50bedad65071f9b6f96d7"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make -C lib/dns
make -C lib/isc
make -C lib/bind9
make -C lib/isccfg
make -C lib/lwres
make -C bin/dig

make DESTDIR=${FAKEROOT} -C bin/dig install

#################
} # END OF FILE #
#################

