#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/cheese/3.2/cheese-2.30.1.tar.bz2"
MD5SUMLIST="1599fded8a1797ea51fb010af4e6c45b"
REQUIRES="gnome-desktop gst-plugins-base libcanberra librsvg libtheora orbit2 pkgconfig udev-rebuild"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib \
            --disable-scrollkeeper
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

