#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/colord/releases/colord-0.1.14.tar.xz"
MD5SUMLIST="b230ba65a3834d1ee67085d62aa81a16"
REQUIRES="dbus glib2 lcms2 sqlite udev-rebuild"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/colord \
            --localstatedir=/var
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

