#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/dconf/0.10/dconf-0.10.0.tar.xz"
MD5SUMLIST="71894eba6d559fb736a43032929fb98a"
REQUIRES="dbus glib2 gtk+3 libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --libexecdir=$GNOME_PREFIX/lib/dconf
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

