#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.gnu.org/pub/gnu/dejagnu/dejagnu-1.5.tar.gz"
MD5SUMLIST="3df1cbca885e751e22d3ebd1ac64dc3c"
REQUIRES="expect"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-doc

#################
} # END OF FILE #
#################

