#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.stack.nl/pub/doxygen/doxygen-1.7.5.src.tar.gz"
MD5SUMLIST="40912d0a4b8248d78df6f705837dcd80"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix /usr \
            --docdir /usr/share/doc/doxygen-1.7.5
make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} install_docs

#################
} # END OF FILE #
#################

