#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://trac.emma-soft.com/epdfview/chrome/site/releases/epdfview-0.1.7.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/epdfview-0.1.7-fix_nonexisting-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/epdfview-0.1.7-fix_scrolling-1.patch"
MD5SUMLIST="1919bb19c16ef0a97d48b0a8303d3c7b
            dontverify
            dontverify"
REQUIRES="gtk+2 poppler"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../epdfview-0.1.7-fix_nonexisting-1.patch
patch -Np1 -i ../epdfview-0.1.7-fix_scrolling-1.patch
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

