#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/evolution/3.2/evolution-3.2.2.tar.xz"
MD5SUMLIST="1c661fb7a982ba6b3624becaa3079eb8"
REQUIRES="evolution-data-server gnome-desktop gtkhtml libcanberra libunique shared-mime-info"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --libexecdir=$GNOME_PREFIX/lib \
            --enable-nntp \
            --enable-nss \
            --enable-smime \
            --disable-image-inline \
            --disable-pst-import
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

