#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/flac/flac-1.2.1.tar.gz"
MD5SUMLIST="153c8b15a54da428d1f0fadc756c22c7"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/#include <stdio.h>/&\n#include <string.h>/' \
    examples/cpp/encode/file/main.cpp

./configure --prefix=/usr --disable-thorough-tests
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

