#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gir-repository/0.6/gir-repository-0.6.5.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/gir-repository-0.6.5-dbus-glib-2.patch"
MD5SUMLIST="f161fa1ae161e81117af6f4bb79bf344
            dontverify"
REQUIRES="gobject-introspection"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../gir-repository-0.6.5-dbus-glib-2.patch
sed -i 's#abl-0\.0#abl-0.1#' gir/Makefile.in
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

