#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gjs/1.30/gjs-1.30.0.tar.xz"
MD5SUMLIST="908c1c8654d141d64aac07d57de9a457"
REQUIRES="dbus-glib gobject-introspection spidermonkey"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

