#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-bluetooth/3.2/gnome-bluetooth-3.2.1.tar.xz"
MD5SUMLIST="6a2bd7d67395dff90e7b45ecb7f7d89c"
REQUIRES="gconf libnotify nautilus-sendto"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

