#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-panel/3.2/gnome-panel-2.30.2.tar.bz2"
MD5SUMLIST="11b6db12223c70a218a2f4602b1683cc"
REQUIRES="gnome-desktop gnome-menus libbonoboui libcanberra libgweather librsvg libwnck orbit2 pkgconfig"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --localstatedir=/var/lib \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib/gnome-panel \
            --mandir=$(pkg-config \
                --variable=prefix ORBit-2.0)/share/man
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) Set up and populate Gnome's panels
gconftool-2 \
    --config-source="$(gconftool-2 --get-default-source)" --direct \
    --load /etc/gnome/2.30.2/gconf/schemas/panel-default-setup.entries

#################
} # END OF FILE #
#################

