#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-keyring/3.2/gnome-keyring-2.30.3.tar.bz2"
MD5SUMLIST="54cb1835c02a40f27fda73e58da17cc6"
REQUIRES="dbus gtk+2 intltool libgcrypt libtasn1 orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --libexecdir=$(pkg-config \
            --variable=prefix ORBit-2.0)/lib/gnome-keyring \
                --sysconfdir=/etc/gnome/3.2.2 \
            --with-pam-dir=/lib/security \
            --with-dbus-services=/usr/share/dbus-1/services \
            --with-root-certs=/etc/ssl/certs
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

