#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-media/2.32/gnome-media-2.32.0.tar.bz2"
MD5SUMLIST="06fc8c67add34c98bc484e0dbc404d41"
REQUIRES="gconf gnome-doc-utils gstreamer gtk+2 libcanberra orbit2 pkgconfig which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/2.30.2 \
            --localstatedir=/var/lib \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib/gnome-media
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

