#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-applets/3.2/gnome-applets-3.2.1.tar.xz"
MD5SUMLIST="bce6d49f3bb2caff8d91c78599ffcfd0"
REQUIRES="gnome-icon-theme gnome-panel"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --localstatedir=/var/lib \
            --libexecdir=$GNOME_PREFIX/lib/gnome-applets \
            --mandir=$GNOME_PREFIX/share/man
make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} -C man install-man

#################
} # END OF FILE #
#################

