#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.gnupg.org/gcrypt/gpgme/gpgme-1.3.1.tar.bz2"
MD5SUMLIST="90afa8436ce2b2683c001c824bd22601"
REQUIRES="libassuan libgpg-error"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr         \
            --libexecdir=/usr/lib \
            --without-g13
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

