#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.26.3.tar.gz"
MD5SUMLIST="6f45946fa622770c45609778c0a982ee"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

ln -v -s ${FAKEROOT}/usr/share/graphviz/doc \
         ${FAKEROOT}/usr/share/doc/graphviz-2.26.3

#################
} # END OF FILE #
#################

