#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.ghostscript.com/public/ghostscript-9.05.tar.bz2"
MD5SUMLIST="8bcef1f33ddf8a4d12b2cf8da385c191"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

rm -rf expat freetype jpeg lcms2 libpng tiff

rm -rf jasper lcms zlib
./configure --prefix=/usr --enable-dynamic --with-system-libtiff LIBS=-lz
make

make so

bin/gs -Ilib -dBATCH examples/tiger.eps

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} soinstall
install -v -m644 base/*.h ${FAKEROOT}/usr/include/ghostscript
ln -v -s ghostscript ${FAKEROOT}/usr/include/ps

ln -sfv ../ghostscript/9.05/doc ${FAKEROOT}/usr/share/doc/ghostscript-9.05

tar -xvf ../<font-tarball> -C ${FAKEROOT}/usr/share/ghostscript --no-same-owner

#################
} # END OF FILE #
#################

