#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gst-plugins-base/0.10/gst-plugins-base-0.10.35.tar.xz"
MD5SUMLIST="0ababc411b6a372f9e5abca443ebb138"
REQUIRES="gstreamer liboil pango"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/\(.*gtkdoc-rebase --relative.* \)\(;.*\)/\1|| true\2/' \
  docs/libs/Makefile.in
./configure --prefix=/usr --with-gtk=3.0
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

