#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gst-plugins-good/0.10/gst-plugins-good-0.10.30.tar.xz"
MD5SUMLIST="bb9c03d950fe2f9d9392d1b47457440c"
REQUIRES="gst-plugins-base"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc --with-gtk=3.0
make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} -C docs/plugins install-data

#################
} # END OF FILE #
#################

