#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/pub/gnu/guile/guile-2.0.3.tar.xz"
MD5SUMLIST="f8b511ad43bbda0a1cbb1c52ceeebdf7"
REQUIRES="gc libunistring"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/gc_version.h/gc.h/' \
    test-suite/standalone/test-pthread-create-secondary.c

./configure --prefix=/usr
make
make html

makeinfo --plaintext -o doc/r5rs/r5rs.txt   doc/r5rs/r5rs.texi
makeinfo --plaintext -o doc/ref/guile.txt   doc/ref/guile.texi

for DIRNAME in r5rs ref 
do
  make -k -C doc/${DIRNAME} pdf ps 
done
unset DIRNAME

make DESTDIR=${FAKEROOT} install

find examples -name "Makefile*" -exec rm {} \;
install -v -m755 -d ${FAKEROOT}/usr/share/doc/guile-2.0.3
cp -vR examples   ${FAKEROOT}/usr/share/doc/guile-2.0.3

for DIRNAME in r5rs ref
do
  install -v -m755 -d ${FAKEROOT}/usr/share/doc/guile-2.0.3/${DIRNAME}
  install -v -m644    doc/${DIRNAME}/*.txt \
                      ${FAKEROOT}/usr/share/doc/guile-2.0.3/${DIRNAME}
  if [ -d             doc/${DIRNAME}/${DIRNAME}.html ]; then
    cp -v -R          doc/${DIRNAME}/${DIRNAME}.html \
                      ${FAKEROOT}/usr/share/doc/guile-2.0.3/${DIRNAME}
  fi
done

cp -v -R doc/ref/guile.html ${FAKEROOT}/usr/share/doc/guile-2.0.3/ref

for DIRNAME in r5rs ref 
do
  install -v -m644 doc/${DIRNAME}/*.{pdf,ps,dvi} \
                   ${FAKEROOT}/usr/share/doc/guile-2.0.3/${DIRNAME}
done

#################
} # END OF FILE #
#################

