#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.imagemagick.org/pub/ImageMagick/ImageMagick-6.7.3-10.tar.xz"
MD5SUMLIST="6bf001ae206bffe77693732e4e886532"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc \
  --with-modules
make

cd PerlMagick
perl Makefile.PL
make
cd ..

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} -C PerlMagick install

#################
} # END OF FILE #
#################

