#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/gnu/gnusrc/inetutils/inetutils-1.9.1.tar.gz"
MD5SUMLIST="944f7196a2b3dba2d400e9088576000c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr          \
            --libexecdir=/usr/sbin \
            --sysconfdir=/etc      \
            --localstatedir=/var   \
            --disable-logger       \
            --disable-syslogd      \
            --disable-whois        \
            --disable-ifconfig     \
            --disable-hostname     \
            --disable-clients
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

