#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/java-access-bridge/1.26/java-access-bridge-1.26.2.tar.bz2"
MD5SUMLIST="baeac0a4f26f66996f62ffa88d6cd19e"
REQUIRES="at-spi icedtea6 jdk orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0)
make

make DESTDIR=${FAKEROOT} install

cat $(pkg-config --variable=prefix \
    ORBit-2.0)/share/jar/accessibility.properties \
    >> $JAVA_HOME/jre/lib/accessibility.properties
chmod -v 644 $JAVA_HOME/jre/lib/accessibility.properties

ln -v -sf $(pkg-config --variable=prefix \
    ORBit-2.0)/share/jar/gnome-java-bridge.jar \
    $JAVA_HOME/jre/lib/ext

cat >> ~/.orbitrc << "EOF"
ORBIIOPIPv4=1

EOF

#################
} # END OF FILE #
#################

