#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://java.sun.com/javase/downloads/index.jsp"
MD5SUMLIST="ad5ee976522bf5767100a8b4b981c690"
REQUIRES="postlfs"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

chmod 755 jdk-6u18-linux-i586.bin
./jdk-6u18-linux-i586.bin

cd jdk1.6.0_18
install -v -m755 -d ${FAKEROOT}/opt/jdk-6u18
mv -v * ${FAKEROOT}/opt/jdk-6u18
chown -v -R root:root ${FAKEROOT}/opt/jdk-6u18
ln -v -sf xawt/libmawt.so \
    ${FAKEROOT}/opt/jdk-6u18/jre/lib/i386/
cd ..

sed -i 's@XINERAMA@FAKEEXTN@g' \
    ${FAKEROOT}/opt/jdk-6u18/jre/lib/i386/xawt/libmawt.so

cat > ${FAKEROOT}/etc/profile.d/jdk.sh << "EOF"
# Begin /etc/profile.d/jdk.sh

# Set JAVA_HOME directory
JAVA_HOME=/opt/jdk

# Adjust PATH
pathappend ${JAVA_HOME}/bin PATH

# Auto Java CLASSPATH
# Copy jar files to, or create symlinks in this directory
AUTO_CLASSPATH_DIR=/usr/lib/classpath
pathprepend . CLASSPATH
for dir in `find ${AUTO_CLASSPATH_DIR} -type d 2>/dev/null`; do
    pathappend $dir CLASSPATH
done

export JAVA_HOME CLASSPATH
unset AUTO_CLASSPATH_DIR
unset dir

# End /etc/profile.d/jdk.sh
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

ln -v -nsf jdk-6u18 /opt/jdk

#################
} # END OF FILE #
#################

