#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://mirrors.isc.org/pub/kde/stable/4.6.0/src/kdelibs-4.6.0.tar.bz2"
MD5SUMLIST="9ee32f375809a42a4a8d512bd06a612b"
REQUIRES="attica automoc4 docbook docbook-xsl libdbusmenuqt qca soprano strigi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=$KDE4_PREFIX \
      -DCMAKE_PREFIX_PATH=$KDE4_PREFIX \
      -DKDE_DEFAULT_HOME=.kde4 \
      -DSYSCONF_INSTALL_DIR=/etc/kde4 \
      -DDOCBOOKXML_CURRENTDTD_DIR=/usr/share/xml/docbook/xml-dtd-4.5 \
      ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

