#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/trinity/kdenetwork-3.5.13.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/kdenetwork-3.5.13-upstream_fixes-1.patch"
MD5SUMLIST="349f197c9af4bf0d9b8773f26829415e
            dontverify
            dontverify"
REQUIRES="kdebase"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../kdenetwork-3.5.13-upstream_fixes-1.patch

MAKEDIR=/tmp/buildkdenet
KDENET=`pwd`
rm -rf   $MAKEDIR
mkdir -p $MAKEDIR
cd       $MAKEDIR

cmake -DCMAKE_INSTALL_PREFIX=$TRINITY_PREFIX    \
      -DCMAKE_VERBOSE_MAKEFILE=ON               \
      -DWITH_JINGLE=ON                          \
      -DWITH_SPEEX=ON                           \
      -DWITH_WEBCAM=ON                          \
      -DWITH_GSM=OFF                            \
      -DWITH_ARTS=ON                            \
      -DBUILD_KOPETE_PROTOCOL_ALL=ON            \
      -DBUILD_KOPETE_PROTOCOL_GADU=OFF          \
      -DBUILD_KOPETE_PROTOCOL_MEANWHILE=OFF     \
      -DBUILD_KOPETE_PLUGIN_ALL=ON              \
      -DBUILD_ALL=ON                            \
      $KDENET

unset MAKEDIR KDENET
make

make DESTDIR=${FAKEROOT} install

includeBootscript lisa

#################
} # END OF FILE #
#################

