#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/leafnode/leafnode-1.11.5.tar.bz2"
MD5SUMLIST="88552c5cc91cb27146c8906b2d33289d"
REQUIRES="pcre tcpwrappers"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
    --localstatedir=/var --sysconfdir=/etc/leafnode \
    --with-lockfile=/var/lock/leafnode/fetchnews.lck
make

make DESTDIR=${FAKEROOT} install

cat > ${FAKEROOT}/etc/nntpserver << "EOF"
127.0.0.1

EOF

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 36 news
useradd -c "Leafnode News Server" -d /var/spool/news -g news \
        -u 36 news

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

cp /etc/leafnode/config.example /etc/leafnode/config

echo "nntp stream tcp nowait news /usr/sbin/tcpd /usr/sbin/leafnode" \
>> /etc/inetd.conf

#################
} # END OF FILE #
#################

