#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libgtop/2.28/libgtop-2.28.1.tar.bz2"
MD5SUMLIST="994c299b6dba330524a67ea45776b3ab"
REQUIRES="glib2 intltool orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --infodir=$(pkg-config --variable=prefix ORBit-2.0)/share/info
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d $(pkg-config \
        --variable=prefix ORBit-2.0)/lib/libgtop/examples
install -v -m755 examples/.libs/* \
        $(pkg-config --variable=prefix ORBit-2.0)/lib/libgtop/examples

#################
} # END OF FILE #
#################

