#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libgnome/2.32/libgnome-2.32.1.tar.bz2"
MD5SUMLIST="a4345e6087ae6195d65a4674ffdca559"
REQUIRES="esound gnome-vfs libbonobo orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################


./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/2.30.2                                \
            --localstatedir=/var/lib                           \
            --mandir=$(pkg-config --variable=prefix ORBit-2.0)/share/man
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

