#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libgnomeprint/2.18/libgnomeprint-2.18.7.tar.bz2"
MD5SUMLIST="d66b81ee8aa3b3a33f5efc9a47ce07e3"
REQUIRES="intltool libart_lgpl libxml2 orbit2 pango perl-xml-parser pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --disable-gtk-doc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

