#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://mikmod.raphnet.net/files/libmikmod-3.1.11.tar.gz"
MD5SUMLIST="705106da305e8de191549f1e7393185c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../libmikmod-3.1.11-a.diff
sed -i -e "s/VERSION=10/VERSION=11/" \
       -e "s/sys_asoundlib/alsa_asoundlib/" \
       -e "s/snd_cards/snd_card_load/g" \
       -e "s|sys/asoundlib.h|alsa/asoundlib.h|g" \
       -e "s/^LIBOBJS/#LIBOBJS/" \
    configure.in
autoconf
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
chmod 755 ${FAKEROOT}/usr/lib/libmikmod.so.2.0.4
install -v -m644 -D docs/mikmod.html \
    ${FAKEROOT}/usr/share/doc/libmikmod-3.1.11/mikmod.html

#################
} # END OF FILE #
#################

