#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/project/libtirpc/libtirpc/0.2.2/libtirpc-0.2.2.tar.bz2
          ftp://anduin.linuxfromscratch.org/other/rpcnis-headers.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/libtirpc-0.2.2-remove-nis-2.patch"
MD5SUMLIST="74c41c15c2909f7d11d9c7bfa7db6273
            dontverify
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

if [ ! -r /usr/include/rpc/rpc.h ]; then
   tar -xvf ../rpcnis-headers.tar.bz2 -C /usr/include
fi

patch -Np1 -i ../libtirpc-0.2.2-remove-nis-2.patch
autoreconf
./configure --prefix=/usr --libdir=/lib
make

make DESTDIR=${FAKEROOT} pkgconfigdir=/usr/lib/pkgconfig install
mv -v ${FAKEROOT}/lib/libtirpc.*a ${FAKEROOT}/usr/lib

#################
} # END OF FILE #
#################

