#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2"
MD5SUMLIST="292ab65cedd5021d6b7ddd117e07cd8e"
REQUIRES="libogg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

cd examples/.libs
for E in *; do
install -v -m755 $E ${FAKEROOT}/usr/bin/theora_${E}; done

#################
} # END OF FILE #
#################

