#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.ibiblio.org/pub/Linux/utils/file/managers/mc/mc-4.6.1.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/mc-4.6.1-bash32-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/mc-4.6.1-debian_fixes-1.patch"
MD5SUMLIST="18b20db6e40480a53bac2870c56fc3c4
            dontverify
            dontverify"
REQUIRES="glib2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../mc-4.6.1-bash32-1.patch

patch -Np1 -i ../mc-4.6.1-debian_fixes-1.patch

CPPFLAGS="-DUTF8" ./configure --prefix=/usr \
            --enable-charset
make

for file in lib/mc.hint{,.es,.it,.nl} doc/{es,it}/mc.hlp.*
do
    iconv -f ISO-8859-1 -t UTF-8 ${file} > ${file}.utf8
    mv ${file}.utf8 ${file}
done
for file in lib/mc.hint{.cs,.hu,.pl} doc/{hu,pl}/mc.hlp.*
do
    iconv -f ISO-8859-2 -t UTF-8 ${file} > ${file}.utf8
    mv ${file}.utf8 ${file}
done
for file in lib/mc.hint.sr doc/sr/mc.hlp.sr
do
    iconv -f ISO-8859-5 -t UTF-8 ${file} > ${file}.utf8
    mv ${file}.utf8 ${file}
done
for file in doc/ru/mc.hlp.ru lib/mc.hint.ru
do
    iconv -f KOI8-R -t UTF-8 ${file} > ${file}.utf8
    mv ${file}.utf8 ${file}
done
iconv -f KOI8-U -t UTF-8 lib/mc.hint.uk > lib/mc.hint.uk.utf8
mv lib/mc.hint.uk.utf8 lib/mc.hint.uk
iconv -f BIG5 -t UTF-8 lib/mc.hint.zh > lib/mc.hint.zh.utf8
mv lib/mc.hint.zh.utf8 lib/mc.hint.zh

make DESTDIR=${FAKEROOT} install
chmod 1755 ${FAKEROOT}/usr/lib/mc/cons.saver

#################
} # END OF FILE #
#################

