#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://web.mit.edu/kerberos/www/dist/krb5/1.6/krb5-1.6-signed.tar
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="a365e39ff7d39639556c2797a0e1c3f4
            dontverify"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

gpg - -verify krb5-1.6.tar.gz.asc

cd src
./configure CPPFLAGS="-I/usr/include/et -I/usr/include/ss" \
            --prefix=/usr \
            --sysconfdir=/etc/krb5 \
            --localstatedir=/var/lib \
            --with-system-et \
            --with-system-ss \
            --enable-dns-for-realm \
            --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/ksu ${FAKEROOT}/bin
chmod -v 755 ${FAKEROOT}/bin/ksu
mv -v ${FAKEROOT}/usr/lib/libkrb5.so.3* ${FAKEROOT}/lib
mv -v ${FAKEROOT}/usr/lib/libk5crypto.so.3* ${FAKEROOT}/lib
mv -v ${FAKEROOT}/usr/lib/libkrb5support.so.0* ${FAKEROOT}/lib

ln -v -sf ../../lib/libkrb5.so.3.3 ${FAKEROOT}/usr/lib/libkrb5.so
ln -v -sf ../../lib/libk5crypto.so.3.1 ${FAKEROOT}/usr/lib/libk5crypto.so
ln -v -sf ../../lib/libkrb5support.so.0.1 ${FAKEROOT}/usr/lib/libkrb5support.so

install -m644 -v ../doc/*.info* ${FAKEROOT}/usr/share/info
for INFOFILE in 425 5-admin 5-install 5-user; do
    rm ../doc/krb$INFOFILE.info*
done

install -m755 -v -d ${FAKEROOT}/usr/share/doc/krb5-1.6
cp -Rv ../doc/* ${FAKEROOT}/usr/share/doc/krb5-1.6

mv -v ${FAKEROOT}/bin/login ${FAKEROOT}/bin/login.shadow
install -m755 -v ${FAKEROOT}/usr/sbin/login.krb5 ${FAKEROOT}/bin/login

mv -v ${FAKEROOT}/usr/lib/libdes425.so.3* ${FAKEROOT}/lib
mv -v ${FAKEROOT}/usr/lib/libkrb4.so.2* ${FAKEROOT}/lib

ln -v -sf ../../lib/libdes425.so.3.0 ${FAKEROOT}/usr/lib/libdes425.so
ln -v -sf ../../lib/libkrb4.so.2.0 ${FAKEROOT}/usr/lib/libkrb4.so

ldconfig

install -v -m755 -d ${FAKEROOT}/etc/krb5
cat > ${FAKEROOT}/etc/krb5/krb5.conf << "EOF"
# Begin /etc/krb5/krb5.conf

[libdefaults]
    default_realm = <LFS.ORG>
    encrypt = true

[realms]
    <LFS.ORG> = {
        kdc = <belgarath.lfs.org>
        admin_server = <belgarath.lfs.org>
        dict_file = /usr/share/dict/words
    }

[domain_realm]
    .<lfs.org> = <LFS.ORG>

[logging]
    kdc = SYSLOG[:INFO[:AUTH]]
    admin_server = SYSLOG[INFO[:AUTH]]
    default = SYSLOG[[:SYS]]

# End /etc/krb5/krb5.conf
EOF

includeBootscript kerberos

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

kdb5_util create -r <LFS.ORG> -s

kadmin.local
kadmin: add_policy dict-only
kadmin: addprinc -policy dict-only <loginname>

kadmin: addprinc -randkey host/<belgarath.lfs.org>

kadmin: ktadd host/<belgarath.lfs.org>

kadmin: addprinc -randkey ftp/<belgarath.lfs.org>
kadmin: ktadd ftp/<belgarath.lfs.org>

/usr/sbin/krb5kdc &

kinit <loginname>

klist

ktutil
ktutil: rkt /etc/krb5/krb5.keytab
ktutil: l

#################
} # END OF FILE #
#################

