#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://0pointer.de/lennart/projects/mod_dnssd/mod_dnssd-0.6.tar.gz"
MD5SUMLIST="bed3d95a98168bf0515922d1c05020c5"
REQUIRES="apache avahi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-lynx
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

