#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-5.9p1.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="afe17eee7e98d3b8550cc349834a85d0
            dontverify"
REQUIRES="openssl"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

install -v -m700 -d ${FAKEROOT}/var/lib/sshd
chown -v root:sys ${FAKEROOT}/var/lib/sshd
groupadd -g 50 sshd
useradd -c 'sshd PrivSep' -d ${FAKEROOT}/var/lib/sshd -g sshd \
    -s ${FAKEROOT}/bin/false -u 50 sshd

sed -i 's@-lcrypto@/usr/lib/libcrypto.a -ldl@' configure

sed -i.bak '/K5LIBS=/s/ -ldes//' configure
./configure --prefix=/usr \
            --sysconfdir=/etc/ssh \
            --datadir=/usr/share/sshd \
            --libexecdir=/usr/lib/openssh \
            --with-md5-passwords \
            --with-privsep-path=/var/lib/sshd
make

make DESTDIR=${FAKEROOT} tests 2>&1 | tee check.log
grep FATAL check.log

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/openssh-5.9p1
install -v -m644 INSTALL LICENCE OVERVIEW README* \
    ${FAKEROOT}/usr/share/doc/openssh-5.9p1

includeBootscript sshd

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo "PermitRootLogin no" >> /etc/ssh/sshd_config

sed 's@d/login@d/sshd@g' /etc/pam.d/login > /etc/pam.d/sshd
chmod 644 /etc/pam.d/sshd
echo "USEPAM yes" >> /etc/ssh/sshd_config

#################
} # END OF FILE #
#################

