#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://freedesktop.org/software/pulseaudio/releases/pulseaudio-0.9.23.tar.gz"
MD5SUMLIST="7391205a337d1e04a9ff38025f684034"
REQUIRES="intltool libsndfile speex"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/pulseaudio \
            --with-module-dir=/usr/lib/pulseaudio/modules \
            --with-udev-rules-dir=/etc/udev/rules.d
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

