#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://delta.affinix.com/download/qca/2.0/qca-2.0.3.tar.bz2"
MD5SUMLIST="fc15bd4da22b8096c51fcfe52d2fa309"
REQUIRES="pkgconfig qt4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix QtCore)
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

