#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://get.qt.nokia.com/qt/source/qt-everywhere-opensource-src-4.8.0.tar.gz"
MD5SUMLIST="e8a5fdbeba2927c948d9f477a6abe904"
REQUIRES="x-window-system"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure -prefix /opt/qt-4.8.0  \
            -release                 \
            -nomake examples         \
            -nomake demos            \
            -system-sqlite           \
            -no-nis                  \

make

make DESTDIR=${FAKEROOT} install

ln -v -sfn qt-4.8.0 ${FAKEROOT}/opt/qt

# (*) Utilize the ld.so.conf directory
mkdir -pv ${FAKEROOT}/etc/ld.so.conf.d

cat >> ${FAKEROOT}/etc/ld.so.conf.d/qt4.conf << "EOF"
# Begin qt addition to /etc/ld.so.conf.d/qt4.conf

/opt/qt/lib

# End qt addition
EOF
ldconfig

#################
} # END OF FILE #
#################

