#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/rpcbind/rpcbind-0.2.0.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="1a77ddb1aaea8099ab19c351eeb26316
            dontverify"
REQUIRES="libtirpc"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/^sunrpc/rpcbind/' /etc/services

./configure --prefix=/usr --bindir=/sbin
make

make DESTDIR=${FAKEROOT} install

includeBootscript rpcbind

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

rpcbind:  127.0.0.1

#################
} # END OF FILE #
#################

