#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.2-p290.tar.bz2"
MD5SUMLIST="096758c3e853b839dc980b183227b182"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --enable-shared  \
            --enable-pthread \
            --enable-install-doc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

