#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://samba.org/samba/ftp/stable/samba-3.6.1.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="5291717be0734e07dc07b6110e162e87
            dontverify"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cd source3

./configure                            \
    --prefix=/usr                      \
    --sysconfdir=/etc                  \
    --localstatedir=/var               \
    --with-piddir=/run                 \
    --with-pammodulesdir=/lib/security \
    --with-fhs                         \
    --enable-nss-wrapper               \
    --enable-socket-wrapper
make

make DESTDIR=${FAKEROOT} install

install -v -m755 ../nsswitch/libnss_win{s,bind}.so ${FAKEROOT}/lib
ln -v -sf libnss_winbind.so ${FAKEROOT}/lib/libnss_winbind.so.2
ln -v -sf libnss_wins.so    ${FAKEROOT}/lib/libnss_wins.so.2

install -v -m644 ../examples/smb.conf.default ${FAKEROOT}/etc/samba

if [ -d ${FAKEROOT}/etc/openldap/schema ]; then
    install -v -m644    ../examples/LDAP/README              \
                        ${FAKEROOT}/etc/openldap/schema/README.LDAP
    install -v -m644    ../examples/LDAP/samba*              \
                        ${FAKEROOT}/etc/openldap/schema
    install -v -m755    ../examples/LDAP/{convert*,get*,ol*} \
                        ${FAKEROOT}/etc/openldap/schema
fi

install -v -m755 -d ${FAKEROOT}/usr/share/doc/samba-3.6.1
install -v -m644    ../docs/*.pdf \
                    ${FAKEROOT}/usr/share/doc/samba-3.6.1
ln -v -s ../../samba/swat  ${FAKEROOT}/usr/share/doc/samba-3.6.1

includeBootscript samba

includeBootscript winbind

cat >> ${FAKEROOT}/etc/stunnel/swat.conf << "EOF"
; File: /etc/stunnel/swat.conf

pid    = /run/stunnel-swat.pid
setuid = root
setgid = root
cert   = /etc/stunnel/stunnel.pem

[swat]
accept = swat
exec   = /usr/sbin/swat

EOF

includeBootscript swat

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

ln -v -sf /usr/bin/smbspool /usr/lib/cups/backend/smb

groupadd -g 99 nogroup
useradd -c "Unprivileged Nobody" -d /dev/null -g nogroup \
    -s /bin/false -u 99 nobody

echo "swat            905/tcp" >> /etc/services

echo "swat stream tcp nowait.5 root /usr/sbin/swat swat >> /etc/inetd.conf

#################
} # END OF FILE #
#################

