#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/seahorse/3.2/seahorse-2.30.1.tar.bz2"
MD5SUMLIST="b332279b34acca952807e31534fec592"
REQUIRES="gconf gnome-doc-utils gnupg gnupg2 gpgme libgnome-keyring orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --disable-scrollkeeper
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

