#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/seahorse-plugins/3.2/seahorse-plugins-2.30.1.tar.bz2"
MD5SUMLIST="cb8a86a1039054b621f6419ac2219695"
REQUIRES="orbit2 pkgconfig seahorse"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --disable-scrollkeeper \
            --disable-update-mime-database
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

