#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/strigi/strigi-0.6.4.tar.bz2"
MD5SUMLIST="ddbd274cb31d65be6a78da58fc09079a"
REQUIRES="clucene cmake expat libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "s;#include \"jsgzipcompressstream.h\";#include <stdio.h>\n&;" \
           src/luceneindexer/jsgzipcompressstream.cpp
sed -i "s;#include \"sqliteindexmanager.h\";#include <stdio.h>\n&;" \
           src/sqliteindexer/sqliteindexmanager.cpp
sed -i "s;#include <cerrno>;#include <stdio.h>\n&;" \
           src/daemon/eventlistener/famlistener.cpp
sed -i "s;#include <stdlib.h>;&\n#include <stdio.h>;" \
           src/daemon/strigithread.cpp

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr \
          -DENABLE_EXPAT=ON \
          -DENABLE_FAM=ON \
          -DENABLE_SQLITE=OFF ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

