#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.sudo.ws/sudo/dist/sudo-1.8.2.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/sudo-1.8.2-fprintf_debug-1.patch"
MD5SUMLIST="000f458e7391be9fdf459a9ad6a4912a
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -p1 < ../sudo-1.8.2-fprintf_debug-1.patch
./configure --prefix=/usr \
            --libexecdir=/usr/lib \
            --with-ignore-dot \
            --with-all-insults \
            --enable-shell-sets-home \
            --disable-root-sudo \
            --with-logfac=auth \
            --without-pam \
            --without-sendmail
make

make DESTDIR=${FAKEROOT} install

cat > ${FAKEROOT}/etc/pam.d/sudo << "EOF"
# Begin /etc/pam.d/sudo

# include the default auth settings
auth      include     system-auth

# include the default account settings
account   include     system-account

# Use xauth keys (if available)
session   optional    pam_xauth.so

# Set default environment variables for the service user
session   required    pam_env.so

# include system session defaults
session   include     system-session

# End /etc/pam.d/sudo
EOF
chmod 644 ${FAKEROOT}/etc/pam.d/sudo

#################
} # END OF FILE #
#################

