#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://perso.wanadoo.fr/sebastien.godard/sysstat-10.0.2.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="0dc5c4baf4165658450dd60913aa75bc
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sa_lib_dir=/usr/lib/sa    \
sa_dir=/var/log/sa        \
conf_dir=/etc/sysconfig   \
./configure --prefix=/usr \
            --disable-man-group
make

make DESTDIR=${FAKEROOT} install

includeBootscript sysstat

#################
} # END OF FILE #
#################

