#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.sfr-fresh.com/unix/misc/tcsh-6.17.00.tar.gz"
MD5SUMLIST="c47de903e3d52f6824c8dd0c91eeb477"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -e 's|\$\*|#&|' -e 's|fR/g|&m|' tcsh.man2html
./configure --prefix=/usr --bindir=/bin
make
sh ./tcsh.man2html

make DESTDIR=${FAKEROOT} install install.man
ln -v -sf tcsh   ${FAKEROOT}/bin/csh
ln -v -sf tcsh.1 ${FAKEROOT}/usr/share/man/man1/csh.1
install -v -m755 -d          ${FAKEROOT}/usr/share/doc/tcsh-6.17.00/html
install -v -m644 tcsh.html/* ${FAKEROOT}/usr/share/doc/tcsh-6.17.00/html
install -v -m644 FAQ         ${FAKEROOT}/usr/share/doc/tcsh-6.17.00

cat >> ${FAKEROOT}/etc/shells << "EOF"
/bin/tcsh
/bin/csh
EOF

#################
} # END OF FILE #
#################

