#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://telepathy.freedesktop.org/releases/telepathy-mission-control/telepathy-mission-control-5.9.1.tar.gz"
MD5SUMLIST="7bbff153a417403633fc0c96483a77d8"
REQUIRES="dbus dbus-glib gconf gnome-keyring telepathy-glib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --libexecdir=/usr/lib/telepathy-mission-control
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

