#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/linux-udf/udftools-1.0.0b3.tar.gz
          http://w1.894.telia.com/~u89404340/patches/packet/udftools-1.0.0b3.patch.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/udftools-1.0.0b3-fixes-1.patch"
MD5SUMLIST="2f491ddd63f31040797236fe18db9e60
            dontverify
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

bzcat ../udftools-1.0.0b3.patch.bz2 | patch -Np1
patch -Np1 -i ../udftools-1.0.0b3-fixes-1.patch
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

