#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.rarlab.com/rar/unrarsrc-3.9.10.tar.gz"
MD5SUMLIST="3c130ae52ff9fece50af988c343e396d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make -f makefile.unix

install -v -m755 unrar ${FAKEROOT}/usr/bin

#################
} # END OF FILE #
#################

