#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/vorbis/vorbis-tools-1.2.0.tar.gz"
MD5SUMLIST="df976d24e51ef3d87cd462edf747bf9a"
REQUIRES="libvorbis"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --enable-vcut \
            --without-curl
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

