#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/vte/0.24/vte-0.24.2.tar.bz2"
MD5SUMLIST="76d5bca203245fedf7eac6d434a16bd9"
REQUIRES="glib2 gtk+2 intltool"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's%\\177:%&kh=\\EOH:@7=\\EOF:%' termcaps/xterm
./configure --prefix=/usr \
            --libexecdir=/usr/lib/vte
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

