#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.xchat.org/files/source/2.8/xchat-2.8.4.tar.bz2"
MD5SUMLIST="66d60febc62a01bafac9bb3a35fb37ae"
REQUIRES="glib2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../xc284-scrollbmkdir.diff
./configure --prefix=/usr \
            --sysconfdir=/etc/gnome/3.2.2 \
            --enable-shm
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/xchat-2.8.4
install -v -m644    README faq.html \
                    ${FAKEROOT}/usr/share/doc/xchat-2.8.4

#################
} # END OF FILE #
#################

