#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://releases.mozilla.org/pub/mozilla.org/firefox/releases/10.0/source/firefox-10.0.source.tar.bz2"
MD5SUMLIST="13c61203ccfa583e5a54b4dc22f41233"
REQUIRES="alsa-lib gtk+2 unzip zip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cat > mozconfig << "EOF"
# If you have a multicore machine you can speed up the build by running
# several jobs at once, but if you have a single core, delete this line:
mk_add_options MOZ_MAKE_FLAGS="-j4"

# If you have installed Yasm delete this option:
ac_add_options --disable-webm

# If you have installed DBus-Glib delete this option:
ac_add_options --disable-dbus

# If you have installed wireless-tools delete this option:
ac_add_options --disable-necko-wifi

# If you have installed libnotify delete this option:
ac_add_options --disable-libnotify

# Uncomment these if you have installed them:
# ac_add_options --with-system-nspr
# ac_add_options --with-system-nss
# ac_add_options --enable-system-sqlite
# ac_add_options --with-system-libvpx
# ac_add_options --enable-startup-notification
# ac_add_options --enable-system-hunspell
# ac_add_options --with-system-libevent

mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/xulrunner-build-dir
ac_add_options --prefix=/usr
ac_add_options --enable-application=xulrunner
ac_add_options --with-pthreads
ac_add_options --enable-system-ffi
ac_add_options --with-system-jpeg
ac_add_options --with-system-png
ac_add_options --enable-system-cairo
ac_add_options --with-system-zlib
ac_add_options --enable-shared
ac_add_options --disable-static
ac_add_options --disable-debug
ac_add_options --disable-crashreporter
ac_add_options --disable-installer
ac_add_options --disable-updater
ac_add_options --disable-tests
EOF

sed -i 's#VPX_CODEC_USE_INPUT_PARTITION#VPX_CODEC_USE_INPUT_FRAGMENTS#' configure
sed -i '/Version/aRequires: nspr >= 4.8.9' xulrunner/installer/libxul-embedding.pc.in
make -f client.mk

make DESTDIR=${FAKEROOT} -C xulrunner-build-dir install
mkdir -p ${FAKEROOT}/usr/lib/mozilla
rm -rf ${FAKEROOT}/usr/lib/xulrunner-10.0/plugins
ln -sv ../mozilla/plugins ${FAKEROOT}/usr/lib/xulrunner-10.0
chown -Rv root:root ${FAKEROOT}/usr/{include,lib,share/idl}/xulrunner-*

for DL in libnss3.so libnssutil3.so libsmime3.so \
  libssl3.so libsoftokn3.so  libplds4.so libplc4.so libnspr4.so
do ln -sv xulrunner-10.0/${DL} ${FAKEROOT}/usr/lib
done
unset DL

#################
} # END OF FILE #
#################

