#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.xvid.org/downloads/xvidcore-1.2.2.tar.gz"
MD5SUMLIST="2ce9b1d280d703b5bc8e702c79e660b5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cd build/generic
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

chmod -v 755 ${FAKEROOT}/usr/lib/libxvidcore.so.4.2
ln -v -sf libxvidcore.so.4.2 ${FAKEROOT}/usr/lib/libxvidcore.so.4
ln -v -sf libxvidcore.so.4   ${FAKEROOT}/usr/lib/libxvidcore.so

install -v -m755 -d ${FAKEROOT}/usr/share/doc/xvidcore-1.2.2/examples
install -v -m644 ../../doc/* ${FAKEROOT}/usr/share/doc/xvidcore-1.2.2
install -v -m644 ../../examples/* \
    ${FAKEROOT}/usr/share/doc/xvidcore-1.2.2/examples

#################
} # END OF FILE #
#################

