#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/yelp/3.2/yelp-2.30.1.tar.bz2"
MD5SUMLIST="afd638cdaea1fcb9821ece88b819a022"
REQUIRES="gconf gnome-doc-utils orbit2 pkgconfig startup-notification xulrunner"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --localstatedir=/var/lib \
            --enable-cpp-rtti
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

