#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/zsh/zsh-4.3.10.tar.bz2
          http://downloads.sourceforge.net/zsh/zsh-4.3.10-doc.tar.bz2"
MD5SUMLIST="74c5b275544400082a1cde806c98682a
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar --strip-components=1 -xvf ../zsh-4.3.10-doc.tar.bz2

./configure --prefix=/usr \
            --bindir=/bin \
            --sysconfdir=/etc/zsh \
            --enable-etcdir=/etc/zsh
make

makeinfo  Doc/zsh.texi --html      -o Doc/html
makeinfo  Doc/zsh.texi --html --no-split --no-headers      \
                                   -o Doc/zsh.html
makeinfo  Doc/zsh.texi --plaintext -o Doc/zsh.txt

texi2pdf  Doc/zsh.texi -o Doc/zsh.pdf

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} infodir=/usr/share/info install.info

install -v -m755 -d ${FAKEROOT}/usr/share/doc/zsh-4.3.10/html
install -v -m644    Doc/html/* \
                    ${FAKEROOT}/usr/share/doc/zsh-4.3.10/html
install -v -m644    Doc/zsh.{html,txt} \
                    ${FAKEROOT}/usr/share/doc/zsh-4.3.10

make DESTDIR=${FAKEROOT} htmldir=/usr/share/doc/zsh-4.3.10/html install.html
install -v -m644 Doc/zsh.dvi ${FAKEROOT}/usr/share/doc/zsh-4.3.10

install -v -m644 Doc/zsh.pdf \
        ${FAKEROOT}/usr/share/doc/zsh-4.3.10

cat >> ${FAKEROOT}/etc/shells << "EOF"
/bin/zsh
/bin/zsh-4.3.10
EOF

#################
} # END OF FILE #
#################

