#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/alacarte/0.13/alacarte-0.13.1.tar.bz2"
MD5SUMLIST="b45232eaf093e7e1fbf99b335d8b880c"
REQUIRES="gnome-menus orbit2 pkgconfig pygobject2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0)
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

