#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/opsys/linux/alsa/oss-lib/alsa-oss-1.0.17.tar.bz2"
MD5SUMLIST="1b1850c2fc91476a73d50f537cbd402f"
REQUIRES="alsa-lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

