#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/trinity/arts-3.5.13.tar.gz"
MD5SUMLIST="109124dabb1aaa9d44eb32e43b549142"
REQUIRES="alsa audiofile cmake glib2 libmad libvorbis qt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

BUILD=/tmp/buildarts
ARTS=`pwd`
rm -rf   $BUILD
mkdir -p $BUILD
cd       $BUILD

cmake $ARTS                              \
  -DCMAKE_INSTALL_PREFIX=$TRINITY_PREFIX \
  -DCMAKE_VERBOSE_MAKEFILE=ON

unset ARTS BUILD
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

