#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/autogen/rel5.12/autogen-5.12.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/autogen-5.12-build_shared-1.patch"
MD5SUMLIST="126e56be629cda747390e8ba9be71e4b
            dontverify"
REQUIRES="guile"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../autogen-5.12-build_shared-1.patch

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

