#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.kernel.org/pub/linux/daemons/autofs/v5/autofs-5.0.5.tar.bz2"
MD5SUMLIST="a1d262cb6ebef0c2dd0fe22232fb3d5a"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

for f in `cat ../patch_order-5.0.5`; do
  patch -Np1 -i ../$f
done
./configure --prefix=/ --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install
ln -sf  ../init.d/autofs ${FAKEROOT}/etc/rc.d/rcsysinit.d/S52autofs

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

mv /etc/auto.master /etc/auto.master.bak
cat > /etc/auto.master << "EOF"
# Begin /etc/auto.master

/media/auto  /etc/auto.misc  --ghost
#/home        /etc/auto.home

# End /etc/auto.master
EOF

#################
} # END OF FILE #
#################

