#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://alpha.gnu.org/gnu//bc/bc-1.06.95.tar.bz2"
MD5SUMLIST="5126a721b73f97d715bb72c13c889035"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-readline
make

echo "quit" | ./bc/bc -l Test/checklib.b

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

