#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/brasero/3.2/brasero-3.2.0.tar.xz"
MD5SUMLIST="b4b13ce81a344b81ddd3a64a3003787b"
REQUIRES="gconf gnome-doc-utils gst-plugins-base libcanberra libunique which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --mandir=$GNOME_PREFIX/share/man
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

