#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ffmpeg.org/releases/ffmpeg-0.10.tar.bz2"
MD5SUMLIST="dc665cc599a739e3c5262ccdac13d129"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build
../configure --prefix=/usr --enable-shared --disable-static --enable-gpl
make

gcc ../tools/qt-faststart.c -o qt-faststart

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-man
mkdir ${FAKEROOT}/usr/share/doc/ffmpeg-0.10
cp ../doc/*.txt ${FAKEROOT}/usr/share/doc/ffmpeg-0.10

mkdir ${FAKEROOT}/usr/share/doc/ffmpeg-0.10/api
cp -v doxy/* ${FAKEROOT}/usr/share/doc/ffmpeg-0.10/api

cp qt-faststart ${FAKEROOT}/usr/bin

#################
} # END OF FILE #
#################

