#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/graphics/gimp/gegl/0.1//gegl-0.1.8.tar.bz2"
MD5SUMLIST="c8279b86b3d584ee4f503839fc500425"
REQUIRES="babl glib2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m644 docs/*.{css,html} ${FAKEROOT}/usr/share/gtk-doc/html/gegl

#################
} # END OF FILE #
#################

