#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-disk-utility/3.0/gnome-disk-utility-3.0.2.tar.xz"
MD5SUMLIST="3916e3abfb3190367c7108b7a034b70d"
REQUIRES="avahi gnome-doc-utils gtk+3 libnotify libunique udisks which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --libexecdir=$GNOME_PREFIX/lib/gnome-disk-utility \
            --disable-gtk-doc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

