#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-speech/0.4/gnome-speech-0.4.25.tar.bz2"
MD5SUMLIST="89cbc23fc131c33396c0346085759f63"
REQUIRES="libbonobo orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0)
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D doc/gnome-speech.html \
    $(pkg-config --variable=prefix \
    ORBit-2.0)/share/doc/gnome-speech-0.4.25/gnome-speech.html

#################
} # END OF FILE #
#################

