#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gtk+/3.2/gtk+-3.2.3.tar.xz"
MD5SUMLIST="b4edcc69e39159dd7be17828249afb46"
REQUIRES="atk cairo gdk-pixbuf pango x-window-system"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

rm tests/css/parser/selector.css
rm tests/a11y/pickers.ui
make check

make DESTDIR=${FAKEROOT} install

cat > ~/.config/gtk-3.0/settings.ini << "EOF"
[Settings]
gtk-theme-name = Adwaita
gtk-fallback-icon-theme = gnome
EOF

cat > ${FAKEROOT}/etc/gtk-3.0/settings.ini << "EOF"[Settings]
gtk-theme-name = Clearwaita
gtk-fallback-icon-theme = elementary
EOF

#################
} # END OF FILE #
#################

