#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/files/BLFS/svn/sources/jfsutils-1.1.15.tar.gz"
MD5SUMLIST="8809465cd48a202895bc2a12e1923b5d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

configure
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

