#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://mirrors.isc.org/pub/kde/stable/4.6.0/src/kdebase-4.6.0.tar.bz2"
MD5SUMLIST="7d2d176c57f2e914acc89c39351ce5aa"
REQUIRES="soprano"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=$KDE4_PREFIX \
      -DKDE_DEFAULT_HOME=.kde4 \
      -DSYSCONF_INSTALL_DIR=/etc/kde4 \
      ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

