#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/trinity/kdeedu-3.5.13.tar.gz"
MD5SUMLIST="37a14a67c4d00babc3015c6a31698cb0"
REQUIRES="kdebase"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cp -v /usr/share/aclocal/libtool.m4       admin/libtool.m4.in
cp -v /usr/share/libtool/config/ltmain.sh admin/ltmain.sh
sed -i -e "s@/usr/include/tqt@$TRINITY_PREFIX/include/tqt@"   \
          admin/acinclude.m4.in
make -f admin/Makefile.common

export LIBRARY_PATH=$TRINITY_PREFIX/lib

./configure --prefix=$TRINITY_PREFIX \
            --enable-closure         \
            --sysconfdir=/etc        \
            --localstatedir=/var     \
            --with-extra-libs=$TRINITY_PREFIX/lib

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

