#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/trinity/kdegraphics-3.5.13.tar.gz"
MD5SUMLIST="a75c254cd1060343cd04c6744bce6798"
REQUIRES="kdebase"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

KDEGRAPHICS=`pwd`
MAKEDIR=/tmp/kdegraphics
rm -rf   $MAKEDIR
mkdir -p $MAKEDIR
cd       $MAKEDIR

cmake -DCMAKE_INSTALL_PREFIX=$TRINITY_PREFIX \
      -DCMAKE_VERBOSE_MAKEFILE=ON            \
      -DQT_VERSION=3                         \
      -DCMAKE_CXX_FLAGS="-fpermissive"       \
      -DWITH_TIFF=ON                         \
      -DWITH_PAM=ON                          \
      -DBUILD_ALL=ON                         \
      -DBUILD_KAMERA=OFF                     \
      -DBUILD_KSVG=OFF                       \
      -DBUILD_KUICKSHOW=OFF                  \
      -DBUILD_LIBKSCAN=OFF                   \
      -DBUILD_KOOKA=OFF                      \
      -DBUILD_KGHOSTVIEW=OFF                 \
      -DBUILD_KFILE_PLUGINS=OFF              \
      $KDEGRAPHICS

unset KDEGRAPHICS MAKEDIR
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

