#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/ao/libao-1.1.0.tar.gz"
MD5SUMLIST="2b2508c29bc97e4dc218fa162cf883c8"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m644 README ${FAKEROOT}/usr/share/doc/libao-1.1.0

#################
} # END OF FILE #
#################

