#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.kernel.org/pub//linux/utils/raid/mdadm/mdadm-3.2.3.tar.xz"
MD5SUMLIST="9203afc5c891a39c5a8998b385cb070b"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make everything

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

