#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/NSS_3_13_1_RTM/src/nss-3.13.1.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/nss-3.13.1-standalone-1.patch"
MD5SUMLIST="c500f96d33ba1390c8a35c667e05e542
            dontverify"
REQUIRES="nspr sqlite"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

# (*) Fixes 'error: "__GNUC_MINOR" is not defined' in network-manager
sed 's/__GNUC__ > 3/defined(__GNUC__) \&\& (__GNUC__ > 3)/g' \
        -i mozilla/security/nss/lib/util/pkcs11n.h
sed 's/__GNUC_MINOR < 5/__GNUC_MINOR__ < 5/g' \
        -i mozilla/security/nss/lib/util/pkcs11n.h

(
[ $(arch) = x86_64 ] && export USE_64=1
export BUILD_OPT=1
cat /usr/include/sqlite3.h &> /dev/null && export NSS_USE_SYSTEM_SQLITE=1
export NSPR_INCLUDE_DIR=/usr/include/nspr
export USE_SYSTEM_ZLIB=1
export ZLIB_LIBS=-lz
patch -Np1 -i ../nss-3.13.1-standalone-1.patch
make -C mozilla/security/nss nss_build_all

export NSS_LINUXDIR=$(basename `ls -d $PWD/mozilla/dist/Linux*`)
cd mozilla/dist
install -v -m755 $NSS_LINUXDIR/lib/*.so ${FAKEROOT}/usr/lib
install -v -m644 $NSS_LINUXDIR/lib/{*.chk,libcrmf.a} ${FAKEROOT}/usr/lib
install -v -m755 -d ${FAKEROOT}/usr/include/nss
install -v -m755 $NSS_LINUXDIR/bin/{certutil,nss-config,pk12util} ${FAKEROOT}/usr/bin
install -v -m644 $NSS_LINUXDIR/lib/pkgconfig/nss.pc ${FAKEROOT}/usr/lib/pkgconfig
cp -v -RL {public,private}/nss/* ${FAKEROOT}/usr/include/nss
chmod 644 ${FAKEROOT}/usr/include/nss/*

)

#################
} # END OF FILE #
#################

