#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.gnupg.org/gcrypt/pinentry/pinentry-0.8.1.tar.gz"
MD5SUMLIST="81f99904daee5331eb6738408bb024b6"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-pinentry-gtk           \
            --disable-pinentry-gtk2          \
            --disable-pinentry-qt
make

makeinfo --html --no-split -o doc/pinentry_nochunks.html doc/pinentry.texi
makeinfo --plaintext       -o doc/pinentry.txt           doc/pinentry.texi

make -k -C doc pdf ps html

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/pinentry-0.8.1/html
install -v -m644    README doc/pinentry{_*.html,.txt,.texi} \
                    ${FAKEROOT}/usr/share/doc/pinentry-0.8.1

install -v -m644 doc/pinentry.html/* \
                 ${FAKEROOT}/usr/share/doc/pinentry-0.8.1/html
install -v -m644 doc/pinentry.{pdf,ps,dvi} \
                 ${FAKEROOT}/usr/share/doc/pinentry-0.8.1

#################
} # END OF FILE #
#################

