#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/kvm/files/qemu-kvm/1.0/qemu-kvm-1.0.tar.gz"
MD5SUMLIST="00a825db46a70ba8ef9fc95da9cc7c1e"
REQUIRES="glib2 python2 sdl x-window-system"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

export LIBRARY_PATH=/opt/xorg/lib

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

ln -sv qemu-system-x86_64 /usr/bin/qemu

cat >> ${FAKEROOT}/etc/sysctl.conf << EOF
net.ipv4.ip_forward=1 
EOF

cat >> ${FAKEROOT}/etc/qemu-ifup << EOF
#!/bin/bash

switch=br0

if [ -n "$1" ]; then
  # Add new tap0 interface to bridge
  ${FAKEROOT}/sbin/ip link set $1 up
  sleep 0.5s
  ${FAKEROOT}/usr/sbin/brctl addif $switch $1
else
  echo "Error: no interface specified"
  exit 1
fi

exit 0 
EOF

cat >> ${FAKEROOT}/etc/qemu-ifdown << EOF
#!/bin/bash

switch=br0

if [ -n "$1" ]; then
  # Remove tap0 interface from bridge
  ${FAKEROOT}/usr/sbin/brctl delif $switch $1
else
  echo "Error: no interface specified"
  exit 1
fi

exit 0 
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

qemu-img create -f qcow2 vdisk.img 10G

qemu

qemu

qemu -hda vdisk.img                        \
     -cdrom Fedora-16-x86_64-Live-LXDE.iso \ 
     -boot d                               \
     -m 384

qemu vdisk.img -m 384

sysctl -w net.ipv4.ip_forward=1

#################
} # END OF FILE #
#################

