#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://download.librdf.org/source/redland-1.0.12.tar.gz"
MD5SUMLIST="40f37a5ad97fdfbf984f78dcea0c6115"
REQUIRES="rasqal"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

