#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/tcl/tcl8.5.10-src.tar.gz
          http://downloads.sourceforge.net/tcl/tcl8.5.10-html.tar.gz"
MD5SUMLIST="a08eaf8467c0631937067c1948dd326b
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xf ../tcl8.5.10-html.tar.gz --strip-components=1

cd unix
./configure --prefix=/usr \
            --enable-threads \
            --mandir=/usr/share/man
make

sed -i \
    -e "s@^\(TCL_SRC_DIR='\).*@\1/usr/include'@" \
    -e "/TCL_B/s@='\(-L\)\?.*unix@='\1/usr/lib@" \
    tclConfig.sh

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-private-headers
ln -v -sf tclsh8.5 ${FAKEROOT}/usr/bin/tclsh
chmod -v 755 ${FAKEROOT}/usr/lib/libtcl8.5.so

install -v -m755 -d           ${FAKEROOT}/usr/share/doc/tcl-8.5.10
cp      -v -R       ../html/* ${FAKEROOT}/usr/share/doc/tcl-8.5.10

#################
} # END OF FILE #
#################

