#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/tripwire/tripwire-2.4.2.2-src.tar.bz2"
MD5SUMLIST="2462ea16fb0b5ae810471011ad2f2dd6"
REQUIRES="openssl"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -e 's@TWDB="${prefix}@TWDB="/var@' install/install.cfg
./configure --prefix=/usr --sysconfdir=/etc/tripwire
make

make DESTDIR=${FAKEROOT} install
cp -v policy/*.txt ${FAKEROOT}/usr/doc/tripwire

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

twadmin --create-polfile --site-keyfile /etc/tripwire/site.key \
    /etc/tripwire/twpol.txt
tripwire --init

tripwire --check > /etc/tripwire/report.txt

uname -n

tripwire --update --twrfile /var/lib/tripwire/report/<report-name.twr>

twadmin --create-polfile /etc/tripwire/twpol.txt
tripwire --init

#################
} # END OF FILE #
#################

