#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://hal.freedesktop.org/releases/udisks-1.0.1.tar.gz"
MD5SUMLIST="3654d994eb43b80c8c2d04fe03da30c4"
REQUIRES="dbus-glib libatasmart lvm2 parted polkit sg3_utils udev-rebuild"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/udisks \
            --localstatedir=/var
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

