#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/hci/sane/xsane/xsane-0.994.tar.gz"
MD5SUMLIST="7d02656026797a46a84bda63006f5668"
REQUIRES="gtk+2 sane"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} xsanedocdir=/usr/share/doc/xsane-0.994 install
ln -v -s ../../doc/xsane-0.994 \
         ${FAKEROOT}/usr/share/sane/xsane/doc

ln -v -s ${FAKEROOT}/usr/bin/xsane ${FAKEROOT}/usr/lib/gimp/2.0/plug-ins/

#################
} # END OF FILE #
#################

