#!/bin/bash

# Last update: BLFS r9313 (2012-02-08)

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/pygobject/2.28/pygobject-2.28.6.tar.xz"
MD5SUMLIST="9415cb7f2b3a847f2310ccea258b101e"
REQUIRES="glib2 pkgconfig"

# The 'pkgconfig' dependency fixes the following error in ./configure:
#   *** A new enough version of pkg-config was not found.
#   *** See http://www.freedesktop.org/software/pkgconfig/
# The 'python-py2cairo' dependency seems not to be required.

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-introspection
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

