#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="$(./sources.sh bash)
         $(./sources.sh bash_patch1)"
MD5SUMLIST="$(./sources.sh -m bash)
            $(./sources.sh -m bash_patch1)"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../bash-4.3-upstream_fixes-3.patch

./configure --prefix=/usr                    \
            --bindir=/bin                    \
            --docdir=/usr/share/doc/bash-4.3 \
            --without-bash-malloc            \
            --with-installed-readline

make

make DESTDIR=${FAKEROOT} install

# (*) This will add the '/bin/sh' symlink to the package archive.
ln -s bash ${FAKEROOT}/bin/sh

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools --without-bash-malloc

make

make install

ln -sv bash /tools/bin/sh

#################
} # END OF FILE #
#################

