#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="$(./sources.sh eudev)
	  $(./sources.sh udev_manpages)
          $(./sources.sh udev)"

MD5SUMLIST="$(./sources.sh -m eudev)
	  $(./sources.sh -m udev_manpages)
          $(./sources.sh -m udev)"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed    -i '/struct ucred/i struct ucred;' src/libudev/util.h
sed -r -i 's|/usr(/bin/test)|\1|'         test/udev-test.pl

BLKID_CFLAGS=-I/tools/include       \
BLKID_LIBS='-L/tools/lib -lblkid'   \
./configure --prefix=/usr           \
            --bindir=/sbin          \
            --sbindir=/sbin         \
            --libdir=/usr/lib       \
            --sysconfdir=/etc       \
            --libexecdir=/lib       \
            --with-rootprefix=      \
            --with-rootlibdir=/lib  \
            --enable-split-usr      \
            --enable-libkmod        \
            --enable-rule_generator \
            --enable-keymap         \
            --disable-introspection \
            --disable-gudev         \
            --disable-gtk-doc-html  \
            --with-firmware-path=/lib/firmware 

make

make DESTDIR=${FAKEROOT} install

tar -xvf ../eudev-1.9-manpages.tar.bz2 -C ${FAKEROOT}/usr/share

tar -xvf ../udev-lfs-20140408.tar.bz2
make DESTDIR=${FAKEROOT} -f udev-lfs-20140408/Makefile.lfs install

#################
} # END OF FILE #
#################

