#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="$(./sources.sh findutils)"
MD5SUMLIST="$(./sources.sh -m findutils)"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --localstatedir=/var/lib/locate

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/find ${FAKEROOT}/bin
sed -i 's|find:=${BINDIR}|find:=/bin|' ${FAKEROOT}/usr/bin/updatedb

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

