#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="$(./sources.sh kmod)"
MD5SUMLIST="$(./sources.sh -m kmod)"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr          \
            --bindir=/bin          \
            --sysconfdir=/etc      \
            --with-rootlibdir=/lib \
            --with-xz              \
            --with-zlib

make

make DESTDIR=${FAKEROOT} install

for target in depmod insmod modinfo modprobe rmmod; do
  ln -sv ../bin/kmod ${FAKEROOT}/sbin/$target
done

ln -sv kmod ${FAKEROOT}/bin/lsmod

#################
} # END OF FILE #
#################

