#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="$(./sources.sh libcap)"
MD5SUMLIST="$(./sources.sh -m libcap)"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} RAISE_SETFCAP=no prefix=/usr install
chmod -v 755 ${FAKEROOT}/usr/lib/libcap.so

mv -v ${FAKEROOT}/usr/lib/libcap.so.* ${FAKEROOT}/lib
ln -sfv ../../lib/$(readlink ${FAKEROOT}/usr/lib/libcap.so) ${FAKEROOT}/usr/lib/libcap.so

#################
} # END OF FILE #
#################

