#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="$(./sources.sh sysklogd)"
MD5SUMLIST="$(./sources.sh -m sysklogd)"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/Error loading kernel symbols/{n;n;d}' ksym_mod.c

make

make prefix=${FAKEROOT} BINDIR=${FAKEROOT}/sbin install

cat > ${FAKEROOT}/etc/syslog.conf << "EOF"
# Begin /etc/syslog.conf

auth,authpriv.* -/var/log/auth.log
*.*;auth,authpriv.none -/var/log/sys.log
daemon.* -/var/log/daemon.log
kern.* -/var/log/kern.log
mail.* -/var/log/mail.log
user.* -/var/log/user.log
*.emerg *

# End /etc/syslog.conf
EOF

#################
} # END OF FILE #
#################

