#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140821 / r10727) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="$(./sources.sh sysvinit)
          $(./sources.sh sysvinit_patch1)"
MD5SUMLIST="$(./sources.sh -m sysvinit)
          $(./sources.sh -m sysvinit_patch1)"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../sysvinit-2.88dsf-consolidated-1.patch

make -C src

make ROOT=${FAKEROOT} -C src install

#################
} # END OF FILE #
#################

