#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-08-22 / r13994) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="$(./sources.sh wget)"
MD5SUMLIST="$(./sources.sh -m wget)"
REQUIRES="openssl"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr      \
            --sysconfdir=/etc  \
            --with-ssl=openssl
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo ca-directory=/etc/ssl/certs >> /etc/wgetrc

#################
} # END OF FILE #
#################

