#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/utils/schilling/cdrtools/cdrtools-2.01.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/cdrtools-2.01-ascii-2.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/cdrtools-2.01-glibc_conflicts-3.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/cdrtools-2.01-mkisofs_iconv-1.patch"
MD5SUMLIST="d44a81460e97ae02931c31188fe8d3fd
            dontverify
            dontverify
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../cdrtools-2.01-mkisofs_iconv-1.patch

patch -Np1 -i ../cdrtools-2.01-ascii-2.patch

patch -Np1 -i ../cdrtools-2.01-glibc_conflicts-3.patch

make INS_BASE=/usr DEFINSUSR=root DEFINSGRP=root

make INS_BASE=${FAKEROOT}/usr DEFINSUSR=root DEFINSGRP=root install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/cdrtools-2.01
install -v -m644 README* ABOUT doc/*.ps \
    ${FAKEROOT}/usr/share/doc/cdrtools-2.01

#################
} # END OF FILE #
#################

