#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.cmake.org/files/v2.8/cmake-2.8.6.tar.gz"
MD5SUMLIST="2147da452fd9212bb9b4542a9eee9d5b"
REQUIRES="curl expat libarchive"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./bootstrap --prefix=/usr       \
            --system-libs       \
            --mandir=/share/man \
            --docdir=/share/doc/cmake-2.8.6
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

