#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://curl.haxx.se/download/curl-7.22.0.tar.bz2"
MD5SUMLIST="bdb5c226d37c4a6082c70e7ef6f63060"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
find docs -name "Makefile*" -o -name "*.1" -o -name "*.3" | xargs rm
install -v -d -m755 ${FAKEROOT}/usr/share/doc/curl-7.22.0
cp -v -R docs/*     ${FAKEROOT}/usr/share/doc/curl-7.22.0

#################
} # END OF FILE #
#################

