#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-0.18.tar.bz2"
MD5SUMLIST="d966b743eb394650f98d5dd56b9aece1"
REQUIRES="glib2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

update-desktop-database /usr/share/applications

#################
} # END OF FILE #
#################

