#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://roy.marples.name/downloads/dhcpcd/dhcpcd-5.2.12.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="832e3cd6bfcaff64e9476e0ff7849e8f
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --libexecdir=/lib/dhcpcd \
            --dbdir=/run             \
            --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

sed -i "s;/var/lib;/run;g" dhcpcd-hooks/50-dhcpcd-compat
install -v -m 644 dhcpcd-hooks/50-dhcpcd-compat ${FAKEROOT}/lib/dhcpcd/dhcpcd-hooks/

includeBootscript service-dhcpcd

#################
} # END OF FILE #
#################

