#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/freetype/freetype-2.4.8.tar.bz2
          http://downloads.sourceforge.net/freetype/freetype-doc-2.4.8.tar.bz2"
MD5SUMLIST="dbf2caca1d3afd410a29217a9809d397
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xf ../freetype-doc-2.4.8.tar.bz2 \
    --strip-components=2 -C docs

sed -i -r 's:.*(#.*SUBPIXEL.*) .*:\1:' \
          include/freetype/config/ftoption.h
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/freetype-2.4.8
cp -v -R docs/*     ${FAKEROOT}/usr/share/doc/freetype-2.4.8

#################
} # END OF FILE #
#################

