#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.gnutls.org/pub/gnutls/gnutls-3.0.7.tar.xz"
MD5SUMLIST="840c96c75817c0f800a47805e275db7e"
REQUIRES="libtasn1 nettle"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/gnutls-3.0.7
install -v -m644    doc/*.{html,png,eps,pdf,ps} doc/cyclo/*.html \
                    ${FAKEROOT}/usr/share/doc/gnutls-3.0.7
cp -v -R            doc/credentials \
                    ${FAKEROOT}/usr/share/doc/gnutls-3.0.7

make DESTDIR=${FAKEROOT} -C doc/reference install-data-local

#################
} # END OF FILE #
#################

