#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gtk+/2.24/gtk+-2.24.8.tar.xz"
MD5SUMLIST="5408d4a70ac132f7c439d7de40e83aff"
REQUIRES="atk cairo gdk-pixbuf pango x-window-system"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -e '/db2html/i@HAVE_DOCBOOK_TRUE@\t   mkdir gtk-tut; '          \
       -e '/gtk-tut html/i@HAVE_DOCBOOK_TRUE@\t   mv *.html gtk-tut; ' \
    docs/tutorial/Makefile.in

sed -i -e '/db2html/i@HAVE_DOCBOOK_TRUE@\t   mkdir gtk-faq; '          \
       -e '/gtk-faq html/i@HAVE_DOCBOOK_TRUE@\t   mv *.html gtk-faq;'  \
    docs/faq/Makefile.in

sed -i -e 's#^\(      gtk_icon_view_\)l#\1queue_l#' gtk/gtkiconview.c

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install
sed -i 's/#man_MANS/man_MANS/' docs/reference/gtk/Makefile
make DESTDIR=${FAKEROOT} -C docs/reference/gtk install-man
        
install -v -m755 -d         ${FAKEROOT}/usr/share/doc/gtk+-2.24.8
cp -v -R docs/faq/html      ${FAKEROOT}/usr/share/doc/gtk+-2.24.8/faq
cp -v -R docs/tutorial/html ${FAKEROOT}/usr/share/doc/gtk+-2.24.8/tutorial
install -v -m644 docs/*.txt ${FAKEROOT}/usr/share/doc/gtk+-2.24.8

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-query-immodules-2.0 > /etc/gtk-2.0/gtk.immodules

#################
} # END OF FILE #
#################

