#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gvfs/1.10/gvfs-1.10.1.tar.xz"
MD5SUMLIST="0c968704be003d2f6eab29388c41664e"
REQUIRES="dbus glib2 intltool pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/gvfs
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

