#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://launchpad.net/intltool/trunk/0.50.0/+download/intltool-0.50.0.tar.gz"
MD5SUMLIST="0da9847a60391ca653df35123b1f7cc0"
REQUIRES="perl-xml-parser"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D doc/I18N-HOWTO \
    ${FAKEROOT}/usr/share/doc/intltool-0.50.0/I18N-HOWTO

#################
} # END OF FILE #
#################

