#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.netfilter.org/projects/iptables/files/iptables-1.4.12.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="d3f145c2c91daecbb4251bc79390b46c
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/if_packet/i#define __aligned_u64 __u64 __attribute__((aligned(8)))' \
   extensions/libxt_pkttype.c
./configure --prefix=/usr     \
            --bindir=/sbin    \
            --sbindir=/sbin   \
            --libdir=/lib     \
            --libexecdir=/lib \
            --with-pkgconfigdir=/usr/lib/pkgconfig
make

make DESTDIR=${FAKEROOT} install
ln -sfv xtables-multi ${FAKEROOT}/sbin/iptables-xml

includeBootscript iptables

#################
} # END OF FILE #
#################

