#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://dri.freedesktop.org/libdrm/libdrm-2.4.27.tar.bz2"
MD5SUMLIST="0fba4f42735cd3d24dd7a8cde0023fbd"
REQUIRES="libatomic_ops libpthread-stubs x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$XORG_PREFIX --enable-nouveau-experimental-api
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

