#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://libproxy.googlecode.com/files/libproxy-0.4.7.tar.gz"
MD5SUMLIST="509e03a488a61cd62bfbaf3ab6a2a7a5"
REQUIRES="cmake"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cmake -DCMAKE_INSTALL_PREFIX=/usr .
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

