#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.2.tar.bz2"
MD5SUMLIST="798a4211221073c1409f26eac4567e8b"
REQUIRES="libogg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m644 doc/Vorbis* ${FAKEROOT}/usr/share/doc/libvorbis-1.3.2

#################
} # END OF FILE #
#################

