#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://xcb.freedesktop.org/dist/libxcb-1.7.tar.bz2"
MD5SUMLIST="925699df361b99491165ebc12068056b"
REQUIRES="libXau libXdmcp libpthread-stubs libxslt xcb-proto"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG --docdir='${datadir}'/doc/libxcb-1.7
make

make DESTDIR=${FAKEROOT} install

cat > ${FAKEROOT}/etc/profile.d/libxcb.sh << "EOF"
export LIBXCB_ALLOW_SLOPPY_LOCK=1
EOF

#################
} # END OF FILE #
#################

