#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libxklavier/5.1/libxklavier-5.1.tar.bz2"
MD5SUMLIST="cbc2a760827c20aef61eb7b18a6ce598"
REQUIRES="glib2 iso-codes libxml2 x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/^GLIB_GENMARSHAL/s/$PKG_CONFIG/\@PKG_CONFIG\@/' \
    libxklavier/Makefile.in

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

