#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://xmlsoft.org/sources/libxml2-2.7.8.tar.gz
          http://www.w3.org/XML/Test/xmlts20080827.tar.gz"
MD5SUMLIST="8127a65e8c3b08856093099b52599c86
            dontverify"
REQUIRES="python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar xf ../xmlts20080827.tar.gz

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

