#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://llvm.org/releases/3.0/llvm-3.0.tar.gz"
MD5SUMLIST="a8e5f5f1c1adebae7b4a654c376a6005"
REQUIRES="postlfs"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

touch tools/edis/EnhancedDisassembly.exports
./configure --prefix=/opt/llvm
find -name Makefile -exec                                  \
        sed -i -r -e '/^LIBRARYNAME/a SHARED_LIBRARY = 1'  \
                  -e 's#BUILD_ARCHIVE :*= 1#NO_&#'         \
                  -e '/^USEDLIBS/s# ([A-Za-z]*).a# -l\1#g' \
                  -e 's#^USEDLIBS#LDFLAGS#' {} \;
sed -i 's#BUILD_ARCHIVE = 1#NO_&#' Makefile.rules
sed -i 's#x)/docs#x)/share/doc#' Makefile.config
make

# (*) Utilize the ld.so.conf directory
mkdir -pv ${FAKEROOT}/etc/ld.so.conf.d

make DESTDIR=${FAKEROOT} install
echo "/opt/llvm/lib" >> ${FAKEROOT}/etc/ld.so.conf.d/llvm.conf
ldconfig
echo "pathappend /usr/share/man MANPATH"      >> ${FAKEROOT}/etc/profile.d/llvm.sh
echo "pathappend /opt/llvm/share/man MANPATH" >> ${FAKEROOT}/etc/profile.d/llvm.sh
echo "pathappend /opt/llvm/bin"               >> ${FAKEROOT}/etc/profile.d/llvm.sh
ln -svf /opt/llvm/share/doc ${FAKEROOT}/usr/share/doc/llvm-3.0

#################
} # END OF FILE #
#################

