#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/NetworkManager/0.9/NetworkManager-0.9.2.0.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/NetworkManager-0.9.2.0-lfs-1.patch"
MD5SUMLIST="d7dce01e97758253bc4ed81d7b86045f
            dontverify"
REQUIRES="dbus-glib dhcpcd glib2 gnutls gtk-doc iptables libgcrypt libnl polkit udev-rebuild wireless-tools"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../NetworkManager-0.9.2.0-lfs-1.patch
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/NetworkManager \
            --localstatedir=/var \
            --with-systemdsystemunitdir=no \
            --with-crypto=gnutls \
            --disable-wimax \
            --disable-ppp --with-tests
make

make DESTDIR=${FAKEROOT} install

# (*) Create configuration file
cat > ${FAKEROOT}/etc/NetworkManager/NetworkManager.conf << "EOF"
[main]
plugins=keyfile

[keyfile]
hostname=localhost # Is set properly on boot #
EOF

# (*) Install a script which launches NetworkManager on boot
cat > ${FAKEROOT}/etc/rc.d/init.d/network-manager << "EOF"
#!/bin/sh
# Written by Marcel van den Boer

. /lib/lsb/init-functions
[ -r /etc/sysconfig/network ] && . /etc/sysconfig/network

case "$1" in
    start)
        log_info_msg "Starting the Network Manager..."

        # Update the persistent hostname for NM. Without this, NM can reset the
        # hostname during an X11 session, which will cause mayhem... 
        sed "s@^hostname=.*\$@hostname=${HOSTNAME}@g" \
                -i /etc/NetworkManager/NetworkManager.conf

        start_daemon /usr/sbin/NetworkManager
        evaluate_retval
        ;;

    stop)
        log_info_msg "Stopping the Network Manager..."
        killproc /usr/sbin/NetworkManager
        evaluate_retval
        ;;

    restart)
        ${0} stop
        sleep 1
        ${0} start
        ;;

    *)
        echo "Usage: ${0} {start|stop|restart}"
        exit 1
        ;;
esac
EOF
chmod 755 ${FAKEROOT}/etc/rc.d/init.d/network-manager

pushd ${FAKEROOT}/etc/rc.d

for n in 0 1 2 6; do
    ln -svf ../init.d/network-manager rc${n}.d/K79network-manager
done
for n in 3 4 5; do
    ln -svf ../init.d/network-manager rc${n}.d/S21network-manager
done

popd

#################
} # END OF FILE #
#################

