#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/pango/1.29/pango-1.29.4.tar.xz"
MD5SUMLIST="9d5aba73897d2e8e8115b3f4fddbc0af"
REQUIRES="cairo fontconfig glib2 gobject-introspection x-window-system"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) Required for proper text rendering in (for example) Gnome
pango-querymodules > /etc/pango/pango.modules

#################
} # END OF FILE #
#################

