#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://hal.freedesktop.org/releases/polkit-0.102.tar.gz"
MD5SUMLIST="a3726bdb9728c103e58f62131e26693a"
REQUIRES="expat intltool pkgconfig"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/polkit-1 \
            --localstatedir=/var \
            --with-authfw=shadow
make

make DESTDIR=${FAKEROOT} install

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -fg 27 polkituser
useradd -c "Policy Kit Daemon User" -d /dev/null -u 27 \
    -g polkituser -s /bin/false polkituser || [ $? == 9 ]

#################
} # END OF FILE #
#################

