#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://freedesktop.org/~hadess/shared-mime-info-0.91.tar.xz"
MD5SUMLIST="982a211560ba4c47dc791ccff34e8fbc"
REQUIRES="glib2 intltool libxml2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) Update the MIME database
update-mime-database /usr/share/mime

#################
} # END OF FILE #
#################

