#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://sqlite.org/sqlite-autoconf-3071000.tar.gz
          http://sqlite.org/sqlite-doc-3071000.zip"
MD5SUMLIST="9ed2ca93577b58cfa0d01f64b9312ab9
            dontverify"
REQUIRES="unzip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

unzip -q ../sqlite-doc-3071000.zip

./configure --prefix=/usr --disable-static \
  CFLAGS="-g -O2 -DSQLITE_SECURE_DELETE=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1"
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/sqlite-3.7.10
cp -v -R sqlite-doc-3071000/* ${FAKEROOT}/usr/share/doc/sqlite-3.7.10

#################
} # END OF FILE #
#################

