#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/wget/wget-1.13.4.tar.xz"
MD5SUMLIST="7f518b3a71e9efd330e9a0c3714f8463"
REQUIRES="openssl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --with-ssl=openssl
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

