#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/wireless_tools.28.tar.gz"
MD5SUMLIST="599c94497f9c9073c7b052d3dcb7cd16"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make PREFIX=${FAKEROOT}/usr install

#################
} # END OF FILE #
#################

