#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/driver/xf86-input-acecad-1.5.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-input-aiptek-1.4.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-input-evdev-2.6.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-input-joystick-1.6.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-input-void-1.4.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-apm-1.2.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-ark-0.7.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-ast-0.93.9.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-ati-6.14.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-cirrus-1.3.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-dummy-0.3.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-fbdev-0.4.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-glint-1.2.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-i128-1.3.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-i740-1.3.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-intel-2.17.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-mach64-6.9.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-mga-1.4.13.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-neomagic-1.2.5.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-nv-2.1.18.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-r128-6.8.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-rendition-4.2.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-s3-0.6.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-s3virge-1.10.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-savage-2.3.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-siliconmotion-1.7.5.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-sis-0.10.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-sisusb-0.9.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-tdfx-1.4.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-tga-1.2.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-trident-1.3.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-tseng-1.2.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-v4l-0.2.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-vesa-2.3.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-voodoo-1.2.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/driver/xf86-video-xgi-1.6.0.tar.bz2"
MD5SUMLIST="a03721cae66c475e5f6513fa51142869
            8231f6ce1c477eac653c9deb527fa3cb
            f33fe9413bde68936d8909206a13e8a1
            19b55812b018a63e597d579d4cec9cdb
            93821f21e807260b05431c62437a8b32
            a3743a971b3acb7de3d2eefc8b1a4834
            ff0cb9cb0a7f36cc6f556deed7327798
            e25c6a55e9d07cc6054d6affc1231296
            19126c8421a05d9605883dcf7498d876
            8195d03ed0be0975c03441e66a9f53b3
            1cf99415c998994f2e88575f942b364c
            53a533d9e0c2da50962282526bace074
            a8458d1b6331c142c8377298c6fecddd
            103316abb2dc466219c027afc5a71691
            4ac1318788f62159965f15131c869e7a
            6d7b1f199dba5820f250888b136186ff
            ae62936e11af4fc0fac9f2db601a844f
            f967fb3e655f6f68aa3f495eaadcaac2
            423b82b776444f88adbf207fb6a82c1a
            b12f0b2114849d1a542d8084732573d3
            2b90854a62a4d45d652062f582dc8d13
            75cc28125077acb7344955294545553b
            5eb06d88533fb327d067928faeb20860
            6517bbbf808c700502d51acdc44662f8
            4dfb647b1ebeaa42a235362643f5b085
            9ca392e16028a2f7c3ebc57f0aa4c1aa
            dd930928b5ed7fcf34e3be4d43202ec7
            1d7a1d4d09aa953bf09acb8467b16a59
            8161bbf2b100c21b609163f0010766b3
            bcbceda78395de74544c83b46a7700cd
            7a646ba7033dd4eb10d38dca8682b391
            fa441774f8bf516a5c6331d64231a39d
            2251ae2a0a905764941cd7b098e85ad1
            07fa32958aff9b463dd3af5481ef6626
            ce8b848e00883ecb88b21ca03891b780
            b4ac771ae81b52fca9b6fa68006a258a"
REQUIRES="libdrm x7server"
TAGS="multi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

case $(basename "$PWD") in
  xf86-input-evdev-[0-9]* | xf86-video-ati-[0-9]* | \
  xf86-video-fbdev-[0-9]* | xf86-video-glint-[0-9]* | \
  xf86-video-newport-[0-9]* )
    sed -i -e "s/\xc3\xb8/\\\\[\/o]/" \
           -e "s/\xc3\xa4/\\\\[:a]/" \
           -e "s/\xc3\x9c/\\\\[:U]/" man/*.man
    ;;
esac

case $(basename "$PWD") in
  xf86-video-s3-[0-9]* | xf86-video-xgi-[0-9]* )
    for file in `grep -Rl "xf86Version.h" *`
    do
      sed 's@xf86Version.h@xorgVersion.h@g' -i "$file"
    done
    ;;
esac

./configure $XORG_CONFIG \
    --with-xorg-module-dir=$XORG_PREFIX/lib/X11/modules
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

