#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/lib/xtrans-1.2.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libX11-1.4.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXext-1.3.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libFS-1.0.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.7.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libSM-1.2.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXScrnSaver-1.2.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXt-1.1.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXmu-1.1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXp-1.0.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXpm-3.5.9.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXaw-1.0.9.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXfixes-5.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXcomposite-0.4.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXcursor-1.1.12.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXdamage-1.1.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libfontenc-1.1.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXfont-1.4.4.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXft-2.2.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXi-1.4.3.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXinerama-1.1.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.3.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXres-1.0.5.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXtst-1.2.0.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXv-1.0.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXvMC-1.0.6.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXxf86dga-1.1.2.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libXxf86vm-1.1.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libdmx-1.1.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libpciaccess-0.12.1.tar.bz2
          http://xorg.freedesktop.org/releases/individual/lib/libxkbfile-1.0.7.tar.bz2"
MD5SUMLIST="c66f9ffd2da4fb012220c6c40ebc7609
            ed7c382cbf8c13425b6a66bcac0ca5d9
            161d200b690ace818db1cc7537e70ba9
            8e68a3a6f3cac936042b240b20d1fb7d
            bb72a732b15e9dc25c3036559387eed5
            e78c447bf1790552b644eca81b542742
            898794bf6812fc9be9bf1bb7aa4d2b08
            eb22c0a1f172b06b97a3f5ae89768412
            6836883a0120e8346cf7f58dc42e465a
            7ae1d63748e79086bd51a633da1ff1a9
            2de3a1b9541f4b3a6f9d84b69d25530e
            ccc57478c41b7a75b9702241b889b1d4
            678071bd7f9f7467e2fc712d81022318
            a60e0b5c276d0aa9e2d3b982c98f61c8
            3b3b7d076c2384b6c600c0b5f4ba971f
            a93b5a6f5b05976d2c0d3f8a07f6ac6a
            44774e1a065158b52f1a0da5100cebec
            11d3c292f05a90f6f67840a9e9c3d9b8
            f9942bc818d39094d7295b156a729393
            cce3c327258116493b753f157e0360c7
            792e8a7ddc7175911d69f823d38eaff6
            ecd4839ad01f6f637c6fb5327207f89b
            92473da2fccf5fac665be4fa4f2037fa
            d08f0b6df3f96c051637d37009f4e55a
            7c592c72da6676f8b0aeec9133b81686
            e292445a64b63e918bbc8b6aae6391dd
            bfc7524646f890dfc30dea1d676004a3
            bbd5fdf63d4c107c8cb710d4df2012b4
            34dc3df888c164378da89a7deeb245a0
            75fd328fab3bd4a55cccaa6d5dfff749
            d6363ee9f4df79f6fc47cba7c67b0d35
            59b4fe0bdf8d9b05e45b59e8fe9e7516"
REQUIRES="fontconfig libXdmcp libxcb x7proto"
TAGS="multi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

case $(basename "$PWD") in
libXfont-[0-9]* )
                 ./configure $XORG_CONFIG --disable-devel-docs
                 ;;
   libXt-[0-9]* )
                 ./configure $XORG_CONFIG \
                     --with-appdefaultdir=/etc/X11/app-defaults
                 ;;
              * )
                 ./configure $XORG_CONFIG
                 ;;
esac
make

make DESTDIR=${FAKEROOT} install
ldconfig

if [ "${XORG_PREFIX}" != "/usr" ]; then
    ln -sv $XORG_PREFIX/lib/X11 ${FAKEROOT}/usr/lib/X11
    ln -sv $XORG_PREFIX/include/X11 ${FAKEROOT}/usr/include/X11
    ln -sv $XORG_PREFIX ${FAKEROOT}/usr/X11R6
fi

#################
} # END OF FILE #
#################

