#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://xlibs.freedesktop.org/xkbdesc/xkeyboard-config-2.0.tar.bz2"
MD5SUMLIST="bb8a98ee61cdc4bd835fdfd2b5cee3e6"
REQUIRES="intltool x7app"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG --with-xkb-rules-symlink=xorg
make

make DESTDIR=${FAKEROOT} install
install -dv -m755 ${FAKEROOT}${XORG_PREFIX}/share/doc/xkeyboard-config-2.0
install -v -m644 docs/{README,HOWTO}* \
    ${FAKEROOT}${XORG_PREFIX}/share/doc/xkeyboard-config-2.0

#################
} # END OF FILE #
#################

