#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/bash/bash-4.2.tar.gz
          http://www.linuxfromscratch.org/patches/lfs/development/bash-4.2-fixes-4.patch"
MD5SUMLIST="3fb927c7c33022f1c327f14a81c0d4b0
            244e3ff74d53792f1db32dea75dc8627"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../bash-4.2-fixes-4.patch

./configure --prefix=/usr --bindir=/bin \
    --htmldir=/usr/share/doc/bash-4.2 --without-bash-malloc \
    --with-installed-readline

make

make DESTDIR=${FAKEROOT} install

# (*) This will add the '/bin/sh' symlink to the package archive.
ln -s bash ${FAKEROOT}/bin/sh

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

patch -Np1 -i ../bash-4.2-fixes-4.patch

./configure --prefix=/tools --without-bash-malloc

make

make install

ln -vs bash /tools/bin/sh

#################
} # END OF FILE #
#################

