#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/bison/bison-2.5.tar.bz2"
MD5SUMLIST="9dba20116b13fc61a0846b0058fbe004"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

echo '#define YYENABLE_NLS 1' >> lib/config.h

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

