#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.2.0.tar.gz"
MD5SUMLIST="dd3a987a0d2b594716baee2f73d61ae3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure CHECK_CFLAGS=-I/tools/include \
    CHECK_LIBS="-L/tools/lib -lcheck" --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

