#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://lfscript.org/sources/btrfs-progs_2012_01_27.tar.bz2"
MD5SUMLIST="1afa2d828ec80cf21aa530ae2a8caf99"
REQUIRES="attr"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} prefix=/usr install

#################
} # END OF FILE #
#################

