#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

REQUIRES="busybox cdrtools squashfs-tools syslinux"
TAGS="group"

