#!/bin/bash

# Last update: BLFS r9302 (2012-02-07)

WGETLIST="http://www.cpan.org/authors/id/C/CH/CHORNY/Tie-IxHash-1.22.tar.gz"
MD5SUMLIST="dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

perl Makefile.PL
make
make test

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

