#!/bin/bash

# Last update: BLFS r9313 (2012-02-08)

WGETLIST="http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2"
MD5SUMLIST="20337132c4ab06c1146ad384d55372c5"
REQUIRES="python2 cairo"

# Book instructions produce an error:
#   configure: error: cannot find install-sh, install.sh, or shtool in "."
#   "./.." "./../.."

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./waf configure --prefix=/usr
./waf build

./waf install --destdir=${FAKEROOT}

#################
} # END OF FILE #
#################

