#!/bin/bash

WGETLIST="http://www.kernel.org/pub/linux/utils/kernel/hotplug/udev-181.tar.xz
          http://www.linuxfromscratch.org/lfs/downloads/development/udev-config-20100128.tar.bz2"
MD5SUMLIST="0d7af750702620a871b9f9b98d8ad859
            dontverify"
REQUIRES="pkgconfig"

# --- Notes ---
# * Last updated for LFS r9737 (2012-02-07).
# * The sole purpose for this rebuild is to install GUDEV.
# * The body of this script should be identical to 'lfs-XXXX/udev', with the
#   exception of the REQUIRES above and '--disable-gudev' removed from
#   ./configure.

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xvf ../udev-config-20100128.tar.bz2

install -dv ${FAKEROOT}/lib/{firmware,udev/devices/pts}
mknod -m0666 ${FAKEROOT}/lib/udev/devices/null c 1 3

BLKID_CFLAGS="-I/usr/include/blkid"  \
BLKID_LIBS="-L/lib -lblkid"          \
KMOD_CFLAGS="-I/usr/include"         \
KMOD_LIBS="-L/lib -lkmod"            \
./configure  --prefix=/usr           \
             --with-rootprefix=''    \
             --bindir=/sbin          \
             --sysconfdir=/etc       \
             --libexecdir=/lib       \
             --enable-rule_generator \
             --disable-introspection \
             --disable-keymap        \
             --with-usb-ids-path=no  \
             --with-pci-ids-path=no  \
             --with-systemdsystemunitdir=no

make

make DESTDIR=${FAKEROOT} install

rmdir -v ${FAKEROOT}/usr/share/doc/udev

cd udev-config-20100128
make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} install-doc

#################
} # END OF FILE #
#################

