#!/bin/bash

# The version in a current edition of BLFS is not compatible with the rest
# of the scripts. Until the incompatibility can be resolved, this script
# provides an older version of the software as it appeared in BLFS.

WGETLIST="http://www.galago-project.org/files/releases/source/libnotify/libnotify-0.4.5.tar.bz2"
MD5SUMLIST="6a8388f93309dbe336bbe5fc0677de6b"
REQUIRES="dbus-glib gtk+2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

