#!/bin/bash

# The version in a current edition of BLFS is not compatible with the rest
# of the scripts. Until the incompatibility can be resolved, this script
# provides an older version of the software as it appeared in BLFS.

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libunique/1.1/libunique-1.1.6.tar.bz2"
MD5SUMLIST="7955769ef31f1bc4f83446dbb3625e6d"
REQUIRES="gtk+2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/DG_DISABLE_DEPRECATED/d' unique/Makefile.in
./configure --prefix=/usr --disable-static
sed -i 's#  -Werror ##' unique/dbus/Makefile
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

