#!/bin/bash

# The version in a current edition of BLFS is not compatible with the rest
# of the scripts. Until the incompatibility can be resolved, this script
# provides an older version of the software as it appeared in BLFS.

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libwnck/3.2/libwnck-2.30.2.tar.bz2"
MD5SUMLIST="f58a82c97cc1dd95d9c56bbef3649a92"
REQUIRES="gtk+2 intltool"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

