#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/libmatecanvas-1.1.0.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="libmate gtk+2 libart_lgpl libglade" # gtk+2 intltool libart_lgpl orbit2 pkgconfig

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
\
        --disable-static \
        --enable-glade
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

