#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/libmate-1.1.3.tar.xz"
MD5SUMLIST="dontverify"
REQUIRES="mate-vfs libcanberra" # esound gnome-vfs libbonobo orbit2 pkgconfig

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
        --localstatedir=/var/lib \
\
        --mandir=${MATE_PREFIX}/share/man \
\
        --libexecdir=${MATE_PREFIX}/lib/libmate \
        --disable-static \
        --disable-esd
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

