#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-settings-daemon-1.1.1.tar.xz"
MD5SUMLIST="dontverify"
REQUIRES="mate-polkit" # gnome-desktop libgnomekbd orbit2 pkgconfig

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

# Update libmatekbd version numbering (FIXME: Still required?)
sed 's@2.29.5@1.1.0@g' -i configure.ac
sed 's@2.31.2@1.1.0@g' -i configure.ac

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
        --libexecdir=${MATE_PREFIX}/lib/mate-settings-daemon \
\
        --localstatedir=/var \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

