#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-file-manager-1.1.2.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="mate-desktop libunique_compat shared-mime-info" # gnome-desktop libunique orbit2 pkgconfig shared-mime-info

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
        --libexecdir=${MATE_PREFIX}/lib/mate-file-manager \
\
        --localstatedir=/var \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/${MATE_PREFIX}/share/doc/mate-file-manager
install -v -m644 docs/*.{txt,dia,pdf,sxw,faq,html} \
        ${FAKEROOT}/${MATE_PREFIX}/share/doc/mate-file-manager

#################
} # END OF FILE #
#################

