#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/a2ps/a2ps-4.14.tar.gz
          ftp://ftp.enst.fr/pub/unix/a2ps/i18n-fonts-0.1.tar.gz"
MD5SUMLIST="781ac3d9b213fa3e1ed0d79f986dc8c7
            dontverify"
REQUIRES="gperf"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

autoconf
sed -i "s/GPERF --version |/& head -n 1 |/" configure
sed -i "s|/usr/local/share|/usr/share|" configure
./configure --prefix=/usr \
    --sysconfdir=/etc/a2ps \
    --enable-shared \
    --with-medium=letter
make

make DESTDIR=${FAKEROOT} install

tar -xf ../i18n-fonts-0.1.tar.gz
cp -v i18n-fonts-0.1/fonts/* ${FAKEROOT}/usr/share/a2ps/fonts
cp -v i18n-fonts-0.1/afm/* ${FAKEROOT}/usr/share/a2ps/afm
cd ${FAKEROOT}/usr/share/a2ps/afm
./make_fonts_map.sh
mv fonts.map.new fonts.map

#################
} # END OF FILE #
#################

