#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/accountsservice/accountsservice-0.6.15.tar.xz"
MD5SUMLIST="47b5af77b544528c02d82761bd574c09"
REQUIRES="dbus-glib polkit"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/accountsservice \
            --localstatedir=/var
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

