#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/opsys/linux/alsa/plugins/alsa-plugins-1.0.24.tar.bz2"
MD5SUMLIST="e4d4c90e11ab9d1a117afbbc1edd2b16"
REQUIRES="alsa-lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/alsa-plugins-1.0.24
install -v -m644 doc/{README*,*.txt} \
                    ${FAKEROOT}/usr/share/doc/alsa-plugins-1.0.24

#################
} # END OF FILE #
#################

