#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://archive.apache.org/dist/ant/source/apache-ant-1.8.1-src.tar.bz2"
MD5SUMLIST="8c31b30f6b9863d1fef4bdf484fc8507"
REQUIRES="icedtea6 jdk"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's;jars,test-jar;jars;' build.xml

sed -i 's|${dist.dir}/etc|/etc/ant|'        build.xml
sed -i 's|/etc/ant.conf|/etc/ant/ant.conf|' src/script/ant
cp -v /usr/share/junit-4.8.1/junit-4.8.1.jar \
      lib/optional/junit.jar

./build.sh -Ddist.dir=/opt/ant-1.8.1 dist
ln -v -sf ${FAKEROOT}/etc/ant ${FAKEROOT}/opt/ant-1.8.1/etc
ln -v -sf ant-1.8.1 ${FAKEROOT}/opt/ant

#################
} # END OF FILE #
#################

