#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/at-spi/1.30/at-spi-1.30.1.tar.bz2"
MD5SUMLIST="29fdf7934e98efda5fe0ab74ab4d3f29"
REQUIRES="gconf gtk+2 libbonobo orbit2 pkgconfig python2 x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib/at-spi
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

