#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://distfiles.audacious-media-player.org/audacious-3.2.tar.bz2"
MD5SUMLIST="e968feb712a229e2be0315a855d1c96d"
REQUIRES="gtk+2 gtk+3 mowgli"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

TPUT=/bin/true ./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D README ${FAKEROOT}/usr/share/doc/audacious-3.2/README

#################
} # END OF FILE #
#################

