#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://avahi.org/download/avahi-0.6.28.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="d0143a5aa3265019072e53ab497818d0
            dontverify"
REQUIRES="glib2 intltool"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --disable-gtk \
            --disable-gtk3 \
            --disable-qt3 \
            --disable-qt4 \
            --disable-mono \
            --disable-monodoc \
            --disable-python \
            --disable-dbus \
            --disable-libdaemon \
            --enable-core-docs \
            --with-distro=lfs
make

make DESTDIR=${FAKEROOT} install

includeBootscript avahi

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -fg 84 avahi
useradd -c "Avahi Daemon Owner" -d /dev/null -u 84 \
    -g avahi -s /bin/false avahi  || [ $? == 9 ]

groupadd -fg 86 netdev

#################
} # END OF FILE #
#################

