#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/avifile/avifile-0.7-0.7.45.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/avifile-0.7-0.7.45-gcc41-1.patch"
MD5SUMLIST="7da94802f120d1b69e04a13170dcd21d
            dontverify"
REQUIRES="qt sdl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

install -v -d -m755 ${FAKEROOT}/usr/lib/avifile-0.7/win32
tar -xvf ../binaries-011002.tgz -C ${FAKEROOT}/usr/lib/avifile-0.7

patch -Np1 -i ../avifile-0.7-0.7.45-gcc41-1.patch
./configure --prefix=/usr \
    --with-win32-path=/usr/lib/avifile-0.7/win32
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

