#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/graphics/gimp/babl/0.1//babl-0.1.6.tar.bz2"
MD5SUMLIST="dc960981a5ec5330fc1c177be9f59068"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/gtk-doc/html/babl/graphics
install -v -m644 docs/*.{css,html} ${FAKEROOT}/usr/share/gtk-doc/html/babl
install -v -m644 docs/graphics/*.{html,png,svg} ${FAKEROOT}/usr/share/gtk-doc/html/babl/graphics

#################
} # END OF FILE #
#################

