#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://balsa.gnome.org/balsa-2.3.22.tar.bz2"
MD5SUMLIST="0f9b8dbdd26a1916dcc92f0767e8b4e4"
REQUIRES="aspell gmime scrollkeeper"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --localstatedir=/var/lib \
            --with-rubrica \
            --with-gtkhtml=no
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

