#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/caribou/0.4/caribou-0.4.1.tar.xz"
MD5SUMLIST="c03cb3e121547222e9c4fe7bf527fee0"
REQUIRES="clutter gtk+3 libgee libxklavier pygobject3 vala"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --libexecdir=$GNOME_PREFIX/lib/caribou \
            --disable-gtk2-module
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

