#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/check/files/check/0.9.8/check-0.9.8.tar.gz"
MD5SUMLIST="5d75e9a6027cde79d2c339ef261e7470"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make check

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

