#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/clucene/clucene-core-0.9.21b.tar.bz2"
MD5SUMLIST="ba1a8f764a2ca19c66ad907dddd88352"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

