#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/cracklib/cracklib-2.8.18.tar.gz
          http://downloads.sourceforge.net/cracklib/cracklib-words-20080507.gz"
MD5SUMLIST="79053ad8bc714a44cd660cb12116211b
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-default-dict=/lib/cracklib/pw_dict
make

make DESTDIR=${FAKEROOT} install
mv -v ${FAKEROOT}/usr/lib/libcrack.so.2* ${FAKEROOT}/lib
ln -v -sf ../../lib/libcrack.so.2.8.1 ${FAKEROOT}/usr/lib/libcrack.so

install -v -m644 -D ../cracklib-words-20080507.gz \
    ${FAKEROOT}/usr/share/dict/cracklib-words.gz
gunzip -v ${FAKEROOT}/usr/share/dict/cracklib-words.gz
ln -v -s cracklib-words ${FAKEROOT}/usr/share/dict/words
echo $(hostname) >>/usr/share/dict/cracklib-extra-words
install -v -m755 -d ${FAKEROOT}/lib/cracklib
create-cracklib-dict ${FAKEROOT}/usr/share/dict/cracklib-words \
                     ${FAKEROOT}/usr/share/dict/cracklib-extra-words

make test

#################
} # END OF FILE #
#################

