#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.easysw.com/pub/cups/1.5.0/cups-1.5.0-source.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="e54ed09ede2340fc3014913333520fe4
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

useradd -c "Print Service User" -d ${FAKEROOT}/dev/null -g lp -s ${FAKEROOT}/bin/false -u 9 lp

sed -i 's#@CUPS_HTMLVIEW@#firefox#' desktop/cups.desktop.in
./configure --localstatedir=/var       \
            --disable-libusb           \
            --with-rcdir=/tmp/cupsinit \
            --with-docdir=/usr/share/doc/cups-1.5.0
make

make DESTDIR=${FAKEROOT} install
rm -rf ${FAKEROOT}/tmp/cupsinit

pushd ${FAKEROOT}/usr/share/man/
find -name cups\*gz -type l -print -delete
find -name \*gz -exec gunzip -v {} \;
popd

ln -v -s cupsaccept.8 ${FAKEROOT}/usr/share/man/man8/reject.8
ln -v -s cupsaccept.8 ${FAKEROOT}/usr/share/man/man8/cupsreject.8
ln -v -s cupsaccept.8 ${FAKEROOT}/usr/share/man/man8/accept.8
ln -v -s cupsenable.8 ${FAKEROOT}/usr/share/man/man8/cupsdisable.8

includeBootscript cups

#################
} # END OF FILE #
#################

