#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/non-gnu/cvs/source/stable/1.11.23/cvs-1.11.23.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/cvs-1.11.23-zlib-1.patch"
MD5SUMLIST="0213ea514e231559d6ff8f80a34117f0
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../cvs-1.11.23-zlib-1.patch

./configure --prefix=/usr
make

make -C doc html txt dvi ps

sed -e 's/rsh};/ssh};/' \
    -e 's/g=rw,o=r$/g=r,o=r/' \
    -i src/sanity.sh

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/cvs-1.11.23
install -v -m644 FAQ README ${FAKEROOT}/usr/share/doc/cvs-1.11.23
install -v -m644 doc/*.pdf ${FAKEROOT}/usr/share/doc/cvs-1.11.23

install -v -m644 doc/*.{ps,dvi,txt} ${FAKEROOT}/usr/share/doc/cvs-1.11.23
install -v -m755 -d ${FAKEROOT}/usr/share/doc/cvs-1.11.23/html/cvs{,client}
install -v -m644 doc/cvs.html/* \
                 ${FAKEROOT}/usr/share/doc/cvs-1.11.23/html/cvs
install -v -m644 doc/cvsclient.html/* \
                 ${FAKEROOT}/usr/share/doc/cvs-1.11.23/html/cvsclient

#################
} # END OF FILE #
#################

