#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.andrew.cmu.edu/pub/cyrus-mail/cyrus-sasl-2.1.23.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="2eb0e48106f0e9cd8001e654f267ecbc
            dontverify"
REQUIRES="openssl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i.bak 's/#elif WITH_DES/#elif defined(WITH_DES)/' \
    plugins/digestmd5.c
sed -i 's#DB_VERSION_MAJOR == 4.*#(&) || DB_VERSION_MAJOR == 5#' \
    {sasldb/db_berkeley.c,utils/dbconverter-2.c}
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-dbpath=/var/lib/sasl/sasldb2 \
            --with-saslauthd=/var/run/saslauthd
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/cyrus-sasl-2.1.23
install -v -m644 doc/{*.{html,txt,fig},ONEWS,TODO} \
    saslauthd/LDAP_SASLAUTHD ${FAKEROOT}/usr/share/doc/cyrus-sasl-2.1.23
install -v -m700 -d ${FAKEROOT}/var/lib/sasl
install -v -m711 -d ${FAKEROOT}/var/run/saslauthd

includeBootscript cyrus-sasl

#################
} # END OF FILE #
#################

