#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gondor.apana.org.au/~herbert/dash/files/dash-0.5.5.1.tar.gz"
MD5SUMLIST="7ac832b440b91f5a52cf8eb68e172616"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --bindir=/bin --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install

ln -svf dash /bin/sh

cat >> ${FAKEROOT}/etc/shells << "EOF"
/bin/dash
EOF

#################
} # END OF FILE #
#################

