#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://fy.chalmers.se/~appro/linux/DVD+RW/tools/dvd+rw-tools-7.1.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/dvd+rw-tools-7.1-headers-1.patch"
MD5SUMLIST="8acb3c885c87f6838704a0025e435871
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../dvd+rw-tools-7.1-headers-1.patch
make all rpl8 btcflash

make DESTDIR=${FAKEROOT} prefix=/usr install

install -v -m644 -D index.html \
    ${FAKEROOT}/usr/share/doc/dvd+rw-tools-7.1/index.html

#################
} # END OF FILE #
#################

