#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/pub/gnu/ed/ed-1.5.tar.gz"
MD5SUMLIST="e66c03d7e4c67b025d5b6093ec678267"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --bindir=/bin
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

