#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/eog/3.2/eog-3.2.2.tar.xz"
MD5SUMLIST="66d2c1d8d250a37e18f3fbf696642214"
REQUIRES="gnome-desktop gnome-icon-theme shared-mime-info"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --localstatedir=/var/lib
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

