#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/esound/0.2/esound-0.2.41.tar.bz2"
MD5SUMLIST="8d9aad3d94d15e0d59ba9dc0ea990c6c"
REQUIRES="audiofile"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install docdir=/usr/share/doc/esound-0.2.41

#################
} # END OF FILE #
#################

