#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/evince/3.2/evince-3.2.1.tar.xz"
MD5SUMLIST="8c01b6741709b8e32b800b71820648ac"
REQUIRES="gnome-doc-utils gnome-icon-theme gtk+3 shared-mime-info which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --libexecdir=$GNOME_PREFIX/lib/evince \
            --without-keyring \
            --disable-nautilus \
            --disable-pdf
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

