#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/evolution-data-server/3.2/evolution-data-server-3.2.2.tar.xz"
MD5SUMLIST="c126e3d2ad64ca0b4fdf2e7e89b01dde"
REQUIRES="db gconf gperf intltool libgdata libgnome-keyring libical nss sqlite"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --libexecdir=$GNOME_PREFIX/lib/evolution-data-server-3.2
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

