#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://prdownloads.sourceforge.net/expect/expect5.45.tar.gz"
MD5SUMLIST="44e1a4f4c877e9ddc5a542dfa7ecc92b"
REQUIRES="tcl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-tcl=/usr/lib \
            --with-tclinclude=/usr/include \
            --enable-shared
make

make DESTDIR=${FAKEROOT} install
ln -svf expect5.45/libexpect5.45.so ${FAKEROOT}/usr/lib

#################
} # END OF FILE #
#################

