#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/faac/faad2-2.7.tar.gz"
MD5SUMLIST="ee1b4d67ea2d76ee52c5621bc6dbf61e"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

./frontend/faad -o sample.wav ../sample.aac

aplay sample.wav

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

