#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://farsight.freedesktop.org/releases/farsight2/farsight2-0.0.26.tar.gz"
MD5SUMLIST="7756d910687dd2abd455fd68e83f125c"
REQUIRES="gst-plugins-base libnice python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-python
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

