#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/fluxbox/fluxbox-1.3.2.tar.bz2"
MD5SUMLIST="f95b0bdb9ee41bfac124bd0fc601f248"
REQUIRES="x-window-system"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

cat > ${FAKEROOT}/usr/share/xsessions/fluxbox.desktop << "EOF"
[Desktop Entry]
Encoding=UTF-8
Name=Fluxbox
Comment=This session logs you into Fluxbox
Exec=startfluxbox
Type=Application
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo startfluxbox > ~/.xinitrc

mkdir -v ~/.fluxbox
cp -v /usr/share/fluxbox/init ~/.fluxbox/init
cp -v /usr/share/fluxbox/keys ~/.fluxbox/keys

cd ~/.fluxbox
fluxbox-generate_menu

cp -v /usr/share/fluxbox/menu ~/.fluxbox/menu

cp /usr/share/fluxbox/styles/<theme> ~/.fluxbox/theme
sed -i 's,\(session.styleFile:\).*,\1 ~/.fluxbox/theme,' ~/.fluxbox/init
echo "background.pixmap: </path/to/nice/image.xpm>" >> ~/.fluxbox/theme

#################
} # END OF FILE #
#################

