#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.gnome.org/~veillard/gamin/sources/gamin-0.1.10.tar.gz"
MD5SUMLIST="b4ec549e57da470c04edd5ec2876a028"
REQUIRES="glib2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --libexecdir=/usr/sbin
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/gamin-0.1.10
install -v -m644 doc/*.{html,fig,gif,txt} ${FAKEROOT}/usr/share/doc/gamin-0.1.10

#################
} # END OF FILE #
#################

