#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.1.tar.gz"
MD5SUMLIST="2ff9924c7249ef7f736ecfe6f08f3f9b"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr            \
            --datadir=/usr/share/doc \
            --enable-cplusplus
make

make DESTDIR=${FAKEROOT} install
install -v -m644 doc/gc.man ${FAKEROOT}/usr/share/man/man3/gc_malloc.3
ln -v -s gc_malloc.3 ${FAKEROOT}/usr/share/man/man3/gc.3 

#################
} # END OF FILE #
#################

