#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gcalctool/6.2/gcalctool-6.2.0.tar.xz"
MD5SUMLIST="2ec304f118735f6268d38741394a3b9e"
REQUIRES="gconf gnome-doc-utils gtk+3 which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

