#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/GConf/3.2/GConf-3.2.3.tar.xz"
MD5SUMLIST="de9047c08d3f642c5b1990b0bef44577"
REQUIRES="dbus-glib gtk+2 intltool libxml2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --libexecdir=$GNOME_PREFIX/lib/GConf \
            --disable-orbit
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d $GNOME_SYSCONFDIR/gconf/gconf.xml.system

cat > ${FAKEROOT}/etc/dbus-1/system-local.conf << "EOF"
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- Search for .conf files in $GNOME_SYSCONFDIR/dbus-1/system.d -->
  <includedir>$GNOME_SYSCONFDIR/dbus-1/system.d</includedir>

  <!-- Search for .service files in $GNOME_PREFIX/share/dbus-1/system-services -->
  <!-- <servicedir>$GNOME_PREFIX/share/dbus-1/system-services</servicedir> -->

</busconfig>
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) Install GConf schemas
export GCONF_CONFIG_SOURCE="$(gconftool-2 --get-default-source)"
for schemas in $(ls -1 /etc/gnome/2.30.2/gconf/schemas/*.schemas); do
    gconftool-2 --makefile-install-rule ${schemas} > /dev/null
done

#################
} # END OF FILE #
#################

