#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/gdb/gdb-7.3.1.tar.bz2"
MD5SUMLIST="b89a5fac359c618dda97b88645ceab47"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-werror
make

make DESTDIR=${FAKEROOT} -C gdb install

#################
} # END OF FILE #
#################

