#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gedit/3.2/gedit-2.30.3.tar.bz2"
MD5SUMLIST="7c8ac5fe529285309f7d5750ee52b7bd"
REQUIRES="gconf gnome-doc-utils gtk+2 gtksourceview orbit2 pkgconfig which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib/gedit-2 \
            --localstatedir=/var/lib
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

