#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/giflib/giflib-4.1.6.tar.bz2"
MD5SUMLIST="7125644155ae6ad33dbc9fc15a14735f"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/giflib-4.1.6/html
install -v -m644 doc/*.{png,html} \
    ${FAKEROOT}/usr/share/doc/giflib-4.1.6/html
install -v -m644 doc/*.txt \
    ${FAKEROOT}/usr/share/doc/giflib-4.1.6

#################
} # END OF FILE #
#################

