#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/glib-networking/2.30/glib-networking-2.30.1.tar.xz"
MD5SUMLIST="a93b7344daf6292ea66f7a6ec21f361d"
REQUIRES="glib2 gnutls intltool libgcrypt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --with-ca-certificates=/etc/ssl/ca-bundle.crt
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

