#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-control-center/3.2/gnome-control-center-3.2.2.tar.xz"
MD5SUMLIST="7da05b8b5d78535482e8f849ca0cf274"
REQUIRES="gnome-doc-utils gnome-menus gnome-settings-daemon libgtop libunique metacity pulseaudio shared-mime-info"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

