#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-contacts/3.2/gnome-contacts-3.2.2.tar.xz"
MD5SUMLIST="b7974ffcdd106fe9c42a074c465d0ef0"
REQUIRES="folks glib2 gtk+3 libnotify vala"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX \
            --sysconfdir=$GNOME_SYSCONFDIR \
            --libexecdir=$GNOME_PREFIX/lib/gnome-contacts
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

