#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-vfs/2.24/gnome-vfs-2.24.4.tar.bz2"
MD5SUMLIST="a05fab03eeef10a47dd156b758982f2e"
REQUIRES="dbus-glib gconf gnome-mime-data orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/2.30.2 \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib/gnome-vfs-2.0
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

