#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-screensaver/3.2/gnome-screensaver-2.30.0.tar.bz2"
MD5SUMLIST="a18086bf2191795d87b7ea80b7b66daa"
REQUIRES="gnome-desktop gnome-menus orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

XSAVERDIR=/usr/share/xscreensaver/config

            --with-xscreensaverdir=$XSAVERDIR

sed -i 's|etc/pam\.d"|etc"|' data/Makefile.in
./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib/gnome-screensaver \
            --with-pam-prefix=/etc
make

mkdir xscreensavers
cd xscreensavers

XSAVERLIST="*"

for SAVERLIST in $(ls ${XSAVERDIR}/${XSAVERLIST}.xml); do
    ../data/migrate-xscreensaver-config.sh $SAVERLIST
done

unset XSAVERDIR
unset XSAVERLIST
unset SAVERLIST

cd ..

make DESTDIR=${FAKEROOT} install

GNOMEDOCDIR="$(pkg-config \
    --variable=prefix ORBit-2.0)/share/doc/gnome-screensaver-2.30.0"

install -v -m644 -D doc/gnome-screensaver.html \
                    ${GNOMEDOCDIR}/gnome-screensaver.html
unset GNOMEDOCDIR

install -v -m755 -d $(pkg-config --variable=prefix \
        ORBit-2.0)/share/applications/screensavers/xscreensaver
install -v -m644 xscreensavers/*.desktop \
        $(pkg-config --variable=prefix \
            ORBit-2.0)/share/applications/screensavers/xscreensaver

cat > ${FAKEROOT}/etc/pam.d/gnome-screensaver << "EOF"
# File: /etc/pam.d/gnome-screensaver

auth         required      pam_unix.so
account      required      pam_unix.so
session      required      pam_unix.so
password     required      pam_unix.so

EOF
chmod -v 644 ${FAKEROOT}/etc/pam.d/gnome-screensaver

#################
} # END OF FILE #
#################

