#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-themes/3.2/gnome-themes-2.30.2.tar.bz2"
MD5SUMLIST="a14d46ac59f651e04a333ae1dff23848"
REQUIRES="gtk-engines icon-naming-utils"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-all-themes
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

