#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-power-manager/3.2/gnome-power-manager-2.30.1.tar.bz2"
MD5SUMLIST="b85178b8db77db5d22e185430549a295"
REQUIRES="gnome-panel libgnome-keyring libnotify libunique orbit2 pkgconfig upower"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib/gnome-power-manager
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

