#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-mime-data/2.18/gnome-mime-data-2.18.0.tar.bz2"
MD5SUMLIST="541858188f80090d12a33b5a7c34d42c"
REQUIRES="orbit2 perl-xml-parser pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --mandir=$(pkg-config \
                --variable=prefix ORBit-2.0)/share/man
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D man/gnome-vfs-mime.5 \
    $(pkg-config \
        --variable=prefix ORBit-2.0)/share/man/man5/gnome-vfs-mime.5

#################
} # END OF FILE #
#################

