#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-doc-utils/0.20/gnome-doc-utils-0.20.6.tar.bz2"
MD5SUMLIST="8f6e05071599bc073007830ea0a68391"
REQUIRES="intltool libxml2 libxslt python2 rarian"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$GNOME_PREFIX
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

