#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-menus/3.2/gnome-menus-2.30.2.tar.bz2"
MD5SUMLIST="5ca9935f50c939881689c48f59348426"
REQUIRES="glib2 intltool orbit2 pkgconfig python2"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo "export XDG_CONFIG_DIRS=/etc/gnome/3.2.2/xdg" \
> /etc/profile.d/gnome.sh

echo "export XDG_DATA_DIRS=$GNOME_PREFIX/share:\
/usr/share:/usr/local/share" >> /etc/profile.d/gnome.sh

echo "export PYTHONPATH=\$PYTHONPATH:$(pkg-config \
--variable=prefix ORBit-2.0)/lib/python2.7/site-packages/GMenuSimpleEditor" \
>> /etc/profile.d/gnome.sh

#################
} # END OF FILE #
#################

