#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnumeric/1.10/gnumeric-1.10.17.tar.xz"
MD5SUMLIST="ee824d9656a271957d949b8769341f40"
REQUIRES="goffice libglade rarian"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc/gnome/2.30.2 && \
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

