#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/BLFS/svn/g/gnupg-1.4.11.tar.bz2"
MD5SUMLIST="411744e1ef8ce90b87938c4203f001f1"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --libexecdir=/usr/lib
make

make -C doc pdf html

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/gnupg-1.4.11
mv -v ${FAKEROOT}/usr/share/gnupg/FAQ ${FAKEROOT}/usr/share/doc/gnupg-1.4.11
install -v -m644 \
    doc/{highlights-1.4.txt,OpenPGP,samplekeys.asc,DETAILS,*.texi} \
    ${FAKEROOT}/usr/share/doc/gnupg-1.4.11

cp -v -R doc/gnupg1.{html,pdf} ${FAKEROOT}/usr/share/doc/gnupg-1.4.11

#################
} # END OF FILE #
#################

