#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gok/3.2/gok-2.30.0.tar.bz2"
MD5SUMLIST="853c7825eb62d7c425f5a0efdc07412a"
REQUIRES="at-spi gconf gnome-speech libcanberra libwnck orbit2 pkgconfig rarian"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2 \
            --localstatedir=/var/lib
make

make DESTDIR=${FAKEROOT} install
chmod -v 644 $(pkg-config --variable=prefix \
      ORBit-2.0)/share/gnome/help/gok/C/legal.xml

#################
} # END OF FILE #
#################

