#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.nico.schottelius.org/software/gpm/archives/gpm-1.20.6.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="6b534da16dc1b28ba828dea89e520f6f
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

ln -v -s libgpm.so.2.1.0 ${FAKEROOT}/usr/lib/libgpm.so
install -v -m644 conf/gpm-root.conf ${FAKEROOT}/etc

install -v -m755 -d ${FAKEROOT}/usr/share/doc/gpm-1.20.6
chmod   -v   755    doc/{changes,support}
chmod   -v   644    doc/{changes/*,support/*,FAQ,HACK_GPM,README*}
cp      -v -R       doc/{FAQ,HACK_GPM,README*,changes,support} \
                    ${FAKEROOT}/usr/share/doc/gpm-1.20.6

includeBootscript gpm

cat > ${FAKEROOT}/etc/sysconfig/mouse << "EOF"
# Begin /etc/sysconfig/mouse

MDEVICE="<yourdevice>"
PROTOCOL="<yourprotocol>"
GPMOPTS="<additional options>"

# End /etc/sysconfig/mouse
EOF

#################
} # END OF FILE #
#################

