#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gstreamer/0.10/gstreamer-0.10.35.tar.xz"
MD5SUMLIST="1da0b170d4d17d358b27011647054f0a"
REQUIRES="glib2 libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/\(.*gtkdoc-rebase --relative.* \)\(;.*\)/\1|| true\2/' \
  docs/{gst,libs}/Makefile.in
./configure --prefix=/usr \
            --libexecdir=/usr/lib
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/gstreamer-0.10/design
install -v -m644 docs/design/*.txt \
                    ${FAKEROOT}/usr/share/doc/gstreamer-0.10/design

if [ -d ${FAKEROOT}/usr/share/doc/gstreamer-0.10/faq/html ]; then
    chown -v -R root:root \
        ${FAKEROOT}/usr/share/doc/gstreamer-0.10/*/html
fi

gst-launch -v fakesrc num_buffers=5 ! fakesink

#################
} # END OF FILE #
#################

