#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gtk-vnc/0.4/gtk-vnc-0.4.3.tar.bz2"
MD5SUMLIST="38d3fbacb5d00e630f939e88858206f1"
REQUIRES="gnutls gtk+3 intltool"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-gtk=3.0 \
            --with-sasl=no
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

