#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gtkhtml/3.30/gtkhtml-3.30.2.tar.bz2"
MD5SUMLIST="590c626e507a2ef9c9026699283d4004"
REQUIRES="enchant gconf gnome-icon-theme gtk+2 iso-codes orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --libexecdir=$(pkg-config \
                --variable=prefix ORBit-2.0)/lib/gtkhtml
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

