#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/gimp-print/gutenprint-5.2.5.tar.bz2"
MD5SUMLIST="10a0a9fac081d8116ec5ed47fbc1591c"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's|$(PACKAGE)/doc|doc/$(PACKAGE)-$(VERSION)|' \
       {,doc/,doc/developer/}Makefile.in
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/gutenprint-5.2.5/api/gutenprint{,ui2}
install -v -m644    doc/gutenprint/html/* \
                    ${FAKEROOT}/usr/share/doc/gutenprint-5.2.5/api/gutenprint
install -v -m644    doc/gutenprintui2/html/* \
                    ${FAKEROOT}/usr/share/doc/gutenprint-5.2.5/api/gutenprintui2

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

/etc/rc.d/init.d/cups restart

#################
} # END OF FILE #
#################

