#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://hal.freedesktop.org/releases/hal-0.5.14.tar.bz2
          http://hal.freedesktop.org/releases/hal-info-20091130.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="c627d8fb0f9afff94f3c687b5216bc06
            dontverify
            dontverify"
REQUIRES="dbus-glib"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/hal \
            --localstatedir=/var \
            --docdir=/usr/share/doc/hal-0.5.14 \
            --enable-policy-kit=no
make

make DESTDIR=${FAKEROOT} install

tar -xf ../hal-info-20091130.tar.bz2
cd hal-info-20091130
./configure --prefix=/usr --sysconfdir=/etc

make DESTDIR=${FAKEROOT} install

cat > ${FAKEROOT}/etc/hal/fdi/policy/no-fixed-drives.fdi << "EOF"
<?xml version="1.0" encoding="UTF-8"?> <!-- -*- SGML -*- -->

<!-- Don't allow HAL methods on disks that are not
     removable or hotpluggable -->

<deviceinfo version="0.2">
<device>
  <match key="@block.storage_device:storage.hotpluggable" bool="false">
    <match key="@block.storage_device:storage.removable" bool="false">
      <merge key="volume.ignore" type="bool">true</merge>
    </match>
  </match>
</device>
</deviceinfo>
EOF

cat > ${FAKEROOT}/etc/hal/fdi/policy/user-options.fdi << "EOF"
<?xml version="1.0" encoding="UTF-8"?> <!-- -*- SGML -*- -->

<!--
This file is used to set custom options to the HAL policy settings.
The default policy settings are defined in files contained in the
/usr/share/hal/fdi/policy subdirectories. User defined customizations
should be in files contained in the /etc/hal/fdi/policy directory.
-->

<deviceinfo version="0.2">
  <device>

    <!-- this is to be able to mount media in drives we cannot poll,
         e.g. IDE Zip Drives and PC style floppy drives -->
    <match key="storage.media_check_enabled" bool="false">
      <match key="storage.no_partitions_hint" bool="true">
        <append key="volume.mount.valid_options" type="strlist">usefree</append>
        <!-- Insert other options here -->
      </match>
    </match>

    <match key="volume.fsusage" string="filesystem">

      <!-- allow these mount options for vfat -->
      <match key="volume.fstype" string="vfat">
        <append key="volume.mount.valid_options" type="strlist">usefree</append>
        <!-- Insert other options here -->
      </match>
    </match>

  </device>
</deviceinfo>
EOF

includeBootscript haldaemon

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -fg 19 haldaemon
useradd -c "HAL Daemon User" -d /dev/null -u 19 \
        -g haldaemon -s /bin/false haldaemon || [ $? == 9 ]

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

groupadd -fg 61 halusers
cat > /etc/dbus-1/system.d/halusers.conf << "EOF"
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

 <!-- Allow users in the halusers group invoke HAL methods -->
 <policy group="halusers">
  <allow send_interface="org.freedesktop.Hal.Device.SystemPowerManagement"/>
  <allow send_interface="org.freedesktop.Hal.Device.LaptopPanel"/>
  <allow send_interface="org.freedesktop.Hal.Device.Volume"/>
  <allow send_interface="org.freedesktop.Hal.Device.Volume.Crypto"/>
 </policy>

</busconfig>
EOF

#usermod -a -G halusers <username>

gconftool-2 --type list --list-type=string \
    --set /system/storage/default_options/vfat/mount_options \
    "[shortname=mixed,uid=,usefree,iocharset=koi8-r,codepage=866]"

#################
} # END OF FILE #
#################

