#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/hdparm/hdparm-9.37.tar.gz"
MD5SUMLIST="0bb94ddd1bedd5c02b1ca62f1caaf6de"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} binprefix=/usr/ install

#################
} # END OF FILE #
#################

