#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://icedtea.classpath.org/download/source/icedtea-web-1.0.1.tar.gz"
MD5SUMLIST="30f969de0503a296226ae0a1876f9702"
REQUIRES="icedtea6"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed 's@prefix)/man@mandir)@' \
    -i Makefile.in
./configure --prefix=${JAVA_HOME}/jre \
            --with-jdk-home=${JAVA_HOME} \
            --disable-docs \
            --mandir=${JAVA_HOME}/man
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

ln -s ${JAVA_HOME}/jre/lib/<arch>/IcedTeaPlugin.so \
    /usr/lib/mozilla/plugins/

#################
} # END OF FILE #
#################

