#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/id3lib/id3lib-3.8.3.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/id3lib-3.8.3-gcc43-1.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/id3lib-3.8.3-test_suite-1.patch"
MD5SUMLIST="19f27ddd2dda4b2d26a559a4f0f402a7
            dontverify
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../id3lib-3.8.3-gcc43-1.patch
patch -Np1 -i ../id3lib-3.8.3-test_suite-1.patch
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/id3lib-3.8.3
install -v -m644 doc/*.{gif,jpg,png,ico,css,txt,php,html} \
    ${FAKEROOT}/usr/share/doc/id3lib-3.8.3

#################
} # END OF FILE #
#################

