#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/k3b/k3b-1.0.4.tar.bz2"
MD5SUMLIST="42538ddae0809707d3bcdbe0a6ed6a43"
REQUIRES="kdelibs"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(kde-config --prefix) \
            --sysconfdir=/etc/kde \
            --disable-debug \
            --disable-dependency-tracking
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

