#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://mirrors.isc.org/pub/kde/stable/4.6.0/src/kdewebdev-4.6.0.tar.bz2"
MD5SUMLIST="9ea899175bc58d5a9333d858b12f705c"
REQUIRES="kde4pimlibs libxml2 libxslt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=$KDE4_PREFIX \
    -DKDE_DEFAULT_HOME=.kde4 \
    -DSYSCONF_INSTALL_DIR=/etc/sysconfig \
    ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

