#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/trinity/kdebase-3.5.13.tar.gz"
MD5SUMLIST="d1f7e1f94eeb46b981fe1ba144179840"
REQUIRES="dbus-qt3 kdelibs"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

MAKEDIR=/tmp/buildbase
KDEBASE=`pwd`
rm -rf   $MAKEDIR
mkdir -p $MAKEDIR
cd       $MAKEDIR

cmake -DCMAKE_INSTALL_PREFIX=$TRINITY_PREFIX \
      -DCMAKE_VERBOSE_MAKEFILE=ON            \
      -DWITH_ARTS=ON                         \
      -DWITH_SHADOW=ON                       \
      -DWITH_XCURSOR=ON                      \
      -DWITH_XFIXES=ON                       \
      -DWITH_XRANDR=ON                       \
      -DWITH_XRENDER=ON                      \
      -DWITH_XDAMAGE=ON                      \
      -DWITH_XEXT=ON                         \
      -DWITH_XDMCP=ON                        \
      -DWITH_XINERAMA=ON                     \
      -DWITH_SAMBA=ON                        \
      -DWITH_LIBUSB=ON                       \
      -DWITH_SUDO_KDESU_BACKEND=ON           \
      -DBUILD_ALL=ON                         \
      -DWITH_XCOMPOSITE=ON                   \
      $KDEBASE

unset KDEBASE MAKEDIR

cmake

export LIBRARY_PATH=$XORG_PREFIX/lib:/lib
find -name link.txt -exec sed -i -e "s@-lICE@& -lX11 -lXrender -ltirpc@" {} \;

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

