#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/trinity/kdemultimedia-3.5.13.tar.gz"
MD5SUMLIST="6d906b8a8fd0928e01ecd600175381c0"
REQUIRES="kdebase"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cp -v /usr/share/aclocal/libtool.m4       admin/libtool.m4.in
cp -v /usr/share/libtool/config/ltmain.sh admin/ltmain.sh
sed -i -e "s@/usr/include/tqt@$TRINITY_PREFIX/include/tqt@" \
          admin/acinclude.m4.in
make -f admin/Makefile.common

sed -i -e 's@^gentable_LDADD.*$@& -L$(TRINITY_PREFIX)/lib@' \
          noatun/library/Makefile.in

export LIBRARY_PATH=$TRINITY_PREFIX/lib

./configure --prefix=$TRINITY_PREFIX                         \
            --with-qt-dir=$QTDIR                             \
            --enable-closure                                 \
            --with-vorbis                                    \
            --with-alsa                                      \
            --with-audiofile                                 \
            --with-flac                                      \
            --with-akode                                     \
            --with-cdparanoia                                \
            --with-kscd-cdda                                 \
            --with-lame                                      \
            --with-xine                                      \
            --with-theora                                    \
            --with-extra-includes=$TRINITY_PREFIX/include    \
            --with-extra-libs=$TRINITY_PREFIX/lib:$QTDIR/lib

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

