#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/trinity/kdepim-3.5.13.tar.gz"
MD5SUMLIST="4488062d5400bdd99642fe0b72ebcf9a"
REQUIRES="kdebase"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

MAKEDIR=/tmp/buildpim
KDEPIM=`pwd`
rm -rf   $MAKEDIR
mkdir -p $MAKEDIR
cd       $MAKEDIR

cmake -DCMAKE_INSTALL_PREFIX=$TRINITY_PREFIX \
      -DCMAKE_VERBOSE_MAKEFILE=ON            \
      -DWITH_ARTS=ON                         \
      -DBUILD_ALL=ON                         \
      -DBUILD_INDEXLIB=OFF                   \
      $KDEPIM

unset KDEPIM MAKEDIR
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

