#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://mirrors.isc.org/pub/kde/stable/koffice-1.6.3/src/koffice-1.6.3.tar.bz2"
MD5SUMLIST="386d388094734f9759977c3267098e30"
REQUIRES="kdebase"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(kde-config --prefix) --disable-debug \
    --disable-dependency-tracking
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

