#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.research.att.com/~gsf/download/tgz/ast-ksh.2008-11-04.tgz"
MD5SUMLIST="630096418741335fd757cda3f054aa11"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir ksh
cd ksh
tar -xf ../INIT.2008-11-04.tgz
tar -xf ../ast-ksh.2008-11-04.tgz
bin/package make

install -v -m755 arch/linux.i386/bin/ksh ${FAKEROOT}/bin
install -v -m644 arch/linux.i386/man/man1/sh.1 \
    ${FAKEROOT}/usr/share/man/man1/ksh.1
install -v -m755 -d ${FAKEROOT}/usr/share/doc/ksh-2008-11-04
install -v -m644 lib/package/{ast-ksh,INIT}.html \
    ${FAKEROOT}/usr/share/doc/ksh-2008-11-04

cat >> ${FAKEROOT}/etc/shells << "EOF"
/bin/ksh
EOF

#################
} # END OF FILE #
#################

