#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/lame/files/lame/3.99/lame-3.99.3.tar.gz"
MD5SUMLIST="5ad31e33e70455eb3a7b79a5dd934fce"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-mp3rtp
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

