#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://liba52.sourceforge.net/files/a52dec-0.7.4.tar.gz"
MD5SUMLIST="caa9f5bc44232dc8aeea773fea56be80"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-shared
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D doc/liba52.txt \
    ${FAKEROOT}/usr/share/doc/liba52-0.7.4/liba52.txt

#################
} # END OF FILE #
#################

