#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libbonoboui/2.24/libbonoboui-2.24.5.tar.bz2"
MD5SUMLIST="853be8e28aaa4ce48ba60be7d9046bf4"
REQUIRES="libglade libgnome libgnomecanvas orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0)
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d $(pkg-config \
        --variable=prefix ORBit-2.0)/share/doc/libbonoboui-2.24.5
install -v -m644 doc/*.{dtd,txt,xml,html} $(pkg-config \
        --variable=prefix ORBit-2.0)/share/doc/libbonoboui-2.24.5

#################
} # END OF FILE #
#################

