#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libcroco/0.6/libcroco-0.6.2.tar.bz2"
MD5SUMLIST="1429c597aa4b75fc610ab3a542c99209"
REQUIRES="glib2 libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/libcroco-0.6.2/examples
install -v -m644 README docs/usage.txt \
    ${FAKEROOT}/usr/share/doc/libcroco-0.6.2
install -v -m644 docs/examples/*.c \
    ${FAKEROOT}/usr/share/doc/libcroco-0.6.2/examples

#################
} # END OF FILE #
#################

