#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://launchpad.net/libdbusmenu-qt/trunk/0.7.0/+download/libdbusmenu-qt-0.7.0.tar.bz2"
MD5SUMLIST="512dc3213afcf0c561ac28000e85a80d"
REQUIRES="pkgconfig qt4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=$(pkg-config --variable=prefix QtCore) ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

