#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.videolan.org/pub/libdvdcss/1.2.10/libdvdcss-1.2.10.tar.bz2"
MD5SUMLIST="ebd5370b79ac5a83e5c61b24a214cf74"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

quit

echo "INPUT_ENCODING         = ISO-8859-1" >>doc/doxygen.cfg

./configure --prefix=/usr
make

make -C doc/latex pdf

make DESTDIR=${FAKEROOT} install

install -v -m755 -d         ${FAKEROOT}/usr/share/doc/libdvdcss-1.2.10/html
install -v -m644 doc/html/* ${FAKEROOT}/usr/share/doc/libdvdcss-1.2.10/html
install -v -m644 doc/latex/*.{pdf,ps,dvi} \
                            ${FAKEROOT}/usr/share/doc/libdvdcss-1.2.10

#################
} # END OF FILE #
#################

