#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/libexif/libexif-0.6.19.tar.bz2"
MD5SUMLIST="56144a030a4c875c600b1ccf713f69f7"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-doc-dir=/usr/share/doc/libexif-0.6.19
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

