#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://mirrors.ibiblio.org/pub/mirrors/ggzgamingzone/ggz/0.0.14.1/libggz-0.0.14.1.tar.gz"
MD5SUMLIST="603739504648833779aa13b0327a1c3d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-tls
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

