#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libgail-gnome/1.20/libgail-gnome-1.20.3.tar.bz2"
MD5SUMLIST="11fde9cc917c2572c87bfda10cc52751"
REQUIRES="at-spi gnome-panel libgnomeui orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

