#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libgsf/1.14/libgsf-1.14.21.tar.bz2"
MD5SUMLIST="2b702648b853402554c97d75405c60d3"
REQUIRES="glib2 libxml2 perl-xml-parser"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
  --sysconfdir=/etc/gnome/2.30.2
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

