#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.iodbc.org/downloads/iODBC/libiodbc-3.52.7.tar.gz"
MD5SUMLIST="ddbd274cb31d65be6a78da58fc09079a"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure prefix=/usr --with-iodbc-inidir=/etc/iodbc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

