#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/BLFS/svn/l/libksba-1.2.0.tar.bz2"
MD5SUMLIST="e797f370b69b4dc776499d6a071ae137"
REQUIRES="libgpg-error"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

makeinfo --html --no-split -o doc/ksba_nochunks.html doc/ksba.texi
makeinfo --plaintext       -o doc/ksba.txt           doc/ksba.texi

tex --output-directory=doc ksba.texi
dvips -o doc/ksba.ps doc/ksba.dvi
make -C doc pdf html

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/libksba-1.2.0
install -v -m644    README doc/ksba{_nochunks.html,.txt,.texi} \
                    ${FAKEROOT}/usr/share/doc/libksba-1.2.0

install -v -m755 -d ${FAKEROOT}/usr/share/doc/libksba-1.2.0/html
install -v -m644 doc/ksba.html/* \
                    ${FAKEROOT}/usr/share/doc/libksba-1.2.0/html
install -v -m644 doc/ksba.{pdf,ps,dvi} \
                    ${FAKEROOT}/usr/share/doc/libksba-1.2.0

#################
} # END OF FILE #
#################

