#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.musicbrainz.org/pub/musicbrainz/libmusicbrainz-3.0.3.tar.gz"
MD5SUMLIST="f4824d0a75bdeeef1e45cc88de7bb58a"
REQUIRES="cmake neon"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cmake -DCMAKE_INSTALL_PREFIX=/usr .
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

