#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/mad/libmad-0.15.1b.tar.gz"
MD5SUMLIST="1be543bc30c56fb6bea1d7bf6a64e66c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/-fforce-mem/d' configure
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

cat > ${FAKEROOT}/usr/lib/pkgconfig/mad.pc << "EOF"
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: mad
Description: MPEG audio decoder
Requires:
Version: 0.15.1b
Libs: -L${libdir} -lmad
Cflags: -I${includedir}
EOF

#################
} # END OF FILE #
#################

