#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/libmng/libmng-1.0.10.tar.bz2"
MD5SUMLIST="eaf1476a3bb29f6190bca660e6abef16"
REQUIRES="lcms libjpeg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cp makefiles/makefile.linux Makefile
sed -i -e 's/unroll-loops/& -fPIC/' Makefile
make

make DESTDIR=${FAKEROOT} prefix=/usr install
install -v -m644 doc/man/*.3 ${FAKEROOT}/usr/share/man/man3
install -v -m644 doc/man/*.5 ${FAKEROOT}/usr/share/man/man5
install -v -m755 -d ${FAKEROOT}/usr/share/doc/libmng-1.0.10
install -v -m644 doc/*.{png,txt} ${FAKEROOT}/usr/share/doc/libmng-1.0.10

#################
} # END OF FILE #
#################

