#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/heroines/libmpeg3-1.8-src.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/libmpeg3-1.8-makefile_fixes-1.patch"
MD5SUMLIST="a9d0d34e8941a4437eb8e7dfe559eca1
            dontverify"
REQUIRES="nasm"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../libmpeg3-1.8-makefile_fixes-1.patch
./configure
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

