#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/libquicktime/libquicktime-1.1.3.tar.gz"
MD5SUMLIST="e4fcda219f1e0ca508d9baa3700e4a59"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --docdir=/usr/share/doc/libquicktime-1.1.3 \
            --without-doxygen
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/libquicktime-1.1.3
install -v -m644    README doc/{*.txt,*.html,mainpage.incl} \
                    ${FAKEROOT}/usr/share/doc/libquicktime-1.1.3

#################
} # END OF FILE #
#################

