#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/librep/files/librep/0.90.5/librep-0.90.5.tar.bz2"
MD5SUMLIST="76e766d4f7034ee293f4405871ab34d3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --libexecdir=/usr/lib
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

