#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/rest/0.7/rest-0.7.12.tar.xz"
MD5SUMLIST="dc14e0d89d38af5d8d544ce8f124d186"
REQUIRES="cacerts glib2 libsoup libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-ca-certificates=/etc/ssl/ca-bundle.crt
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

