#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://webm.googlecode.com/files/libvpx-v1.0.0.tar.bz2"
MD5SUMLIST="d987b5140412edd37d2c6b10c29ad484"
REQUIRES="nasm which yasm"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir ../libvpx-build
cd ../libvpx-build
../libvpx-v1.0.0/configure --prefix=/usr --enable-shared
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

