#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://links.twibright.com/download/links-2.4.tar.bz2"
MD5SUMLIST="aedee41d9ee941378dc0ab114a65f353"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -d -m755 ${FAKEROOT}/usr/share/doc/links-2.4
install -v -m644 doc/links_cal/* KEYS BRAILLE_HOWTO \
    ${FAKEROOT}/usr/share/doc/links-2.4

#################
} # END OF FILE #
#################

