#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="https://fedorahosted.org/releases/l/i/linux-pam/Linux-PAM-1.1.5.tar.bz2
          https://fedorahosted.org/releases/l/i/linux-pam/Linux-PAM-1.1.5-docs.tar.bz2"
MD5SUMLIST="927ee5585bdec5256c75117e9348aa47
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xf ../Linux-PAM-1.1.5-docs.tar.bz2 --strip-components=1

./configure --sbindir=/lib/security \
            --docdir=/usr/share/doc/Linux-PAM-1.1.5 \
            --disable-nis \
            --enable-read-both-confs
make

install -v -m755 -d ${FAKEROOT}/etc/pam.d

cat > ${FAKEROOT}/etc/pam.d/other << "EOF"
auth     required       pam_deny.so
account  required       pam_deny.so
password required       pam_deny.so
session  required       pam_deny.so
EOF

rm -rfv ${FAKEROOT}/etc/pam.d

make DESTDIR=${FAKEROOT} install
chmod -v 4755 ${FAKEROOT}/lib/security/unix_chkpwd
mv -v ${FAKEROOT}/lib/security/pam_tally ${FAKEROOT}/sbin

#################
} # END OF FILE #
#################

