#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://sources.redhat.com/pub/lvm2/LVM2.2.02.88.tgz"
MD5SUMLIST="321429cd1b1526a29cf6d75018b1e4bb"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-pkgconfig
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

