#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.oberhumer.com/opensource/lzo/download/lzo-2.03.tar.gz"
MD5SUMLIST="0c3d078c2e8ea5a88971089a2f02a726"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-shared
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/lzo-2.03
install -v -m644 doc/* ${FAKEROOT}/usr/share/doc/lzo-2.03

#################
} # END OF FILE #
#################

