#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://distfiles.atheme.org/libmcs-0.7.1.tgz"
MD5SUMLIST="1611a7bd7e7b07df3d889012d133c440"
REQUIRES="mowgli"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D README ${FAKEROOT}/usr/share/doc/libmcs-0.7.1/README

#################
} # END OF FILE #
#################

