#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/metacity/2.34/metacity-2.34.1.tar.xz"
MD5SUMLIST="d505e2d7936bd9b11a3f48470a616767"
REQUIRES="gconf gtk+2 libcanberra perl-xml-parser zenity"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure \
    --prefix=/usr \
    --with-gconf-schema-file-dir=$GNOME_SYSCONFDIR/gconf/schemas
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/metacity-2.34.1
install -v -m644 README rationales.txt doc/*.txt \
                    ${FAKEROOT}/usr/share/doc/metacity-2.34.1

#################
} # END OF FILE #
#################

