#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.mplayerhq.hu/MPlayer/releases/MPlayer-1.0rc1.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/MPlayer-1.0rc1-ext_ffmpeg-1.patch
          http://www.mplayerhq.hu/MPlayer/releases/codecs/essential-20061022.tar.bz2
          http://www.mplayerhq.hu/MPlayer/skins/Blue-1.7.tar.bz2
          http://www1.mplayerhq.hu/MPlayer/releases/fonts/font-arial-iso-8859-1.tar.bz2"
MD5SUMLIST="18c05d88e22c3b815a43ca8d7152ccdc
            dontverify
            dontverify
            dontverify
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

install -v -d -m755 ${FAKEROOT}/usr/lib/mplayer/codecs
tar -xvf ../essential-20061022.tar.bz2 \
    -C ${FAKEROOT}/usr/lib/mplayer/codecs --strip-components=1
chown -v -R root:root ${FAKEROOT}/usr/lib/mplayer/codecs

install -v -d -m755 ${FAKEROOT}/usr/share/mplayer/Skin
tar -xvf ../Blue-1.7.tar.bz2 \
    -C ${FAKEROOT}/usr/share/mplayer/Skin
chown -v -R root:root ${FAKEROOT}/usr/share/mplayer/Skin/Blue
chmod -v 755 ${FAKEROOT}/usr/share/mplayer/Skin/Blue{,/icons}
ln -sfv Blue ${FAKEROOT}/usr/share/mplayer/Skin/default

patch -Np0 -i ../asmrules_fix_20061231.diff
patch -Np0 -i ../cddb_fix_20070605.diff
patch -Np1 -i ../MPlayer-1.0rc1-ext_ffmpeg-1.patch

./configure --prefix=/usr \
            --confdir=/etc/mplayer \
            --enable-largefiles \
            --enable-dynamic-plugins
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/mplayer-1.0rc1
cp -v -R DOCS/*     ${FAKEROOT}/usr/share/doc/mplayer-1.0rc1

ln -v -s libdha.so.1.0 ${FAKEROOT}/usr/lib/libdha.so

install -m644 etc/codecs.conf ${FAKEROOT}/etc/mplayer

install -m644 etc/*.conf ${FAKEROOT}/etc/mplayer

echo "dev.rtc.max-user-freq=1024" >> ${FAKEROOT}/etc/sysctl.conf

install -v -m750 -d ~/.mplayer
ln -v -sf /usr/share/fonts/X11-TTF/luxisri.ttf \
    ~/.mplayer/subfont.ttf

tar -xvf ../font-arial-iso-8859-1.tar.bz2 \
    -C ${FAKEROOT}/usr/share/mplayer/font
chown -v -R root:root ${FAKEROOT}/usr/share/mplayer/font
cd ${FAKEROOT}/usr/share/mplayer/font
ln -v -sf font-arial-iso-8859-1/font-arial-<font size>-iso-8859-1/* .

#################
} # END OF FILE #
#################

