#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/mutt/mutt-1.5.21.tar.gz"
MD5SUMLIST="a29db8f1d51e2f10c070bf88e8a553fd"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

chgrp -v mail ${FAKEROOT}/var/mail

./configure --prefix=/usr --sysconfdir=/etc \
            --with-docdir=/usr/share/doc/mutt-1.5.21 \
            --enable-pop --enable-imap \
            --enable-hcache --without-qdbm \
            --without-tokyocabinet \
            --with-gdbm --without-bdb
make

make -C doc manual.pdf

make DESTDIR=${FAKEROOT} install

install -v -m644 doc/manual.{pdf,tex} \
    ${FAKEROOT}/usr/share/doc/mutt-1.5.21

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 34 mail

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

cat /usr/share/doc/mutt-1.5.21/samples/gpg.rc >> ~/.muttrc

ln -v -s gpg2 /usr/bin/gpg

#################
} # END OF FILE #
#################

