#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://source.clutter-project.org/sources/mx/1.2/mx-1.2.1.tar.bz2"
MD5SUMLIST="1d7f9764c6e79cadf9f1cae3bcbe0eef"
REQUIRES="clutter dbus gdk-pixbuf gobject-introspection gtk+2 startup-notification"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

