#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/infosys/clients/ftp/ncftp/ncftp-3.2.3-src.tar.bz2"
MD5SUMLIST="fac4aa169e1734e8d9617afd4a9b51e5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make -C libncftp shared
make

make DESTDIR=${FAKEROOT} -C libncftp soinstall
make DESTDIR=${FAKEROOT} install

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

