#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.webdav.org/neon/neon-0.29.6.tar.gz"
MD5SUMLIST="591e0c82e6979e7e615211b386b8f6bc"
REQUIRES="expat libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-shared
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

