#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-4.2/ntp-4.2.6p4.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="1447121a07b49361677ffda4f6e29527
            dontverify"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc \
            --with-binsubdir=sbin
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/ntp-4.2.6p4
cp -v -R html/* ${FAKEROOT}/usr/share/doc/ntp-4.2.6p4/

cat > ${FAKEROOT}/etc/ntp.conf << "EOF"
# Africa
server tock.nml.csir.co.za

# Asia
server 0.asia.pool.ntp.org

# Australia
server 0.oceania.pool.ntp.org

# Europe
server 0.europe.pool.ntp.org

# North America
server 0.north-america.pool.ntp.org

# South America
server 2.south-america.pool.ntp.org

driftfile /var/cache/ntp.drift
pidfile   /var/run/ntpd.pid
EOF

includeBootscript ntpd

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

ln -v -sf ../init.d/setclock /etc/rc.d/rc0.d/K46setclock
ln -v -sf ../init.d/setclock /etc/rc.d/rc6.d/K46setclock

#################
} # END OF FILE #
#################

