#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/opal/3.10/opal-3.10.2.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/opal-3.10.2-ffmpeg-1.patch"
MD5SUMLIST="11263275c51e3ea77de202bf5ca87e0b
            dontverify"
REQUIRES="ptlib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../opal-3.10.2-ffmpeg-1.patch
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

