#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.osuosl.org/pub/openoffice/stable/3.2.1/OOo_3.2.1_src_core.tar.bz2
          ftp://ftp.mozilla.org/pub/mozilla.org/seamonkey/releases/1.1.14/seamonkey-1.1.14.source.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/OOo_3.2.1-build_with_db5-1.patch"
MD5SUMLIST="4fa713fb796bc57e5eb9dfb0758adda0
            dontverify
            dontverify"
REQUIRES="apache-ant gtk+2 libidl perl-archive-zip perl-xml-parser pkgconfig unzip which zip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cp ../seamonkey-1.1.14.source.tar.bz2 moz/download/

umask 0022
unset LANG LC_ALL

patch -Np1 -i ../OOo_3.2.1-build_with_db5-1.patch
autoreconf
PKG_CONFIG=/usr/bin/pkg-config ./configure \
            --disable-binfilter            \
            --disable-fontooo              \
            --disable-gnome-vfs            \
            --disable-odk                  \
            --disable-qadevooo             \
            --enable-cairo                 \
            --without-afms                 \
            --without-fonts                \
            --without-ppds                 \
            --without-pam                  \
            --with-system-stdlibs          \
            --with-system-cairo            \
            --with-system-expat            \
            --with-system-zlib             \
            --with-package-format=native   \
            --with-vendor="BLFS"           \
            --with-use-shell=bash
source LinuxX86Env.Set.sh
./bootstrap
make

pushd instsetoo_native/unxlng?6.pro/OpenOffice/\
native/install/en-US/linux-2.6-*/buildroot/opt
cp -r -v openoffice.org3 ${FAKEROOT}/opt/openoffice-3.2.1
cp -r -v openoffice.org/* ${FAKEROOT}/opt/openoffice-3.2.1
ln -sf basis3.2 ${FAKEROOT}/opt/openoffice-3.2.1/basis-link
popd

for appl in sbase scalc sdraw simpress smath soffice spadmin swriter
do
    ln -v -sf ${FAKEROOT}/opt/openoffice-3.2.1/program/$appl ${FAKEROOT}/usr/bin
done

pushd sysui/desktop/icons
install -v -m755 -d ${FAKEROOT}/usr/share/icons/{hicolor,locolor}
cp -r -v hicolor/* ${FAKEROOT}/usr/share/icons/hicolor
cp -r -v locolor/* ${FAKEROOT}/usr/share/icons/locolor
popd

install -v -d -m755 ${FAKEROOT}/usr/share/applications
pushd ${FAKEROOT}/opt/openoffice-3.2.1/share/xdg/
for appl in *.desktop
do
    sed -i '/Exec/d' $appl
    echo "Exec=/usr/bin/s`echo $appl | sed 's/.desktop//'`" >> $appl
    sed -i '/Icon/d' $appl
    echo "Icon=`echo "ooo-${appl}3.2" | sed 's/\.desktop//'`" >> $appl
done
sed -i 's@bin/sprinteradmin@bin/spadmin@' printeradmin.desktop
cp -v *.desktop ${FAKEROOT}/usr/share/applications
update-desktop-database
popd

cp -v dictionaries/unxlngi6.pro/bin/dict-*.oxt \
    sdext/unxlngi6.pro/bin/*.oxt \
    reportbuilder/unxlngi6.pro/bin/report-builder.oxt \
    swext/unxlngi6.pro/bin/wiki-publisher.oxt \
    ${FAKEROOT}/opt/openoffice-3.2.1/share/extension/install

for ext in ${FAKEROOT}/opt/openoffice-3.2.1/share/extension/install/*.oxt
do
    ${FAKEROOT}/opt/openoffice-3.2.1/program/unopkg add --shared --verbose $ext
done

#################
} # END OF FILE #
#################

