#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/orca/3.2/orca-2.30.2.tar.bz2"
MD5SUMLIST="8988f96533109c14cbd5ac8f2b0754f2"
REQUIRES="at-spi dbus-python orbit2 pkgconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

if [ $(pkg-config --variable=prefix ORBit-2.0) != "/usr" ]; then
    sed -i "s|PATH=\"|&$(pkg-config \
           --variable=prefix ORBit-2.0)/bin:|" \
        src/orca/orca.in
fi

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0)
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

