#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://mirrors.isc.org/pub/kde/stable/4.6.0/src/oxygen-icons-4.6.0.tar.bz2"
MD5SUMLIST="47b943e1b8bc2c1cef10fd791ac70091"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=$KDE4_PREFIX ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

