#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.packagekit.org/releases/PackageKit-0.7.1.tar.xz"
MD5SUMLIST="f31a53e5bbd95ee737fce0b4bd174083"
REQUIRES="dbus dbus-glib glib2 gtk+3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/PackageKit \
            --localstatedir=/var \
            --disable-tests \
            --disable-qt
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

