#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://pan.rebelbase.com/download/releases/0.133/source/pan-0.133.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/pan-0.133-gmime_gcc-1.patch"
MD5SUMLIST="ca165da8557605d89d327cff78891b89
            dontverify"
REQUIRES="gmime gtk+2 intltool pcre"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../pan-0.133-gmime_gcc-1.patch
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

