#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/paps/paps-0.6.8.tar.gz"
MD5SUMLIST="e9508132bf27609bf2fded2bfd9cb3f1"
REQUIRES="pango"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d                 ${FAKEROOT}/usr/share/doc/paps-0.6.8
install -v -m644 doxygen-doc/html/* ${FAKEROOT}/usr/share/doc/paps-0.6.8

#################
} # END OF FILE #
#################

