#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/parted/parted-3.0.tar.xz"
MD5SUMLIST="c415e5c97f86b5ff65a2d925e5a3feb7"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --enable-device-mapper=no
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

