#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/pdl/PDL-2.4.2.tar.gz"
MD5SUMLIST="edd056a006eae8b46e8ef804b9774a93"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/\(dirname);\)/\1\nuse blib;/' Demos/BAD*demo.pm.PL
perl Makefile.PL
make
make test

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

