#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://us2.php.net/distributions/php-5.3.8.tar.bz2"
MD5SUMLIST="704cd414a0565d905e1074ffdc1fadfb"
REQUIRES="apache"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-apxs2 \
            --with-config-file-path=/etc \
            --with-zlib \
            --enable-bcmath \
            --with-bz2 \
            --enable-calendar \
            --enable-dba=shared \
            --with-gdbm \
            --with-gmp \
            --enable-ftp \
            --with-gettext \
            --enable-mbstring \
            --with-readline
make

make DESTDIR=${FAKEROOT} install
install -v -m644 php.ini-production ${FAKEROOT}/etc/php.ini

install -v -m755 -d ${FAKEROOT}/usr/share/doc/php-5.3.8
install -v -m644 CODING_STANDARDS EXTENSIONS INSTALL NEWS \
                 README* TODO* UPGRADING php.gif \
    ${FAKEROOT}/usr/share/doc/php-5.3.8
ln -v -sfn ${FAKEROOT}/usr/lib/php/doc/Archive_Tar/docs/Archive_Tar.txt \
         ${FAKEROOT}/usr/share/doc/php-5.3.8
ln -v -sfn ${FAKEROOT}/usr/lib/php/doc/Structures_Graph/docs \
         ${FAKEROOT}/usr/share/doc/php-5.3.8

install -v -m644 ../php_manual_en.html.gz \
    ${FAKEROOT}/usr/share/doc/php-5.3.8
gunzip -v ${FAKEROOT}/usr/share/doc/php-5.3.8/php_manual_en.html.gz

tar -xvf ../php_manual_en.tar.gz \
    -C ${FAKEROOT}/usr/share/doc/php-5.3.8 --no-same-owner

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

sed -i 's@php/includes"@&\ninclude_path = ".:/usr/lib/php"@' \
    /etc/php.ini

#################
} # END OF FILE #
#################

