#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.pilot-link.org/pilot-link-0.12.2.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/pilot-link-0.12.2-bindings_fix-1.patch"
MD5SUMLIST="c1f4db8f32a2ee916fedb9a2dac8aa26
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../pilot-link-0.12.2-bindings_fix-1.patch
./configure --prefix=/usr \
            --enable-threads \
            --enable-conduits \
            --with-perl
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/pilot-link-0.12.2
install -v -m644 README doc/{README.*,TODO,CodingGuidelines} \
                    ${FAKEROOT}/usr/share/doc/pilot-link-0.12.2

#################
} # END OF FILE #
#################

