#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://hal.freedesktop.org/releases/PolicyKit-0.9.tar.gz"
MD5SUMLIST="802fd13ae41f73d79359e5ecb0a98716"
REQUIRES="dbus-glib docbook-xsl intltool linux-pam"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc \
    --libexecdir=/usr/lib/PolicyKit --localstatedir=/var
make

make DESTDIR=${FAKEROOT} install
install -v -d -m755 ${FAKEROOT}/usr/share/doc/PolicyKit-0.9
cp -v -r doc/html ${FAKEROOT}/usr/share/doc/PolicyKit-0.9

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -fg 27 polkituser
useradd -c "Policy Kit Daemon User" -d /dev/null -u 27 \
    -g polkituser -s /bin/false polkituser || [ $? == 9 ]

#################
} # END OF FILE #
#################

