#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/polkit-gnome/0.104/polkit-gnome-0.104.tar.xz"
MD5SUMLIST="e1188c42fb61ec4ab3b26dde59145bca"
REQUIRES="gtk+3 polkit"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
    --libexecdir=/usr/lib/polkit-gnome
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

