#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.kde.org/pub/kde/stable/apps/KDE4.x/admin/polkit-qt-1-0.99.0.tar.bz2"
MD5SUMLIST="1c5b4113a2a167624b5f716b4f03a219"
REQUIRES="polkit"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

CMAKE_PREFIX_PATH=$QT4DIR \
    cmake -DCMAKE_INSTALL_PREFIX=$KDE4_PREFIX ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

