#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://poppler.freedesktop.org/poppler-0.14.4.tar.gz
          http://poppler.freedesktop.org/poppler-data-0.4.3.tar.gz"
MD5SUMLIST="a40fe96e1115f648ce4689e667743530
            dontverify"
REQUIRES="fontconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d      ${FAKEROOT}/usr/share/doc/poppler-0.14.4
install -v -m644 README* ${FAKEROOT}/usr/share/doc/poppler-0.14.4

tar -xf ../poppler-data-0.4.3.tar.gz
cd poppler-data-0.4.3

make DESTDIR=${FAKEROOT} prefix=/usr install

#################
} # END OF FILE #
#################

