#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/db/postgresql/source/v9.0.6/postgresql-9.0.6.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="4ad7e4fc31ef8b8a75a3e4243933963f
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
  --docdir=/usr/share/doc/postgresql-9.0.6 \
  --enable-thread-safety
make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-docs
chown -v root:root ${FAKEROOT}/usr/share/doc/postgresql-9.0.6/html/*

install -v -m700 -d ${FAKEROOT}/srv/pgsql/data
groupadd -g 41 postgres
useradd -c "PostgreSQL Server" -g postgres -d ${FAKEROOT}/srv/pgsql/data \
        -u 41 postgres
chown -v postgres ${FAKEROOT}/srv/pgsql/data
su - postgres -c '/usr/bin/initdb -D ${FAKEROOT}/srv/pgsql/data'

su - postgres -c '/usr/bin/postmaster -D ${FAKEROOT}/srv/pgsql/data > \
    ${FAKEROOT}/srv/pgsql/data/logfile 2>&1 &'

su - postgres -c '/usr/bin/createdb test'
echo "create table t1 ( name varchar(20), state_province varchar(20) );" \
    | (su - postgres -c '/usr/bin/psql test ')
echo "insert into t1 values ('Billy', 'NewYork');" \
    | (su - postgres -c '/usr/bin/psql test ')
echo "insert into t1 values ('Evanidus', 'Quebec');" \
    | (su - postgres -c '/usr/bin/psql test ')
echo "insert into t1 values ('Jesse', 'Ontario');" \
    | (su - postgres -c '/usr/bin/psql test ')
echo "select * from t1;" | (su - postgres -c '/usr/bin/psql test')

includeBootscript postgresql

#################
} # END OF FILE #
#################

