#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://postfix.energybeam.com/source/official/postfix-2.8.4.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="a9fdd0f204e7ca0b7d32fd0b9f8f8c72
            dontverify"
REQUIRES="db"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

PF_CCARGS="-DDEF_DAEMON_DIR=\\\"/usr/lib/postfix\\\""
PF_CCARGS="$PF_CCARGS -DDEF_MANPAGE_DIR=\\\"/usr/share/man\\\""
PF_CCARGS="$PF_CCARGS -DDEF_HTML_DIR=\\\"/usr/share/doc/postfix-2.8.4/html\\\""
PF_CCARGS="$PF_CCARGS -DDEF_README_DIR=\\\"/usr/share/doc/postfix-2.8.4/README\\\""
PF_CCARGS="$PF_CCARGS -DHAS_PCRE"
PF_CCARGS="$PF_CCARGS -DUSE_TLS -I/usr/include/openssl"

PF_AUXLIBS="-lpcre -lssl -lcrypto"

make makefiles CCARGS="$PF_CCARGS" AUXLIBS="$PF_AUXLIBS"
make
unset PF_CCARGS PF_AUXLIBS

sh postfix-install -non-interactive

cat >> ${FAKEROOT}/etc/aliases << "EOF"
# Begin /etc/aliases

MAILER-DAEMON:    postmaster
postmaster:       root

root:             LOGIN
# End /etc/aliases
EOF

includeBootscript postfix

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 32 postfix
groupadd -g 33 postdrop
useradd -c "Postfix Daemon User" -d /dev/null -g postfix \
    -s /bin/false -u 32 postfix
chown -v postfix:postfix /var/mail

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

sed -i "s/LOGIN/<user>/" /etc/aliases
sed -i "s/#myhostname = host.domain.tld/myhostname = \
  <localhost.localdomain>/" /etc/postfix/main.cf
/usr/bin/newaliases

/usr/sbin/postfix upgrade-configuration

/usr/sbin/postfix check
/usr/sbin/postfix start

#################
} # END OF FILE #
#################

