#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/publishing/tex/tex-utils/psutils/psutils-p17.tar.gz"
MD5SUMLIST="b161522f3bd1507655326afa7db4a0ad"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed 's@/usr/local@/usr@g' Makefile.unix > Makefile
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

