#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/pth/pth-2.0.7.tar.gz"
MD5SUMLIST="9cb4a25331a4c4db866a31cbe507c793"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/pth-2.0.7
install -v -m644    README PORTING SUPPORT TESTS \
                    ${FAKEROOT}/usr/share/doc/pth-2.0.7

#################
} # END OF FILE #
#################

