#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.python.org/ftp/python/3.2.2/Python-3.2.2.tar.xz
          http://docs.python.org/ftp/python/doc/3.2.2/python-3.2.2-docs-html.tar.bz2"
MD5SUMLIST="3720ce9460597e49264bbb63b48b946d
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "s/ndbm_libs = \[\]/ndbm_libs = ['gdbm', 'gdbm_compat']/" setup.py
./configure --prefix=/usr --enable-shared
make

make DESTDIR=${FAKEROOT} install
chmod -v 755 ${FAKEROOT}/usr/lib/libpython3.2m.so.1.0
chmod -v 755 ${FAKEROOT}/usr/lib/libpython3.so 

install -v -m755 -d ${FAKEROOT}/usr/share/doc/Python-3.2.2/html
tar --strip-components=1 \
    --no-same-owner \
    --no-same-permissions \
    -C ${FAKEROOT}/usr/share/doc/Python-3.2.2/html \
    -xvf ../python-3.2.2-docs-html.tar.bz2

cat > ${FAKEROOT}/etc/profile.d/python3.sh << "EOF"
export PYTHONDOCS=/usr/share/doc/Python-3.2.2/html
EOF

#################
} # END OF FILE #
#################

