#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.qualcomm.com/eudora/servers/unix/popper/qpopper4.0.9.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="de2cd15f95cfd00d0d080fd16287acad
            dontverify"
REQUIRES="server-mail"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-standalone
make

make DESTDIR=${FAKEROOT} install
install -D -m644 GUIDE.pdf ${FAKEROOT}/usr/share/doc/qpopper-4.0.9/GUIDE.pdf

includeBootscript qpopper

cat > ${FAKEROOT}/etc/mail/qpopper.conf << "EOF"
# Qpopper configuration file

set debug = false

set spool-dir = /var/spool/mail/
set temp-dir  = /var/spool/mail/

set downcase-user = true
set trim-domain = true

set statistics = true

# End /etc/shells
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo "local0.notice;local0.debug /var/log/POP.log" >> \
    /etc/syslog.conf
killall -HUP syslogd

echo "pop3 stream tcp nowait root /usr/sbin/popper popper" >> \
    /etc/inetd.conf
killall inetd || inetd

#################
} # END OF FILE #
#################

