#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/trinity/qt3-3.3.8.d.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/qt-3.3.8.d-libpng15-1.patch"
MD5SUMLIST="78dc675e84aed595375449818cbb589a
            dontverify"
REQUIRES="x-window-system"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make sub-tools

sed -i '/QMAKE_RPATH/d' mkspecs/linux*/qmake.conf

bash
export PATH=$PWD/bin:$PATH
export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH

patch -Np1 -i ../qt-3.3.8.d-libpng15-1.patch

./configure -prefix     /usr                \
            -docdir     /usr/share/doc/qt   \
            -headerdir  /usr/include/qt     \
            -plugindir  /usr/lib/qt/plugins \
            -datadir    /usr/share/qt       \
            -sysconfdir /etc/qt             \
            -translationdir /usr/share/qt/translations \
            -qt-gif                         \
            -system-zlib                    \
            -system-libpng                  \
            -system-libjpeg                 \
            -system-libmng                  \
            -plugin-imgfmt-png              \
            -plugin-imgfmt-jpeg             \
            -plugin-imgfmt-mng              \
            -no-exceptions                  \
            -thread                         \
            -tablet

make
exit

make DESTDIR=${FAKEROOT} install
ln -v -sf libqt-mt.so ${FAKEROOT}/usr/lib/libqt.so
ln -v -snf ../../bin ${FAKEROOT}/usr/share/qt/bin
ln -v -snf ../../include/qt ${FAKEROOT}/usr/share/qt/include
ln -v -snf ../../lib ${FAKEROOT}/usr/share/qt/lib
cp -v -r doc/man ${FAKEROOT}/usr/share
cp -v -r examples ${FAKEROOT}/usr/share/doc/qt

bash
export QTDIR=$PWD
export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH
export PATH=$PWD/bin:$PATH

patch -Np1 -i ../qt-3.3.8.d-libpng15-1.patch

./configure -prefix /opt/qt-3.3.8d \
            -sysconfdir /etc/qt   \
            -qt-gif               \
            -system-zlib          \
            -system-libpng        \
            -system-libjpeg       \
            -system-libmng        \
            -plugin-imgfmt-png    \
            -plugin-imgfmt-jpeg   \
            -plugin-imgfmt-mng    \
            -no-exceptions        \
            -thread               \
            -tablet

make
exit

make DESTDIR=${FAKEROOT} install
ln -v -sfn qt-3.3.8d ${FAKEROOT}/opt/qt
ln -v -s libqt-mt.so ${FAKEROOT}/opt/qt/lib/libqt.so
cp -v -r doc/man examples ${FAKEROOT}/opt/qt/doc

# (*) Utilize the ld.so.conf directory
mkdir -pv ${FAKEROOT}/etc/ld.so.conf.d

cat >> ${FAKEROOT}/etc/ld.so.conf.d/qt.conf << "EOF"
# Begin qt addition to /etc/ld.so.conf.d/qt.conf

/opt/qt/lib

# End qt addition
EOF
ldconfig
cat >> ${FAKEROOT}/etc/man_db.conf << "EOF"
# Begin qt addition to man_db.conf

MANDATORY_MANPATH /opt/qt/doc/man
MANPATH_MAP       /opt/qt/bin         /opt/qt/doc/man
MANDB_MAP         /opt/qt/doc/man     /var/cache/man/qt

# End qt addition to man_db.conf
EOF

#################
} # END OF FILE #
#################

