#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://download.librdf.org/source/rasqal-0.9.20.tar.gz"
MD5SUMLIST="c45b6cd784298e264e8757d14355ecce"
REQUIRES="raptor"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

