#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://samba.org/ftp/rsync/src/rsync-3.0.9.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="5ee72266fe2c1822333c407e1761b92b
            dontverify"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

pushd doc
docbook2pdf             rsync.sgml
docbook2ps              rsync.sgml
docbook2dvi             rsync.sgml
docbook2txt             rsync.sgml
docbook2html --nochunks rsync.sgml
popd

make DESTDIR=${FAKEROOT} install

install -v -m755 -d          ${FAKEROOT}/usr/share/doc/rsync-3.0.9/api
install -v -m644 dox/html/*  ${FAKEROOT}/usr/share/doc/rsync-3.0.9/api
install -v -m644 doc/rsync.* ${FAKEROOT}/usr/share/doc/rsync-3.0.9

cat > ${FAKEROOT}/etc/rsyncd.conf << "EOF"
# This is a basic rsync configuration file
# It exports a single module without user authentication.

motd file = /home/rsync/welcome.msg
use chroot = yes

[localhost]
    path = /home/rsync
    comment = Default rsync module
    read only = yes
    list = yes
    uid = rsyncd
    gid = rsyncd

EOF

includeBootscript rsyncd

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 48 rsyncd
useradd -c "rsyncd Daemon" -d /home/rsync -g rsyncd \
    -s /bin/false -u 48 rsyncd

#################
} # END OF FILE #
#################

