#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://dist.schmorp.de/rxvt-unicode/Attic/rxvt-unicode-9.12.tar.bz2"
MD5SUMLIST="945af37d661c8c45a7cac292160e7c70"
REQUIRES="x-window-system"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-everything
make

make DESTDIR=${FAKEROOT} install

cat >> ${FAKEROOT}/etc/X11/app-defaults/URxvt << "EOF"
URxvt*perl-ext: matcher
URxvt*urlLauncher: firefox
URxvt.background: black
URxvt.foreground: yellow
URxvt*font: xft:Monospace:pixelsize=12
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# Start the urxvtd daemon
urxvtd -q -f -o &

#################
} # END OF FILE #
#################

