#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/sawmill/files/sawfish/1.6.1/sawfish-1.6.1.tar.bz2"
MD5SUMLIST="3200deb3428a5973d71e98b291f5247b"
REQUIRES="esound rep-gtk"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr             \
            --libexec=/usr/sbin       \
            --infodir=/usr/share/info \
            --disable-themer
make

make DESTDIR=${FAKEROOT} install

cat >> ${FAKEROOT}/etc/X11/app-defaults/xinitrc.d/sawfish.xinitrc << "EOF"
exec sawfish
EOF

#################
} # END OF FILE #
#################

