#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/scrollkeeper/0.3/scrollkeeper-0.3.14.tar.bz2"
MD5SUMLIST="b175e582a6cec3e50a9de73a5bb7455a"
REQUIRES="docbook libxslt perl-xml-parser"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --disable-static \
            --with-omfdirs=/usr/share/omf:\
/opt/kde-3.5.10/share/omf:\
/opt/gnome-3.2.2/share/omf

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

