#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.libsdl.org/release/SDL-1.2.14.tar.gz"
MD5SUMLIST="e52086d1b508fa0b76c52ee30b55bec4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/SDL-1.2.14/html
install -v -m644    docs/html/*.html \
                    ${FAKEROOT}/usr/share/doc/SDL-1.2.14/html

#################
} # END OF FILE #
#################

