#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.sendmail.org/ftp/sendmail.8.14.4.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="1b23d5000c8e7bfe82ec1a27f2f5fdc5
            dontverify"
REQUIRES="db"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cat >> devtools/Site/site.config.m4 << "EOF"
APPENDDEF(`confENVDEF',`-DSTARTTLS -DTCPWRAPPERS -DSASL -DLDAPMAP')
APPENDDEF(`confLIBS', `-lssl -lcrypto -lwrap -lsasl2 -lldap -llber')
APPENDDEF(`confINCDIRS', `-I/usr/include/sasl')
EOF

cat >> devtools/Site/site.config.m4 << "EOF"
define(`confMANGRP',`root')
define(`confMANOWN',`root')
define(`confSBINGRP',`root')
define(`confUBINGRP',`root')
define(`confUBINOWN',`root')
EOF
cd sendmail
sh Build
cd ../cf/cf
cp generic-linux.mc sendmail.mc
sh Build sendmail.cf

install -v -d -m755 ${FAKEROOT}/etc/mail
sh Build install-cf

cd ../..
sh Build install

install -v -m644 cf/cf/{submit,sendmail}.mc ${FAKEROOT}/etc/mail
cp -v -R cf/* ${FAKEROOT}/etc/mail

install -v -m755 -d ${FAKEROOT}/usr/share/doc/sendmail-8.14.4/{cf,sendmail}
install -v -m644 \
        CACerts FAQ KNOWNBUGS LICENSE PGPKEYS README RELEASE_NOTES \
        ${FAKEROOT}/usr/share/doc/sendmail-8.14.4
install -v -m644 sendmail/{README,SECURITY,TRACEFLAGS,TUNING} \
        ${FAKEROOT}/usr/share/doc/sendmail-8.14.4/sendmail
install -v -m644 cf/README ${FAKEROOT}/usr/share/doc/sendmail-8.14.4/cf

for manpage in sendmail editmap mailstats makemap praliases smrsh
do
    install -v -m444 $manpage/$manpage.8 ${FAKEROOT}/usr/share/man/man8
done
install -v -m444 sendmail/aliases.5    ${FAKEROOT}/usr/share/man/man5
install -v -m444 sendmail/mailq.1      ${FAKEROOT}/usr/share/man/man1
install -v -m444 sendmail/newaliases.1 ${FAKEROOT}/usr/share/man/man1
install -v -m444 vacation/vacation.1   ${FAKEROOT}/usr/share/man/man1

cd doc/op
sed -i 's/groff/GROFF_NO_SGR=1 groff/' Makefile
make op.txt op.pdf

install -v -d -m755 ${FAKEROOT}/usr/share/doc/sendmail-8.14.4
install -v -m644 op.ps op.txt op.pdf ${FAKEROOT}/usr/share/doc/sendmail-8.14.4
cd ../..

includeBootscript sendmail

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 26 smmsp
useradd -c "Sendmail Daemon" -g smmsp -d /dev/null \
        -s /bin/false -u 26 smmsp
chmod -v 1777 /var/mail
install -v -m700 -d /var/spool/mqueue

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo $(hostname) > /etc/mail/local-host-names
cat > /etc/mail/aliases << "EOF"
postmaster: root
MAILER-DAEMON: root

EOF
newaliases -v

m4 m4/cf.m4 sendmail.mc > sendmail.cf

#################
} # END OF FILE #
#################

