#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/sharutils/sharutils-4.11.1.tar.bz2"
MD5SUMLIST="52dd02b6f5e0a148ba871234ae29bba2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make check

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

