#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://swiss.csail.mit.edu/ftpdir/scm/OLD/slib-3b2.tar.gz"
MD5SUMLIST="850f48ad933e2fe8bb03b1e994ed4407"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's|usr/lib|usr/share|' RScheme.init
makeinfo -o slib.txt  --plaintext       slib.texi
makeinfo -o slib.html --html --no-split slib.texi

texi2pdf  slib.texi
texi2dvi  slib.texi
dvips  -o slib.ps   slib.dvi

make DESTDIR=${FAKEROOT} prefix=/usr/ \
     libdir=/usr/share/ \
     mandir=/usr/share/man/ \
     infodir=/usr/share/info/ \
  install installinfo

install -v -m755 -d ${FAKEROOT}/usr/share/doc/slib-3b2
install -v -m644    ANNOUNCE FAQ README slib.{txt,html} \
                    ${FAKEROOT}/usr/share/doc/slib-3b2

ln -v -s ../slib ${FAKEROOT}/usr/share/guile

install -v -m644 slib.{pdf,dvi,ps} \
                 ${FAKEROOT}/usr/share/doc/slib-3b2

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

guile -l guile.init \
      -c "(use-modules (ice-9 slib)) (require 'new-catalog)"

#################
} # END OF FILE #
#################

