#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.stunnel.org/download/stunnel/src/stunnel-4.46.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="978030ff42f087ec26eb8a095ab69994
            dontverify"
REQUIRES="openssl"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --disable-libwrap
make

make DESTDIR=${FAKEROOT} docdir=/usr/share/doc/stunnel-4.46 install

install -v -m750 -o stunnel -g stunnel -d ${FAKEROOT}/var/lib/stunnel/run

cat > ${FAKEROOT}/etc/stunnel/stunnel.conf << "EOF"
; File: /etc/stunnel/stunnel.conf

pid    = /run/stunnel.pid
chroot = /var/lib/stunnel
client = no
setuid = stunnel
setgid = stunnel
cert   = /etc/stunnel/stunnel.pem

EOF
chmod -v 644 ${FAKEROOT}/etc/stunnel/stunnel.conf

includeBootscript stunnel

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 51 stunnel
useradd -c "Stunnel Daemon" -d /var/lib/stunnel \
        -g stunnel -s /bin/false -u 51 stunnel

#################
} # END OF FILE #
#################

