#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/system-tools-backends/2.9/system-tools-backends-2.9.4.tar.bz2"
MD5SUMLIST="d12f83b03d0b9c2ed31557ed0193997b"
REQUIRES="dbus-glib intltool orbit2 pkgconfig polkit"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$(pkg-config --variable=prefix ORBit-2.0) \
            --sysconfdir=/etc/gnome/3.2.2
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

