#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://telepathy.freedesktop.org/releases/telepathy-farsight/telepathy-farsight-0.0.14.tar.gz"
MD5SUMLIST="1e6af31be4d5cdfc72a3f06542de96c0"
REQUIRES="farsight2 telepathy-glib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-python
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

