#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://telepathy.freedesktop.org/releases/telepathy-glib/telepathy-glib-0.16.0.tar.gz"
MD5SUMLIST="071ed1b34ace45109188df73933609e4"
REQUIRES="dbus-glib libxslt python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --libexecdir=/usr/lib/telepathy-glib
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

