#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://telepathy.freedesktop.org/releases/telepathy-logger/telepathy-logger-0.2.10.tar.bz2"
MD5SUMLIST="ec01a8f99fc11406e85153095433c155"
REQUIRES="intltool sqlite telepathy-glib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --libexecdir=/usr/lib/telepathy-logger
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

