#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/infosys/newsreaders/tin/v1.8/tin-1.8.3.tar.bz2"
MD5SUMLIST="e6ed45205020665c097556822b0d575b"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-screen=ncursesw \
    --enable-nntp-only --disable-printing
make build

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install_sysdefs
rm -vf doc/*.?
install -v -m755 -d ${FAKEROOT}/usr/share/doc/tin-1.8.3
install -v -m644 doc/* ${FAKEROOT}/usr/share/doc/tin-1.8.3

cat > ${FAKEROOT}/etc/tin/tinrc << "EOF"
use_mouse=ON
getart_limit=100
translit=ON
EOF

cat >> ~/.newsrc << "EOF"
gmane.linux.lfs.devel:
gmane.linux.lfs.beyond.devel:
EOF
export NNTPSERVER=news.gmane.org
tin -Q

#################
} # END OF FILE #
#################

