#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/tcl/tk8.5.9-src.tar.gz"
MD5SUMLIST="7cdeb9feb61593f58a0ae61f2497580e"
REQUIRES="tcl x-window-system"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cd unix
./configure --prefix=/usr \
            --enable-threads \
            --mandir=/usr/share/man
make
sed -i \
    -e "s@^\(TK_SRC_DIR='\).*@\1/usr/include'@" \
    -e "/TK_B/s@='\(-L\)\?.*unix@='\1/usr/lib@" \
    tkConfig.sh

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-private-headers
ln -v -sf wish8.5 ${FAKEROOT}/usr/bin/wish
chmod -v 755 ${FAKEROOT}/usr/lib/libtk8.5.so

#################
} # END OF FILE #
#################

