#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/tracker/0.12/tracker-0.12.3.tar.xz"
MD5SUMLIST="d794eca9dd1d957f7e2221520342de85"
REQUIRES="gstreamer icu intltool nautilus poppler sqlite vala"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libexecdir=/usr/lib/tracker-0.12 \
            --enable-miner-evolution=no \
            --enable-miner-firefox=no \
            --enable-miner-thunderbird=no \
            --disable-unit-tests
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

