#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://transcode.kabewm.com/transcode-1.0.3.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/transcode-1.0.3-libmpeg3_fixes-1.patch"
MD5SUMLIST="4f6eb832123ea28c54f0d4952733bcb6
            dontverify"
REQUIRES="ffmpeg libmpeg2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../transcode-1.0.3-libmpeg3_fixes-1.patch
sed -i 's|doc/transcode|&-$(PACKAGE_VERSION)|' \
       $(find . -name Makefile.in -exec grep -l 'docsdir =' {} \;)

autoconf
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

