#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www2.nl.vim.org/unix/vim-7.3.tar.bz2"
MD5SUMLIST="5b9510a17074e2b37d8bb38ae09edbf2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xf ../vim-7.3-lang.tar.gz --strip-components=1

echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h
echo '#define SYS_GVIMRC_FILE "/etc/gvimrc"' >> src/feature.h
./configure --prefix=/usr --with-features=huge
make

make DESTDIR=${FAKEROOT} install

ln -snfv ../vim/vim72/doc ${FAKEROOT}/usr/share/doc/vim-7.3

rsync -avzcP --delete --exclude="/dos/" --exclude="/spell/" \
    ftp.nluug.nl::Vim/runtime/ ./runtime/

make DESTDIR=${FAKEROOT} -C src installruntime
vim -c ":helptags ${FAKEROOT}/usr/share/doc/vim-7.3" -c ":q"

#################
} # END OF FILE #
#################

