#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/virtuoso/virtuoso-opensource-6.1.2.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="0519e1f104428e0c8b25fad89e3c57ef
            dontverify"
REQUIRES="net-tools"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --without-internal-zlib \
            --program-transform-name="s/isql/isql-v/"
make

make DESTDIR=${FAKEROOT} install

includeBootscript virtuoso

#################
} # END OF FILE #
#################

