#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="https://security.appspot.com/downloads/vsftpd-2.3.4.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2"
MD5SUMLIST="2ea5d19978710527bb7444d93b67767a
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

install -v -d -m 0755 ${FAKEROOT}/var/ftp/empty
install -v -d -m 0755 ${FAKEROOT}/home/ftp
groupadd -g 47 vsftpd
groupadd -g 45 ftp
useradd -c "vsftpd User"  -d ${FAKEROOT}/dev/null -g vsftpd -s ${FAKEROOT}/bin/false -u 47 vsftpd
useradd -c anonymous_user -d ${FAKEROOT}/home/ftp -g ftp    -s ${FAKEROOT}/bin/false -u 45 ftp

sed -i -e 's|#define VSF_SYSDEP_HAVE_LIBCAP|//&|' sysdeputil.c

make

install -v -m 755 vsftpd        /usr/sbin/vsftpd
install -v -m 644 vsftpd.8      /usr/share/man/man8
install -v -m 644 vsftpd.conf.5 /usr/share/man/man5
install -v -m 644 vsftpd.conf   /etc

cat >> ${FAKEROOT}/etc/vsftpd.conf << "EOF"
background=YES
listen=YES
nopriv_user=vsftpd
secure_chroot_dir=/var/ftp/empty
EOF

includeBootscript vsftpd

#################
} # END OF FILE #
#################

