#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.debian.org/debian/pool/main/w/whois/whois_5.0.12.tar.gz"
MD5SUMLIST="1147b6a993af384ba341cb91666c7e97"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make
make pos

make prefix=/usr install-whois
make prefix=/usr install-mkpasswd
make prefix=/usr install-pos

#################
} # END OF FILE #
#################

