#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.wireshark.org/download/src/all-versions/wireshark-0.99.6.tar.bz2"
MD5SUMLIST="e57a8c8b364c38df3da97e2ee9f0d0bc"
REQUIRES="glib2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --enable-threads
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/wireshark-0.99.6
install -v -m644    FAQ README{,.linux} doc/README.* doc/*.{pod,txt} \
                    ${FAKEROOT}/usr/share/doc/wireshark-0.99.6
pushd ${FAKEROOT}/usr/share/doc/wireshark-0.99.6
for FILENAME in ../../wireshark/*.html; do \
    ln -s -v $FILENAME .
done
popd

install -v -m644 -D wireshark.desktop \
                    ${FAKEROOT}/usr/share/applications/wireshark.desktop
install -v -m644 -D image/wsicon48.png \
                    ${FAKEROOT}/usr/share/pixmaps/wireshark.png
install -v -m755 -d ${FAKEROOT}/usr/share/pixmaps/wireshark
install -v -m644 image/*.{png,ico,xpm,bmp} \
                 ${FAKEROOT}/usr/share/pixmaps/wireshark

install -v -m644 <Downloaded_Files> ${FAKEROOT}/usr/share/doc/wireshark-0.99.6

#################
} # END OF FILE #
#################

