#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/files/BLFS/svn/sources/xfsprogs-3.1.7.tar.gz"
MD5SUMLIST="049cf9873794ea49d0bb3f12d45748a4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make DEBUG=-DNDEBUG INSTALL_USER=root INSTALL_GROUP=root \
    LOCAL_CONFIGURE_OPTIONS="--enable-readline=yes"

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-dev
chmod -v 755 ${FAKEROOT}/lib/libhandle.so.1.*

#################
} # END OF FILE #
#################

