#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/publishing/xpdf/xpdf-3.02.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/xpdf-3.02-consolidated_pl5-1.patch"
MD5SUMLIST="599dc4cc65a07ee868cf92a667a913d2
            dontverify"
REQUIRES="lesstif"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../xpdf-3.02-consolidated_pl5-1.patch
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-freetype2-includes=/usr/include/freetype2 \
            --enable-opi \
            --enable-multithreaded \
            --enable-wordlist
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

