#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.jwz.org/xscreensaver/xscreensaver-5.15.tar.gz"
MD5SUMLIST="c0b8b2c817a9a7371f51a82e80602d10"
REQUIRES="bc lesstif libglade"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --libexecdir=/usr/lib
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

