#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.tortall.net/projects/yasm/releases/yasm-1.2.0.tar.gz"
MD5SUMLIST="4cfc0686cf5350dd1305c4d905eb55a6"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's#) ytasm.*#)#' Makefile.in
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

