#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/opsys/linux/alsa/utils/alsa-utils-1.0.24.2.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20120206.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/alsa-utils-1.0.24.2-no_xmlto-1.patch"
MD5SUMLIST="8238cd57cb301d1c36bcf0ecb59ce6b2
            dontverify
            dontverify"
REQUIRES="alsa-lib"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../alsa-utils-1.0.24.2-no_xmlto-1.patch

./configure
make

make DESTDIR=${FAKEROOT} install

includeBootscript alsa

cat > ${FAKEROOT}/etc/udev/rules.d/40-alsa.rules << "EOF"
# /etc/udev/rules.d/40-alsa.rules

# When a sound device is detected, restore the volume settings
KERNEL=="controlC[0-9]*", ACTION=="add", RUN+="/usr/sbin/alsactl restore %n"
EOF
chmod -v 644 ${FAKEROOT}/etc/udev/rules.d/40-alsa.rules

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

mkdir -p /var/lib/alsa
touch /var/lib/alsa/asound.state
alsactl store

#usermod -a -G audio <username>

#################
} # END OF FILE #
#################

