#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://gd.tuwien.ac.at/opsys/linux/alsa/lib/alsa-lib-1.0.24.1.tar.bz2"
MD5SUMLIST="7cc05f25e1d5b65da8fb3fdcd540f226"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --enable-static
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D doc/asoundrc.txt \
    ${FAKEROOT}/usr/share/doc/alsa-lib-1.0.24.1/asoundrc.txt

#################
} # END OF FILE #
#################

