#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/ConsoleKit/dist/ConsoleKit-0.4.5.tar.bz2"
MD5SUMLIST="f2657f93761206922d558471a936fbc3"
REQUIRES="dbus-glib polkit x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc \
    --libexecdir=/usr/lib/ConsoleKit --localstatedir=/var
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

