#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://fontconfig.org/release/fontconfig-2.8.0.tar.gz"
MD5SUMLIST="77e15a92006ddc2adbb06f840d591c0e"
REQUIRES="expat freetype2 libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --disable-docs \
            --without-add-fonts \
            --docdir=/usr/share/doc/fontconfig-2.8.0
make

make DESTDIR=${FAKEROOT} install

install -v -m755 \
    -d ${FAKEROOT}/usr/share/{man/man{3,5},doc/fontconfig-2.8.0/fontconfig-devel}
install -v -m644 fc-*/*.1          ${FAKEROOT}/usr/share/man/man1
install -v -m644 doc/*.3           ${FAKEROOT}/usr/share/man/man3
install -v -m644 doc/fonts-conf.5  ${FAKEROOT}/usr/share/man/man5
install -v -m644 doc/fontconfig-devel/* \
    ${FAKEROOT}/usr/share/doc/fontconfig-2.8.0/fontconfig-devel
install -v -m644 doc/*.{pdf,sgml,txt,html} \
    ${FAKEROOT}/usr/share/doc/fontconfig-2.8.0

#################
} # END OF FILE #
#################

