#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/glib/2.30/glib-2.30.2.tar.xz"
MD5SUMLIST="b7dd26aa83de0b59c867a0b9eb9f9462"
REQUIRES="libffi pcre python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

PCRE_LIBS=-lpcre  PCRE_CFLAGS=" "                                \
LIBFFI_LIBS=-lffi LIBFFI_CFLAGS=-I/usr/lib/libffi-3.0.10/include \
./configure --prefix=/usr --sysconfdir=/etc --with-pcre=system
make

make DESTDIR=${FAKEROOT} install
ln -v -sfn ../../lib/glib-2.0/include/glibconfig.h ${FAKEROOT}/usr/include/glib-2.0/glibconfig.h

cat > ${FAKEROOT}/etc/profile.d/glib2-locale.sh << "EOF"
# Use the current locale charset for filenames
# in applications using GLib
export G_FILENAME_ENCODING=@locale
EOF

#################
} # END OF FILE #
#################

