#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/sources/BLFS/svn/l/libgpg-error-1.10.tar.bz2"
MD5SUMLIST="736a03daa9dc5873047d4eb4a9c22a16"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m644 -D README ${FAKEROOT}/usr/share/doc/libgpg-error-1.10/README

#################
} # END OF FILE #
#################

