#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="ftp://ftp.freedesktop.org/pub/mesa/7.11.2/MesaLib-7.11.2.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/MesaLib-7.11.2-add_xdemos-2.patch
          http://www.linuxfromscratch.org/patches/blfs/svn/MesaLib-7.11.2-llvm_3.0-1.patch"
MD5SUMLIST="0837c52698fe3252369c3fdb5195afcc
            dontverify
            dontverify"
REQUIRES="expat libdrm llvm makedepend talloc x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed 's@FLAGS=\"-g@FLAGS=\"@' -i configure
patch -Np1 -i ../MesaLib-7.11.2-llvm_3.0-1.patch
patch -Np1 -i ../MesaLib-7.11.2-add_xdemos-2.patch
./configure $XORG_CONFIG --enable-xcb
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}${XORG_PREFIX}/share/doc/MesaLib-7.11.2
install -v -m644    docs/* \
                    ${FAKEROOT}${XORG_PREFIX}/share/doc/MesaLib-7.11.2

if [ "${XORG_PREFIX}" != "/usr" ]; then
    ln -s -v ${XORG_PREFIX}/include/GL  ${FAKEROOT}/usr/include
    ln -s -v ${XORG_PREFIX}/include/EGL ${FAKEROOT}/usr/include
    ln -s -v ${XORG_PREFIX}/include/KHR ${FAKEROOT}/usr/include
fi

#################
} # END OF FILE #
#################

