#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.nasm.us/pub/nasm/releasebuilds/2.09.10/nasm-2.09.10.tar.bz2
          http://www.nasm.us/pub/nasm/releasebuilds/2.09.10/nasm-2.09.10-xdoc.tar.bz2"
MD5SUMLIST="15c79dcb5838870a0fac15feb5fade66
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

pushd ..
tar -xf nasm-2.09.10-xdoc.tar.bz2
popd

./configure --prefix=/usr
make

make INSTALLROOT=${FAKEROOT} install

install -m755 -d         ${FAKEROOT}/usr/share/doc/nasm-2.09.10/html
cp -v doc/html/*.html    ${FAKEROOT}/usr/share/doc/nasm-2.09.10/html
cp -v doc/*.{txt,ps,pdf} ${FAKEROOT}/usr/share/doc/nasm-2.09.10
cp -v doc/info/*         ${FAKEROOT}/usr/share/info

#################
} # END OF FILE #
#################

