#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://www.lysator.liu.se/~nisse/archive/nettle-2.4.tar.gz"
MD5SUMLIST="450be8c4886d46c09f49f568ad6fa013"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/nettle-2.4
install -v -m644 nettle.html ${FAKEROOT}/usr/share/doc/nettle-2.4

#################
} # END OF FILE #
#################

