#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/pcre/pcre-8.30.tar.bz2"
MD5SUMLIST="98e8928cccc945d04279581e778fbdff"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static --libdir=/lib \
  --docdir=/usr/share/doc/pcre-8.30 --enable-utf8 --enable-unicode-properties \
  --enable-pcregrep-libz --enable-pcregrep-libbz2
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

