#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://upower.freedesktop.org/releases/upower-0.9.14.tar.xz"
MD5SUMLIST="18803f82102d56aac90949d1e4251645"
REQUIRES="dbus-glib libusb polkit udev-rebuild"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --libexecdir=/usr/lib/upower
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

