#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2012-02-12 / r9383) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2012, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/xserver/xorg-server-1.11.2.tar.bz2"
MD5SUMLIST="8796fff441e5435ee36a72579008af24"
REQUIRES="openssl pixman x7font xkeyboard-config"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG \
    --with-module-dir=$XORG_PREFIX/lib/X11/modules \
    --with-xkb-output=/var/lib/xkb \
    --enable-install-setuid
make

make DESTDIR=${FAKEROOT} install
ln -s $XORG_PREFIX/share/X11/xorg.conf.d ${FAKEROOT}/etc/X11

#################
} # END OF FILE #
#################

