#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://ftp.acc.umu.se/pub/GNOME/sources/network-manager-applet/0.9/network-manager-applet-0.9.2.0.tar.xz"
MD5SUMLIST="dontverify"
REQUIRES="networkmanager iso-codes mate-keyring libnotify_compat"

# Note: 'wpa-supplicant' can be used at run time to configure secured wireless
#       connections.

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

# (*) Convert source code to Mate
convertToMate
mv -v src/gconf-helpers/tests/fake-{g,mate}conf.h
mv -v src/gconf-helpers/tests/fake-{g,mate}conf.c
mv -v src/gconf-helpers/{g,mate}conf-helpers.c
mv -v src/gconf-helpers/{g,mate}conf-upgrade.h
mv -v src/gconf-helpers/{g,mate}conf-upgrade.c
mv -v src/gconf-helpers/{g,mate}conf-helpers.h
mv -v src/{g,mate}conf-helpers
mv -v src/{gnome,mate}-bluetooth

./configure --prefix=/usr \
        --sysconfdir=/etc/mate/${MATE_RELEASE}
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

