#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://hostap.epitest.fi/releases/wpa_supplicant-0.7.3.tar.gz"
MD5SUMLIST="dontverify"
REQUIRES="openssl pkgconfig dbus libnl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

# Allow linking against LIBNL-3.2.x
sed 's/-lnl/-lnl-3/g' -i src/drivers/drivers.mak
sed 's/-lnl-3-genl/-lnl-genl-3/g' -i src/drivers/drivers.mak

pushd wpa_supplicant

cp -v defconfig .config
cat >> .config << "EOF"
# (*) Configure with DBUS and NL80211 driver support (req'd for NetworkManager)
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_DRIVER_NL80211=y
CONFIG_LIBNL20=y

# Allow linking against LIBNL-3.2.x
CFLAGS += -I/usr/include/libnl3
EOF

make

cp -v wpa_cli wpa_passphrase wpa_supplicant ${FAKEROOT}/sbin

pushd dbus
cp -v dbus-wpa_supplicant.conf ${FAKEROOT}/etc/dbus-1/system.d/
cp -v *.service ${FAKEROOT}/usr/share/dbus-1/system-services/
popd

popd

#################
} # END OF FILE #
#################

