#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://sourceforge.net/projects/check/files/check/0.9.8/check-0.9.8.tar.gz"
MD5SUMLIST="5d75e9a6027cde79d2c339ef261e7470"

###################################################
preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
###################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

