#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/diffutils/diffutils-3.2.tar.gz"
MD5SUMLIST="22e4deef5d8949a727b159d6bc65c1cc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

