#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/gdbm/gdbm-1.10.tar.gz"
MD5SUMLIST="88770493c2559dc80b561293e39d3570"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-libgdbm-compat

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

