#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/glibc/glibc-2.14.1.tar.bz2
          http://www.linuxfromscratch.org/patches/lfs/development/glibc-2.14.1-cpuid-1.patch
          http://www.linuxfromscratch.org/patches/lfs/development/glibc-2.14.1-fixes-1.patch
          http://www.linuxfromscratch.org/patches/lfs/development/glibc-2.14.1-gcc_fix-1.patch"
MD5SUMLIST="5869a2620c6917dd392289864c6ce595
            4f110dc9c8d4754fbda841492ce796b4
            13bdfb7db1654d9c3d7934d24479a6c4
            d1f28cb98acb9417fe52596908bbb9fd"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

DL=$(readelf -l /bin/sh | sed -n 's@.*interpret.*/tools\(.*\)]$@\1@p')
sed -i "s|libs -o|libs -L/usr/lib -Wl,-dynamic-linker=$DL -o|" \
        scripts/test-installation.pl
unset DL

sed -i -e 's/"db1"/& \&\& $name ne "nss_test1"/' scripts/test-installation.pl

sed -i 's|@BASH@|/bin/bash|' elf/ldd.bash.in

patch -Np1 -i ../glibc-2.14.1-fixes-1.patch

patch -Np1 -i ../glibc-2.14.1-gcc_fix-1.patch

sed -i '195,213 s/PRIVATE_FUTEX/FUTEX_CLOCK_REALTIME/' \
nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_timed{rd,wr}lock.S

mkdir -v ../glibc-build
cd ../glibc-build

case `uname -m` in
  i?86) echo "CFLAGS += -march=i486 -mtune=native -O3 -pipe" > configparms ;;
esac

../glibc-2.14.1/configure --prefix=/usr \
    --disable-profile --enable-add-ons \
    --enable-kernel=2.6.25 --libexecdir=/usr/lib/glibc

make

touch ${FAKEROOT}/etc/ld.so.conf

make install_root=${FAKEROOT} install

cp -v ../glibc-2.14.1/sunrpc/rpc/*.h ${FAKEROOT}/usr/include/rpc
cp -v ../glibc-2.14.1/sunrpc/rpcsvc/*.h ${FAKEROOT}/usr/include/rpcsvc
cp -v ../glibc-2.14.1/nis/rpcsvc/*.h ${FAKEROOT}/usr/include/rpcsvc

make install_root=${FAKEROOT} localedata/install-locales

cat > ${FAKEROOT}/etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

hosts: files dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF

cat > ${FAKEROOT}/etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib

EOF

cat >> ${FAKEROOT}/etc/ld.so.conf << "EOF"
# Add an include directory
include /etc/ld.so.conf.d/*.conf

EOF
mkdir ${FAKEROOT}/etc/ld.so.conf.d

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) This will run 'tzselect' to determine your timezone when installing your
#     system, unless you have set up the TZ variable in 'install.conf'.
if [ "${LFSCRIPT_INSTALL}" == "true" ]; then
    [ "${TZ}" == "" ] && TZ="$(tzselect)"
else
    TZ="UTC"
fi
#tzselect

# (*) This will set the time zone to the one selected earlier.
cp -v --remove-destination /usr/share/zoneinfo/${TZ} \
    /etc/localtime

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

patch -Np1 -i ../glibc-2.14.1-gcc_fix-1.patch

patch -Np1 -i ../glibc-2.14.1-cpuid-1.patch

mkdir -v ../glibc-build
cd ../glibc-build

case `uname -m` in
  i?86) echo "CFLAGS += -march=i486 -mtune=native" > configparms ;;
esac

../glibc-2.14.1/configure --prefix=/tools \
    --host=$LFS_TGT --build=$(../glibc-2.14.1/scripts/config.guess) \
    --disable-profile --enable-add-ons \
    --enable-kernel=2.6.25 --with-headers=/tools/include \
    libc_cv_forced_unwind=yes libc_cv_c_cleanup=yes

make

make install

#################
} # END OF FILE #
#################

