#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/grep/grep-2.10.tar.xz"
MD5SUMLIST="709915434d09f5db655e5ebd7fd6bb7f"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/cp/#&/' tests/unibyte-bracket-expr

./configure --prefix=/usr --bindir=/bin

make

make DESTDIR=${FAKEROOT} install

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools \
    --disable-perl-regexp

make

make install

#################
} # END OF FILE #
#################

