#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/groff/groff-1.21.tar.gz"
MD5SUMLIST="8b8cd29385b97616a0f0d96d0951c5bf"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

PAGE=A4 ./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

ln -sv eqn ${FAKEROOT}/usr/bin/geqn
ln -sv tbl ${FAKEROOT}/usr/bin/gtbl

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) This will change the default paper size for groff when installing your
#     system, if you have set up the PAGE variable in 'install.conf'.
if [ "${LFSCRIPT_INSTALL}" == "true" ]; then
    [ "${PAGE}" != "" ] && echo "${PAGE}" > /etc/papersize
fi

#################
} # END OF FILE #
#################

