#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/grub/grub-1.99.tar.gz"
MD5SUMLIST="ca9f2a2d571b57fc5c53212d1d22e2b5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr           \
             --sysconfdir=/etc      \
             --disable-grub-emu-usb \
             --disable-efiemu       \
             --disable-werror

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

