#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/inetutils/inetutils-1.9.1.tar.gz"
MD5SUMLIST="944f7196a2b3dba2d400e9088576000c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --libexecdir=/usr/sbin \
    --localstatedir=/var --disable-ifconfig \
    --disable-logger --disable-syslogd --disable-whois \
    --disable-servers

make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} -C doc html
make DESTDIR=${FAKEROOT} -C doc install-html docdir=/usr/share/doc/inetutils-1.9.1

mv -v ${FAKEROOT}/usr/bin/{hostname,ping,ping6} ${FAKEROOT}/bin
mv -v ${FAKEROOT}/usr/bin/traceroute ${FAKEROOT}/sbin

#################
} # END OF FILE #
#################

