#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-3.2.0.tar.xz"
MD5SUMLIST="6f814291cc3d7f4312cf8c2c052da5f1"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/^TARGETS/s@arpd@@g' misc/Makefile
sed -i /ARPD/d Makefile
rm man/man8/arpd.8

sed -i -e '/netlink\//d' ip/ipl2tp.c

make DESTDIR=

make DESTDIR=${FAKEROOT} MANDIR=/usr/share/man \
     DOCDIR=/usr/share/doc/iproute2-3.2.0 install

#################
} # END OF FILE #
#################

