#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://packages.profusion.mobi/kmod/kmod-5.tar.xz"
MD5SUMLIST="b271c2ec54aba1c67bda63c8579d8c15"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

liblzma_CFLAGS="-I/usr/include" \
liblzma_LIBS="-L/lib -llzma"    \
zlib_CFLAGS="-I/usr/include"    \
zlib_LIBS="-L/lib -lz"          \
./configure --prefix=/usr --bindir=/bin --libdir=/lib --sysconfdir=/etc \
            --with-xz     --with-zlib

make

make DESTDIR=${FAKEROOT} pkgconfigdir=/usr/lib/pkgconfig install
for target in depmod insmod modinfo modprobe rmmod; do
  ln -sv ../bin/kmod ${FAKEROOT}/sbin/$target
done
ln -sv kmod ${FAKEROOT}/bin/lsmod

#################
} # END OF FILE #
#################

