#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://www.greenwoodsoftware.com/less/less-444.tar.gz"
MD5SUMLIST="56f9f76ffe13f70155f47f6b3c87d421"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

