#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.2.5.tar.xz"
MD5SUMLIST="61d9a063d3265112ba7ec1d9a501a086"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make mrproper

make headers_check
make INSTALL_HDR_PATH=dest headers_install
find dest/include \( -name .install -o -name ..install.cmd \) -delete

cp -rv dest/include/* ${FAKEROOT}/usr/include

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

make mrproper

make headers_check
make INSTALL_HDR_PATH=dest headers_install

cp -rv dest/include/* /tools/include

#################
} # END OF FILE #
#################

