#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/patch/patch-2.6.1.tar.bz2
          http://www.linuxfromscratch.org/patches/lfs/development/patch-2.6.1-test_fix-1.patch"
MD5SUMLIST="0818d1763ae0c4281bcdc63cdac0b2c0
            c51e1a95bfc5310635d05081472c3534"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../patch-2.6.1-test_fix-1.patch

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

