#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://prdownloads.sourceforge.net/psmisc/psmisc-22.15.tar.gz"
MD5SUMLIST="35e155bae2e499a6dcba35884560db1e"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/fuser ${FAKEROOT}/bin
mv -v ${FAKEROOT}/usr/bin/killall ${FAKEROOT}/bin

#################
} # END OF FILE #
#################

