#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://pkg-shadow.alioth.debian.org/releases/shadow-4.1.4.3.tar.bz2"
MD5SUMLIST="b8608d8294ac88974f27b20f991c0e79"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \;

sed -i 's/man_MANS = $(man_nopam) /man_MANS = /' man/ru/Makefile.in

sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs

./configure --sysconfdir=/etc

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/passwd ${FAKEROOT}/bin

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

pwconv

grpconv

sed -i 's/yes/no/' /etc/default/useradd

# (*) The password for root will be set during interactive configuration.
#passwd root

#################
} # END OF FILE #
#################

