#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.88dsf.tar.bz2"
MD5SUMLIST="6eda8a97b86e0a6f59dabbf25202aa6f"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's@Sending processes@& configured via /etc/inittab@g' \
    src/init.c

sed -i -e 's/utmpdump wall/utmpdump/' \
       -e '/= mountpoint/d' \
       -e 's/mountpoint.1 wall.1//' src/Makefile

make -C src

make ROOT=${FAKEROOT} -C src install

#################
} # END OF FILE #
#################

