#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/tar/tar-1.26.tar.bz2"
MD5SUMLIST="2cee42a2ff4f1cd4f9298eeeb2264519"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr \
   --bindir=/bin --libexecdir=/usr/sbin

make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} -C doc install-html docdir=/usr/share/doc/tar-1.26

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

