#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/texinfo/texinfo-4.13a.tar.gz"
MD5SUMLIST="71ba711519209b5fb583fed2b3d86fcb"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} TEXMF=/usr/share/texmf install-tex

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

pushd /usr/share/info
rm -vf dir
for FILENAME in *; do
    install-info ${FILENAME} dir 2>/dev/null
done
popd

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

