#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://www.kernel.org/pub/linux/utils/kernel/hotplug/udev-181.tar.xz
          http://www.linuxfromscratch.org/lfs/downloads/development/udev-config-20100128.tar.bz2"
MD5SUMLIST="0d7af750702620a871b9f9b98d8ad859
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xvf ../udev-config-20100128.tar.bz2

install -dv ${FAKEROOT}/lib/{firmware,udev/devices/pts}
mknod -m0666 ${FAKEROOT}/lib/udev/devices/null c 1 3

BLKID_CFLAGS="-I/usr/include/blkid"  \
BLKID_LIBS="-L/lib -lblkid"          \
KMOD_CFLAGS="-I/usr/include"         \
KMOD_LIBS="-L/lib -lkmod"            \
./configure  --prefix=/usr           \
             --with-rootprefix=''    \
             --bindir=/sbin          \
             --sysconfdir=/etc       \
             --libexecdir=/lib       \
             --enable-rule_generator \
             --disable-introspection \
             --disable-keymap        \
             --disable-gudev         \
             --with-usb-ids-path=no  \
             --with-pci-ids-path=no  \
             --with-systemdsystemunitdir=no

make

make DESTDIR=${FAKEROOT} install

rmdir -v ${FAKEROOT}/usr/share/doc/udev

cd udev-config-20100128
make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} install-doc

#################
} # END OF FILE #
#################

