#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://tukaani.org/xz/xz-5.0.3.tar.bz2"
MD5SUMLIST="8d900b742b94fa9e708ca4f5a4b29003"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --libdir=/lib --docdir=/usr/share/doc/xz-5.0.3

make

make DESTDIR=${FAKEROOT} pkgconfigdir=/usr/lib/pkgconfig install

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

