#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/automake/automake-1.11.3.tar.xz"
MD5SUMLIST="3d72b2076eb4397ad5e9a2aace6357fd"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.11.3

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

