#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://prdownloads.sourceforge.net/flex/flex-2.5.35.tar.bz2
          http://www.linuxfromscratch.org/patches/lfs/development/flex-2.5.35-gcc44-1.patch"
MD5SUMLIST="10714e50cea54dc7a227e3eddcd44d57
            ad9109820534278c6dd0898178c0788f"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../flex-2.5.35-gcc44-1.patch

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

ln -sv libfl.a ${FAKEROOT}/usr/lib/libl.a

cat > ${FAKEROOT}/usr/bin/lex << "EOF"
#!/bin/sh
# Begin /usr/bin/lex

exec /usr/bin/flex -l "$@"

# End /usr/bin/lex
EOF
chmod -v 755 ${FAKEROOT}/usr/bin/lex

mkdir -v ${FAKEROOT}/usr/share/doc/flex-2.5.35
cp    -v doc/flex.pdf \
         ${FAKEROOT}/usr/share/doc/flex-2.5.35

#################
} # END OF FILE #
#################

