#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.2.5.tar.xz"
MD5SUMLIST="61d9a063d3265112ba7ec1d9a501a086"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

#make mrproper

make

make INSTALL_MOD_PATH=${FAKEROOT} modules_install

cp -v arch/x86/boot/bzImage ${FAKEROOT}/boot/vmlinuz-3.2.5-lfs-SVN-20120211

cp -v System.map ${FAKEROOT}/boot/System.map-3.2.5

cp -v .config ${FAKEROOT}/boot/config-3.2.5

install -d ${FAKEROOT}/usr/share/doc/linux-3.2.5
cp -r Documentation/* ${FAKEROOT}/usr/share/doc/linux-3.2.5

install -v -m755 -d ${FAKEROOT}/etc/modprobe.d
cat > ${FAKEROOT}/etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf

install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

# End /etc/modprobe.d/usb.conf
EOF

#################
} # END OF FILE #
#################

