#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://www.mpfr.org/mpfr-3.1.0/mpfr-3.1.0.tar.bz2
          http://www.linuxfromscratch.org/patches/lfs/development/mpfr-3.1.0-fixes-1.patch"
MD5SUMLIST="238ae4a15cc3a5049b723daef5d17938
            6a1a0be6f2326e237ce27a0254e360a5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../mpfr-3.1.0-fixes-1.patch

./configure --prefix=/usr --enable-thread-safe \
  --docdir=/usr/share/doc/mpfr-3.1.0

make

make DESTDIR=${FAKEROOT} install

make html

make DESTDIR=${FAKEROOT} install-html

#################
} # END OF FILE #
#################

