#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.1' (SVN-20120211 / r9742) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2012, Gerard Beekmans

WGETLIST="http://procps.sourceforge.net/procps-3.2.8.tar.gz
          http://www.linuxfromscratch.org/patches/lfs/development/procps-3.2.8-fix_HZ_errors-1.patch
          http://www.linuxfromscratch.org/patches/lfs/development/procps-3.2.8-watch_unicode-1.patch"
MD5SUMLIST="9532714b6846013ca9898984ba4cd7e0
            2ea4c8e9a2c2a5a291ec63c92d7c6e3b
            cd1a757e532d93662a7ed71da80e6b58"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../procps-3.2.8-fix_HZ_errors-1.patch

patch -Np1 -i ../procps-3.2.8-watch_unicode-1.patch

sed -i -e 's@\*/module.mk@proc/module.mk ps/module.mk@' Makefile

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

