#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-session-manager-1.1.2.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="mate-panel upower consolekit" # gconf gtk+2 orbit2 pkgconfig startup-notification upower

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
        --libexecdir=${MATE_PREFIX}/lib \
\
        --mandir=${MATE_PREFIX}/share/man \
\
        --localstatedir=/var \
        --enable-splash
make

make DESTDIR=${FAKEROOT} install

# (*) Configuring the Core MATE Packages
echo "exec ck-launch-session mate-session" \
        > ${FAKEROOT}/etc/X11/app-defaults/xinitrc.d/Mate.xinitrc

#################
} # END OF FILE #
#################

