#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-control-center-1.1.0.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="mate-settings-daemon desktop-file-utils" # gnome-doc-utils gnome-menus gnome-settings-daemon libunique metacity orbit2 pkgconfig shared-mime-info

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
        --localstatedir=/var/lib \
\
        --libexecdir=${MATE_PREFIX}/lib/mate-control-center \
\
        --disable-static --disable-scrollkeeper
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

