#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-icon-theme-1.1.1.tar.xz"
MD5SUMLIST="dontverify"
REQUIRES="libmateweather icon-naming-utils" # icon-naming-utils intltool

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX}
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

