#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/libmatecomponentui-1.1.1.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="libmatecanvas" # libglade libgnome libgnomecanvas orbit2 pkgconfig

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
\
        --localstatedir=/var \
        --sysconfdir=/etc \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}${MATE_PREFIX}/share/doc/libmatecomponentui
install -v -m644 doc/*.{dtd,txt,xml,html} \
        ${FAKEROOT}${MATE_PREFIX}/share/doc/libmatecomponentui

#################
} # END OF FILE #
#################

