#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/libmateweather-1.1.0.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="libmatekbd libsoup_compat" # gtk+2 intltool libsoup orbit2 pkgconfig

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
\
        --localstatedir=/var \
        --disable-static --enable-locations-compression
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

