#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-desktop-1.1.1.tar.xz"
MD5SUMLIST="dontverify"
REQUIRES="mate-dialogs" # gconf gnome-doc-utils gtk+2 orbit2 pkgconfig which x7lib

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
        --localstatedir=/var/lib \
\
        --disable-static --disable-scrollkeeper
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

