#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-window-manager-1.1.0.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="mate-menus" # gconf gtk+2 libcanberra perl-xml-parser zenity

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc \
\
        --libexecdir=${MATE_PREFIX}/lib/mate-window-manager \
        --with-mateconf-schema-file-dir=/etc/mate/${MATE_RELEASE}/mateconf/schemas \
\
        --localstatedir=/var \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}${MATE_PREFIX}/share/doc/mate-window-manager
install -v -m644 README rationales.txt doc/*.txt \
        ${FAKEROOT}${MATE_PREFIX}/share/doc/mate-window-manager

cat > ${FAKEROOT}/etc/X11/app-defaults/xinitrc.d/Marco_\(with_an_XTerm\).xinitrc << "EOF"
xterm &
exec marco
EOF

#################
} # END OF FILE #
#################

