#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-menus-1.1.1.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="mate-backgrounds" # glib2 intltool orbit2 pkgconfig python2
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
\
        --localstatedir=/var \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo "export XDG_CONFIG_DIRS=/etc/mate/${MATE_RELEASE}/xdg" \
> /etc/profile.d/mate.sh

echo "export XDG_DATA_DIRS=${MATE_PREFIX}/share:\
/usr/share:/usr/local/share" >> /etc/profile.d/mate.sh

#echo "export PYTHONPATH=\$PYTHONPATH:\
#${MATE_PREFIX}/lib/python2.7/site-packages/GMenuSimpleEditor" \
#>> /etc/profile.d/mate.sh

#################
} # END OF FILE #
#################

