#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-common-1.1.0.tar.bz2"
MD5SUMLIST="dontverify"

# 'mate-common' actually does not require anything, however this list of
# dependencies is shared by a lot (if not all) packages that also require
# 'mate-common'
#which glib2 intltool pkgconfig gtk-doc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX}
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

