#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-keyring-1.1.0.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="libmatekeyring libtasn1" # dbus gtk+2 intltool libgcrypt libtasn1 orbit2 pkgconfig

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --libexecdir=${MATE_PREFIX}/lib/mate-keyring \
        --sysconfdir=/etc/mate/${MATE_RELEASE} \
        --with-pam-dir=/lib/security \
        --with-root-certs=/etc/ssl/certs \
\
        --with-dbus-services=/usr/share/dbus-1/services \
\
        --localstatedir=/var \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

