#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2012 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.1/mate-dialogs-1.1.0.tar.bz2"
MD5SUMLIST="dontverify"
REQUIRES="mate-icon-theme" # gnome-doc-utils gtk+2 orbit2 pkgconfig which

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=${MATE_PREFIX} \
        --localstatedir=/var/lib \
\
        --mandir=${MATE_PREFIX}/share/man \
\
        --sysconfdir=/etc \
        --disable-scrollkeeper
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

